### ISSUE TITLE
Support for all WordPress translation functions?

### ISSUE THREAD

**Issue by deckerweb** [vslavik/poedit#109]
Currently, there's missing support for the function "load_child_theme_textdomain()" -- that should be added of course.

Also, in some cases the path and/or textdomain gets not recognized from Poedit. However those cases are hard to find out.

I just opened this ticket to start tracking this stuff and hopefully have it improved then in Poedit. So I may add and report related stuff with missing i18n functions from WP plus path/textdomain problems here.

**Comment by vslavik** [comment]
Results of 1.7.3 code on the themes from https://wordpress.org/themes/ are good, I think:

I crawled all 1630 maintained themes (i.e. with updates in the last 2 years and w/o a warning shown in the directory). From these
- 1300 worked with Poedit
- 320 had no localization support whatsoever
- 10 had some Poedit failures

A grand total of *three* of the failures were genuine: something that would require much deeper interpretation; the remaining 7 were either didn't have l10n support and were misdetected (a comment saying that they used `load_theme_textdomain`, but they didn't, Poedit thought the comment was code) or had broken domain-loading calls (using `get_template_directory_uri()` instead of `get_template_directory()`) and so effectively didn't have *working* l10n either.

When I included unmaintained themes too (total 2928), there were many more w/o l10n (1256) and 16 failures (after analyzing them, they added 3 more "genuine" ones, the other 3 were one of the above cases).

**Comment by vslavik** [comment]
It's less rosy for https://wordpress.org/plugins/, mainly due to the sheer number of them. I tested 19717 maintained plugins and from these

- 6286 were OK
- 12649 had no localization support
- 782 had some Poedit failures

It's worth noting that none of the 782 plugins ship with any PO files. Many of those (guestimate 40-50%) are incorrect, broken `load_plugin_textdomain` uses that don't work and Poedit *shouldn't* recognize them as good. But there are lots of legitimate code that Poedit fails to understand — the trouble is that these unhandled `load_plugin_textdomain` calls are pretty much all unique; I think I reached the limits of static analysis here.

Right now, the most appealing course seems to me to either start sending patches to developers or have some manually curated whitelist (or both). Or to (continue to) handle these edge cases as support requests.

**Comment by madeinua** [comment]
Is this possible to implement the text domain keyword? E.g. __:1,2d (d -> indicates the textdomain). Of course the perfect scenario is the possibility to specify the text domain to fetch translations only for it (i.e. I have two different text domains within one php file).

**Comment by vslavik** [comment]
@madeinua Please read GNU gettext documentation. Please don’t post off-topic comments on random issues.

**Comment by vslavik** [comment]
Closing — realized this is outdated now.
