### ISSUE TITLE
Incorrect error when having different amount of parameters for singular/plural messages

### ISSUE THREAD

**Issue by janlaan** [vslavik/poedit#137]
See the screenshot below. I have a translation with a different amount of parameters for the singular and plural message. I believe my translation is in the correct format, but Poedit says there is an error. The .mo file is however compiled correctly.

![image](https://cloud.githubusercontent.com/assets/233992/5874836/8fa3c144-a306-11e4-8f89-0a3370ab4dd1.png)

**Comment by vslavik** [comment]
>  I believe my translation is in the correct format, but Poedit says there is an error.

Did you consider the possibility that your belief is incorrect and Poedit's (`msgfmt`, actually) check is right? Because that's exactly the case: `msgfmt` validates per target language's requirements and if it reports an error, you *have* to fix it for the translation to work correctly.

It even tells you exactly what is wrong with the translation: you didn't use `%d` in the first one and you simply *can't* do it like that (if you insist on using "Een", try positional format specifiers, that may be more permissive). In any case, there's nothing Poedit itself can do about it.

P.S. Please only use the issue tracker when you're sure it is a bug; there are better support channels listed at http://poedit.net/support for other situations.
