### ISSUE TITLE
Windows disappear on Mac OS 10.10.3 for Poedit 1.7.4 and 1.7.5

### ISSUE THREAD

**Issue by pkarjala** [vslavik/poedit#157]
This issue occurs on Poedit 1.7.4 and 1.7.5 under Mac OS 10.10.3.

When Poedit is launched, the main editor window does not appear: 
![screenshot1](https://cloud.githubusercontent.com/assets/5232936/7150802/aad26c6e-e2bb-11e4-85f7-c646b0838847.png)

If the user switches to Full Screen via the View -> Enter Full Screen dialog window:

![screen shot 2015-04-14 at 3 34 22 pm](https://cloud.githubusercontent.com/assets/5232936/7150811/d0e18084-e2bb-11e4-874f-e0243e38ca30.png)

Then the editor window finally appears, but does not load the Toolbar for the window, as in this screenshot:
![screen shot 2015-04-14 at 3 37 36 pm](https://cloud.githubusercontent.com/assets/5232936/7150834/3af0c85e-e2bc-11e4-8cf5-183b072c0cdf.png)

Exiting full screen returns to the same state as the first screenshot.

The program does function normally while it is in full screen mode, but none of the top Toolbar items are available, and must be accessed through the menu:

![screen shot 2015-04-14 at 3 42 33 pm](https://cloud.githubusercontent.com/assets/5232936/7150866/089eee0c-e2bd-11e4-9a6d-2c6cf3bd1689.png)

I first encountered this on Poedit 1.7.4, and tried a reboot of my system.  I uninstalled the program and installed Poedit 1.7.5, which had the same behavior.

I am glad to perform any testing to help debug this issue.  The issue only occurred after upgrading to Mac OS 10.10.3.  I unfortunately do not have another system with an older OS version to test with at this time.

**Comment by vslavik** [comment]
Previously in this thread: https://groups.google.com/d/msg/poedit/z-zat7DS76Y/o0ZDxZRgI2IJ

**Comment by vslavik** [comment]
I very much doubt this is specific to 1.7.{4,5} or 10.10.3 — as you know, the same thing (probably) was reported with an older OS X version. I have no other reports of any 10.10.3 craziness, nor do I see anything wrong on it. Whatever the differentiating factor is, it’s something else, but I have no idea what, so the following is a bit of a fishing expedition:

1. Are you absolutely *sure* the download was OK? MD5 of `Poedit-1.7.5.zip` is `b4c667cf802ffe25f05899feab433785`, can you check?
2. Asking because this very much looks like a broken app bundle, as if it failed to load a part of it. Is there `toolbar.xrc` file present in `Poedit.app/Contents/Resources`? Does running `xmllint —noout toolbar.xrc` output anything if it is there?
3. What is the full path to your `Poedit.app` (any spaces or non-ASCII chars in it)?
4. Any difference with 1.8beta1 from http://poedit.net/download ?
5. Any multi-display setup involved, now or recently, including using a Macbook with external display?
6. OS language is English (US) from the looks of it? 
7. Could you attach or email me your `~/Library/Preferences/net.poedit.Poedit.plist` and `~/Library/Preferences/net.poedit.Poedit.cfg`?

TIA!

**Comment by pkarjala** [comment]
1. Output of `$ md5 Poedit-1.7.5.zip` is `MD5 (Poedit-1.7.5.zip) = b4c667cf802ffe25f05899feab433785`
2. `toolbar.xrc` is present in `Poedit.app/Contents/Resources`.  `xmllint -noout toolbar.xrc` returns no output; `xmllint toolbar.xrc` outputs the contents of the XML file.
3. `pwd` output is `/Applications/Poedit.app`
4. No; Same behavior with the downloaded `1.8beta1`.
5. Yes, on a MacBook Pro, one Apple Lightning display, one HDMI Dell display.  Disconnecting both displays results in the same behavior on just the laptop display.
6. Yes, US English.
7. I have sent an email from pkarjala@gmail.com with the requested files.

**Comment by vslavik** [comment]
> Yes, on a MacBook Pro, one Apple Lightning display, one HDMI Dell display.

*This* is the culprit, then. And thanks to your config file, I was able to reproduce it. Could you please try the build from http://cl.ly/1T1q2o3s163V to see if it fixes it? If you could subject it to a bit of torture (i.e. your normal use that involves multiple displays and their changing configurations), I’d appreciate it — I’d like to have some real-life testing before I put it into 1.7.6 and make a release.

**Comment by pkarjala** [comment]
Absolutely, I've downloaded it and will put it through the paces today.

**Comment by pkarjala** [comment]
Small bug; for each additional window opened, all currently open windows get a duplicate "Upgrade to Pro" button.  See screenshot:

![screen shot 2015-04-16 at 7 35 04 am](https://cloud.githubusercontent.com/assets/5232936/7187273/1e1b35ca-e40b-11e4-944e-47b5e8eefe92.png)

**Comment by vslavik** [comment]
> duplicate "Upgrade to Pro” button

Took me most of today, but eventually I squashed this one too...

**Comment by pkarjala** [comment]
After two days of testing, no further bugs have cropped up.  I'd sign off of the new build (with the "Upgrade to Pro" button duplication bugfix) as working AOK.
