### ISSUE TITLE
Cannot configure References directories

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#161]
When I right-click on a translation entry, the menu shows the references where the string appears in the source code. When I click on the menu item, a dialog box tells me “Error opening file %s!”.

Where can I configure the paths where the source files are looked for? Having an additional “Configure source lookup” would be a natural addition to this error message dialog.

I looked in the general settings and in the catalog’s properties, but didn’t find anything that looked like it. The closest thing is the “Sources paths” tab in the catalog’s properties, but that seems to be related to generating the .pot file from the source code.

**Comment by vslavik** [comment]
The references are relative filenames — relative to the location of the PO file itself. Instead of adding yet another setting (and a mostly pointless one at that), let’s fix the root of the problem: your PO file. You should fix whatever tool generates it to run from the same directory the PO(T) file is in so that you get correct references.

IMHO this isn’t worth adding a workaround for to Poedit.

**Comment by rillig** [comment]
Thanks for clearing that up. The error message was misleading, since it didn’t tell me that Poedit looked for the reference in several directories. It just told me “Error opening file C:\dialog.c”. From that message I concluded that Poedit tried only that one file, and not all the files from the current directory up to the root directory. Is there a chance that you improve the error message a bit?

    None of these files could be opened:
    C:\Users\rillig\Desktop\dialogs.c
    C:\Users\rillig\dialogs.c
    C:\Users\dialogs.c
    C:\dialogs.c

This error message would have given me a clear clue what to do.

**Comment by vslavik** [comment]
> Is there a chance that you improve the error message a bit?

Your PRs are welcome. 

> This error message would have given me a clear clue what to do.

That said, *this* really doesn’t sound like a great error message: if anything, it’s more intimidating. And the situation where the user finds *this* information useful must be *EXTREMELY* rare and usual (honestly, I can’t even imagine what you did that this would help correct it).

**Comment by rillig** [comment]
Ok, here’s a little background.

I translate for http://translationproject.org/team/de.html. In that project, I usually just download the PO file (as it is linked on that page) and start translating. Therefore I don’t have the source code around.

When I need context, I download the source code separately and unpack it. At that point I know that the PO file and the unpacked source code may be anywhere in the file system, and therefore I thought there had to be a setting to specify where to lookup the source code.

**Comment by vslavik** [comment]
> Ok, here’s a little background.

This confirms that the setup is very uncommon (normally, either POs come with sources or you don’t need sources) and IMHO not worth fretting over.

**Comment by gerdneuman** [comment]
I think this is a very common use case: Translator are not the same as the developers. So it is very typical to only have the po file which you translate and not a proper source system. That is, often the sources are somewhere else then the po file.

FWIW, I have this use case. And many others working with transifex, crowdin, ackuna or glotpress would also have it.

My use case is this: I have a Wordpress theme (of which I am not the developer) and also a few plugins (of which I am not the developer) but I need a German translation for them, like for WooCommerce Subscriptions where I have this problem: https://docs.woocommerce.com/document/subscriptions/faq/#section-32 (the resulting mo file lives in another directory than the original sources, because this makes it upgrade-safe. Most wordpress plugins work like this, e.g. also woocommerce, see https://docs.woocommerce.com/document/woocommerce-localization/#making-your-translation-upgrade-safe

**Comment by vslavik** [comment]
> And many others working with transifex, crowdin, ackuna or glotpress would also have it.

Please don’t assume that because you think something matters that “many” do too — not without actual evidence. The evidence available in this case is that very few care (i.e. those “many” simply don’t exist). Indeed, most Crowdin etc. users won’t have the source code *at all* — which is the case Poedit handles correctly and which is indeed common.

But having the code, putting it in other location *and* wanting to reference it is *rare*, not “common”. If you go through the extra pain of obtaining the source code separately, you can as well put the PO file where it belongs and be done with it.

As always, and as I already wrote above, if you disagree and think this is not as marginal as I do, you are more than welcome to implement a solution an submit a PR. I’ll gladly review it and help you get the code merged.
