### ISSUE TITLE
"Update from POT file" append to the end of file

### ISSUE THREAD

**Issue by suhrab** [vslavik/poedit#173]
When we do "Update from POT file" and save the po file, all new keys are placed in alphabet order.
Is there any solution to append new keys to the end of file? You will ask why we need this. We are using Git and po files are in version control. Every time somebody does push there is a conflict. Tools like kdiff3 cannot do proper conflict resolving for po files, because they are re-build in alphabet order. We tried to play with "Preferences -> Advanced -> Preserve formatting of existing files", it works but saving po file after "Update from POT file" always saves in alphabet order.

**Is there any solution to append new keys to the end of file using "Update from POT file"?**

**Comment by suhrab** [comment]
We tried to google for *git driver po*, but all solutions are for linux. We are on dotnet, windows..
https://gist.github.com/mezis/1605647
http://stackoverflow.com/questions/16214067/wheres-the-3-way-git-merge-driver-for-po-gettext-files
https://www.npmjs.com/package/git-po-merge

**Comment by vslavik** [comment]
(Please only use this issue tracker to file *issues*, i.e.  bugs or PRs; it is not well suited for open-ended *questions* like this.)

> all new keys are placed in alphabet order.

This is simply not true. `xgettext`, and thus Poedit, uses *order of occurrence* and unless you’re using a really old version of Poedit (sadly, you don’t provide basic info like your Poedit version), the order is stable. Meaning that no, updating does not reorder things and no, Poedit in itself isn’t causing git conflicts.

The only explanation for alphabetical order, if you really are seeing it, would be that you use your own custom extractor — but such custom extractors are *your* responsibility.

If you’re seeing a file completely reordered, then it must be because it was initially created by some other tool, in a different order. But that’s a one-time thing: once you commit the first revision saved by Poedit, subsequent changes *will* be reasonable.

> Every time somebody does push there is a conflict. Tools like kdiff3 cannot do proper conflict resolving for po files,

There is *nothing* inherently problematic w.r.t. git in PO files. The only annoying thing are location references that change a lot, and this has nothing to do with Poedit or order of entries in the file, and is not something Poedit could fix. Fortunately, it’s fixed easily enough: either use `--no-location` or adopt a better workflow that doesn’t involve updating POTs and POs all the time, but only before releases, or only on one branch.

> Is there any solution to append new keys to the end of file using "Update from POT file”?

No. But again, you are misinterpreting things: Poedit does *not* rearrange entries in alphabetical or any other order. You’re probably just seeing location references noise.

**Comment by suhrab** [comment]
You are right. After "Update from POT file" new keys are placed in POT file order. Sorry about this.
>The only explanation for alphabetical order, if you really are seeing it, would be that you use your own custom extractor — but such custom extractors are your responsibility.

We are using https://github.com/rubenv/angular-gettext . It has tool to extract keys from sources. Yes this tool creates pot file in alphabetical order.
