### ISSUE TITLE
Poedit under Linux/GTK: Close also quits program

### ISSUE THREAD

**Issue by c72578** [vslavik/poedit#180]
In Poedit under Linux there are these two entries in the file menu:
Close Ctrl+W
Quit Ctrl+Q

How to reproduce:
- Open a po file
- Click on "Close Ctrl+W" in the file menu or type "Ctrl+W"

Observation:
Both entries are doing the same, they quit the application.

Expected behavior for "Close": Close the file but do not quit the application

Poedit version tested: 1.8.1
OS: Fedora Linux, kernel 3.19.7-200.fc21.i686

**Comment by vslavik** [comment]
Are you talking about a situation when you have 2+ windows open, or just one?

**Comment by c72578** [comment]
One Poedit window is open

**Comment by vslavik** [comment]
Then I’m not sure what’s your complain? GNOME/GTK+/X11/Linux isn’t OS X and doesn’t have the concept of window-less running GUI app, does it? Closing the last open window *should* terminate the app’s process as far as I know.

**Comment by c72578** [comment]
No.
"File - Close" is expected to close the file, leave the program open and not quit the program.
The expected status should be the same as when you start Poedit, without having opened a file yet.

**Comment by vslavik** [comment]
Can you please provide an example of a native GNOME applications behaving in this way and that uses multiple windows and *not* tabs (i.e. gedit is out) and/or a reference to GNOME HIG that says so?

But I’m skeptical, because I can give you counter-examples for both: GNOME3’s file browser has *Close Window* (Ctrl+W) and *Close All Windows* (Ctrl+Q). Closing all open windows with Ctrl+W is indistinguishable from Ctrl+Q. And GNOME HIG clearly [states the following on the subject](https://developer.gnome.org/hig/stable/primary-windows.html.en#general-guidelines):

> - Your application should cease to run when all its primary windows have been closed.
> - Quit should close all primary windows.

As far as I can tell, Poedit does conform to GNOME HIG and this behavior shouldn’t be changed.

**Comment by c72578** [comment]
When closing the last open file in Poedit, the "Welcome to Poedit" screen could be shown again. Like at the beginning, when Poedit is started. Close from there would finally close the program.

Remark: All the GNOME applications I had a look at in the meantime (editors etc.) use tabs - so different situation there.

**Comment by vslavik** [comment]
> "Welcome to Poedit" screen could be shown again

It certainly could, but I don't think it *should*. It would be highly unexpected for Ctrl+W to *not* close the window, and going back to the welcome screen would require exactly that. That's something that would be OK in tabbed UI, but not in "normal" one.

Why do you want this anyway?

**Comment by c72578** [comment]
OK - GNOME HIG counts.
Sorry for the noise.

**Comment by XOlegator** [comment]
Sorry, I pick up a closed topic discussion, but I totally agree with topicstarter (c72578). Ctrl+W should close document, but not the program. https://developer.gnome.org/hig/stable/keyboard-input.html.en#application-shortcuts - it says Ctrl+W "Closes the current content item". The same behavior, for example, in Incskape. It intuitive understandable behavior to close app by Ctrl+Q and close current doc by Ctrl+W. This makes me frequent inconvenience in the work of the Poedit.

**Comment by vslavik** [comment]
> It intuitive understandable behavior to close app by Ctrl+Q and close current doc by Ctrl+W.

You’re not making any sense: *that’s what Poedit already does*. This section on Ctrl+W is perfectly consistent with the behavior mandated by HIG that I quoted above *and that Poedit already implements*.  Note in particular that it doesn’t same “replace the closed content item with arbitrary other UI”. 

> This makes me frequent inconvenience in the work of the Poedit.

Yeah, right. *How?*

I have no intention of changing this behavior, because it conforms to the HIG and anything else would *violate* it, but I’m open to (comprehensible and reasoned!) arguments to the contrary.
