### ISSUE TITLE
Updating .pot from sources proposes to remove every translation

### ISSUE THREAD

**Issue by Adriatic1** [vslavik/poedit#181]
Using latest v1.8.1, I started the process to update .pot from sources.
Program marks all 1600 lines as obsolete, no new lines were added :(
Reinstalled ancient version 1.5,4, works perfectly with the same file.

Some info that may help:
- using Windows 7 32-bit PC
- within the source root, pot. and .po files are stored in "po" sub-directory
- within the source root, .cpp to be parsed are stored in "src" sub-directory
- portion of the .pot file (mostly related to the path setting):
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-SourceCharset: iso-8859-2\n"
"X-Poedit-Basepath: ..\\src\\\n"
"X-Generator: Poedit 1.5.7\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPath-1: ..\\lib\\gtkspell\n"

**Comment by vslavik** [comment]
> portion of the .pot file

Sorry, but “portion” of something is not exactly useful — as a developer, presumably, you should understand that there’s nothing I can do unless you provide something *reproducible*. In this case, that would be the PO(T) file *and* complete source tree as well as the relevant extractor settings.

**Comment by Adriatic1** [comment]
OK, here is the sample tree that shows the error on my PC:
http://notecase.sourceforge.net/temp/test.zip

Steps:
1. unpack, open .pot file from "po" subdir
2. run "update from sources", I get the "There are no translations. That's unusual." screen
3. with old version, out of the initial 1635 strings, merging gives: 0 new, 1634 obsolete
which is correct, because 1 sample item from the sample .cpp file survived the operation

**Comment by vslavik** [comment]
It is as I suspected: Poedit is doing exactly what you told it to do, there’s no bug here. You have no additional keywords set in the properties and so Poedit dutifully extracts only strings using the default keywords (as documented at http://poedit.net/trac/wiki/Doc/Keywords, linked to from the properties). The only keyword you use is the *non-default* `_()` one, which you instructed Poedit not to extract. You probably made some customizations to 1.5 to always include it and forgot about it (or the old versions used to include it and *I* forgot about that — in either case, the config should be transferred to 1.8 unless you did a clean install).

The fix is simple: just explicitly add `_` to the kw list.

BTW, you should also fix the invalid, Windows-centric paths (see https://github.com/vslavik/poedit/wiki/PO-Extensions) in there. Best way to do that is to remove them all and just drag & drop the folders to be scanned (in Poedit 1.8).

**Comment by Adriatic1** [comment]
Sorry, but I never edited any of such settings in the old poEdit and it just works.
Also, does poEdit remove settings on uninstall? To prepare this bug data, I reinstalled poEdit at least few times (switching between two versions), and it correctly forgot my email settings for example.
That proves that your hypothesis about an explanation is invalid.

Old version just works and I'll stick with it. I just filed the bug hoping to help you improve the software to work out of the box. 
IMO correct solution here is to add this keyword as default in the next release (as I suppose was already the default in the old version).

**Comment by vslavik** [comment]
> Sorry, but I never edited

I envy your memory, I wish I could remember every insignificant detail for years as well you do...

> Old version just works and I'll stick with it.

Sigh. Why do you waste my time filling a bug, then, if you are determined to ignore the answer? Don’t ask for help if you’re too stubborn to listen to the answer.

> I just filed the bug hoping to help you improve the software to work out of the box.

It, of course, *does* work out of the box, and consistently with the rest of the gettext ecosystem (i.e., particularly the gettext-runtime behavior). The problem lies entirely in you not reading the documentation for the gettext runtime *library* you use, where it’s explained that `_()` is not a symbol recognized by default (in code or gettext tools, the latter is also explained in the documented I linked to above).

Poedit respects and will continue to respect the defaults put forward by the GNU gettext team.

I explained the issue, explained how you can *trivially* fix it with one tiny addition. I’m sorry, but refusing to listen and fix your PO file and sticking to a *three years* old, buggy-as-hell version of Poedit is more than a bit irrational.

**Comment by Adriatic1** [comment]
I'm not saying you must add anything, but just to make you aware what GTK programming standard says here (in the section 1.7): https://developer.gnome.org/gtk3/stable/gtk-question-index.html

Quote: 
"Conventionally, people define macros as follows for convenience:
#define  _(x)     gettext (x)"

This has been used for decades, some of my code was even generated by Glade tool that uses that.
So I stay by my opinion that supporting GTK standards out of the box would be nice to have.
I have no wish to discuss what's irrational, thank you.

**Comment by vslavik** [comment]
> Quote: 
> "Conventionally, people define macros as follows for convenience:
> #define _(x) gettext (x)”

Sigh. That’s exactly what I said. `_` IS NOT THE DEFAULT. It says so right there: **PEOPLE DEFINE** it *themselves*.

Of course `_` is common and convenient. That’s why people define it in their headers *and* in their POT file and are done with it (well, some; some prefer to argue endlessly about things established decades ago).

There are good reasons why gettext-runtime doesn’t define `_` by default: conflicts with other uses. That’s the same reason `xgettext` doesn’t make `-k_` a default and you have to opt-in (again, *both* in code and tools). Contrary to what you probably think, the gettext developers know better than you or, for that matter, me. There’s too much of risk of conflicting with *other* uses of `_` and yes, that’s a real, real-life thing, even in C and even more so in other languages supported by Poedit and `xgettext`.
