### ISSUE TITLE
"Relative paths" in "Source paths" under "Catalogue properties" gone with 1.8.2 ?

### ISSUE THREAD

**Issue by DrLightman** [vslavik/poedit#191]
I've not been using Poedit for some weeks. This morning went to translate a wordpress theme, opened Poedit and it asked me to update, and I did, to 1.8.2

Opened a .po , went to set up paths to source files because I made some changes to the theme and needed to update the catalogue, but I couldn't find the buttons to add "." and ".." I was used to.

Here is a pic:

![poedit](https://cloud.githubusercontent.com/assets/4699807/8427533/6b85272e-1f18-11e5-89e3-6e98bb2abd0a.jpg)

With the "+" button a window popup appeared but it lets me browse for a folderan absolute path, but it doesn't even work because it doesn't save the "drive:", only the absolute path, eg sites\mysite\ instead of g:\sites\mysite\

I'm using Windows Vista 32bit

**Comment by vslavik** [comment]
> doesn't even work because it doesn't save the "drive:", only the absolute path

No, it adds *relative path from the location of the PO file*, i.e. does automatically the only correct thing, something you had to do manually before (and more likely than not, screw it up).

If you believe there's a bug, kindly provide detailed instructions on how to reproduce it and explain why Poedit is wrong. "I add some path and it is wrong" really isn't enough, please see http://www.chiark.greenend.org.uk/~sgtatham/bugs.html if you don't have experience filing bugs.

**Comment by DrLightman** [comment]
A popup came out with a white cross on redd background telling me poedit coulnd't find any source file at the specific location.

To be more precise, I opened a default.po and it already had a path saved, but it was of the kind:

../../../../../../../../../wamp/some/foo/bar/

That made no sense in my configuration. I deleted it and browsed for the parent folder relative to default.po and I recevied the error.

I ave up on the task for another reason so next time I will face this "bug" I'll let you know with more details.

Thank you.

**Comment by vslavik** [comment]
Again, whenever you create a bug (not just for Poedit, anywhere), please include reproducible description. 

As it is, I still have absolutely no idea what is wrong (or you think is wrong). Your latest comment is unclear and not even close to being something reproducible and doesn't seem to have any relation to the original issue. What little detail it contains is clearly inaccurate (you couldn't have possibly received that error immediately after browsing for an error) and is most likely explained by you choosing a folder that did not in fact contain any source code.

Poedit 1.8 creates the relative paths automatically, just add the sources folder. That doesn't mean there isn't some bug in there, but so far, there's *nothing* in the above comments that would indicate that, mostly because you refuse to describe your situation in any meaningful detail 😢

**Comment by DrLightman** [comment]
The last comment was just a comment/information, I didn't expect a solution, don't worry. I'm no longer in need to translate the theme and I don't have time to investigate further.

It's just that in the past I was used to type ".." and I was done, while now I can't type anything, but only browse stuff. If this is intended behaviour, it's okay, if the button was hidden or missing dued to my configuration, in that scenario it was a bug, but you made it clear that since 1.8 there is no more typing paths, it's okay to me then.
