### ISSUE TITLE
Mac Base Path and Paths for Creating POT file

### ISSUE THREAD

**Issue by okahara** [vslavik/poedit#196]
What I have found online so far is that the Base Path should be "." and the paths to my source code should be an absolute path.  But when I add a folder or a file to my paths it automatically changes my base path.  Doing so causes me to get an error saying the files do not exist.

![screen shot 2015-08-12 at 1 56 41 pm](https://cloud.githubusercontent.com/assets/10368199/9236486/0a0c929e-40fa-11e5-8f7a-57f285fd7cc0.png)

This image shows the structure of my files.  I am currently working on "testPOT.po" to make the POT file and am testing it on the master.html file in the same folder.
On the right shows the Base path as "." and the paths as "master.html" but when I click OK I get this popup:

![screen shot 2015-08-12 at 1 55 59 pm](https://cloud.githubusercontent.com/assets/10368199/9236545/56dd6b70-40fa-11e5-8c30-34afa9ea03d0.png)

What am I doing wrong?  Thank you for your help

**Comment by vslavik** [comment]
> What I have found online so far is that the Base Path should be "." and the paths to my source code should be an absolute path

I don't know where you read this nonsense, but it's actually the **exact opposite** of what you should do in Poedit 1.7 and older. [See the documentation.](https://github.com/vslavik/poedit/wiki/PO-Extensions) In 1.8+, just drag/add the folders you need and don't worry your head about it. It will do the right thing.

Your assumption that this is somehow related to the error you get is jumping to unwarranted conclusions. No, Poedit tells you that no source code is available *because you didn't provide it with any source code*. 
You added one HTML *markup* file, not source code in any language gettext can be used with. If you are misguided enough to use the `.html` extension for e.g. PHP files, you need to configure the extractors accordingly (or better yet, stop doing it). 

BTW, there's really no reason to add individual *files* there, instead of the entire sources folder.

P.S. Please use this tracker only for *issues*, i.e. bugs or PRs, not for questions or general confusion — that's what http://poedit.net/support is for (and it explicitly told you so).
