### ISSUE TITLE
On latest version 1.8.4 (Windows) there appears to be no way to edit Base Path

### ISSUE THREAD

**Issue by galbraith** [vslavik/poedit#197]
In version 1.6.11 I was able to edit the Base Path in the Catalog Properties Dialog.  Since version 1.77 the field is read-only, whether I am creating a new PO file or editing an existing one. Checked with some other developers and they have the same issue.  My fix was to go back to version 1.6.11 for now but not sure if there is a setting or something else I am missing to make the Base Path editable in the current version. 

Any suggestions?

Thanks,
Pete

**Comment by vslavik** [comment]
> Since version 1.77

No, since 1.8, as documented in `NEWS`, a file I highly recommend reading, because it lists intentional changes like this one.

> Any suggestions?

Yes: don't edit the base path.

Why would you even *care?* Just add the extraction paths you need added and don't worry yourself with internal messy little details like the base path. You don't need them.

**Comment by galbraith** [comment]
Thanks.
