### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by LikeBtn** [vslavik/poedit#216]
Windows 8.1 (64bit)
Poedit 1.8.5

1) Download an archive from https://mega.nz/#!B0NEQbCJ!V1-00on4pUj7tAvDOmVQqPYn2uR__glVNflgrD5prY8, open /translations/ru.po in Poeditor. You will see:
![poedit1](https://cloud.githubusercontent.com/assets/8167133/10268686/2a094288-6ac9-11e5-9028-ab2d4c22d6d6.png)

2) Click "Update" button. "Source text" and "Translations" sections disappear and you are unable to edit .po file anymore:
![a91c1942-6939-11e5-9c5b-0ce921a6a380](https://cloud.githubusercontent.com/assets/8167133/10268694/5e64ac70-6ac9-11e5-853f-0fc665801072.png)

**Comment by vslavik** [comment]
(Please don't post duplicates like this. You should have commented on #214 instead. In fact, please don't file GitHub issues unless you are 100% *sure* it's a bug — see http://poedit.net/support for more appropriate channels otherwise.)

Your source code does not have any files that Poedit would recognize by default, not with any translations — hence, correctly, empty translations set. If you choose to use non-standard file extensions like `.inc` or `.module`, you have to actually configure the PHP extractor to recognize them. Go to Preferences➞Extractors and add these custom extensions to the PHP extractor. Better yet, use normal extensions instead.
