### ISSUE TITLE
CJK issue: freeze translation field when I try to change input language and type

### ISSUE THREAD

**Issue by darkcircle** [vslavik/poedit#222]
I'm using this app from both Mac OS X and Linux, and I did upgrade to current latest release version.

recently, I found an issue that app usually freeze when I try to input full-width east-asian characters after I change typing language by Iuput Manager.

It should be fixed, because this issue usually breaks typing rhythm, so translation working tempo goes slower.

**Comment by vslavik** [comment]
> I'm using this app from both Mac OS X and Linux, and I did upgrade to current latest release version.

Please do actually state the version number you’re using, for both platforms — for one thing, you may believe that you are using the latest version, but you may not, for another, the definition of “latest” changes in time. Please also state the OS X version and a more specific description of your Linux-based system than an extremely vague “Linux”.

> recently, I found an issue that app usually freeze when I try to input full-width east-asian characters after I change typing language by Iuput Manager.

I’m sorry, but this is totally unclear. Please have a look at [this document](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and describe whatever the problem is exactly and precisely and in detail (you seem to be a developer yourself, you should know this!). Don’t assume I am sitting next to you looking at your computer and can see what you can, as you do, or that I know your language (or know what your language *is*), or that I know how your input method / keyboard works or for that matter what your IM *is* — because the truth is, I have absolutely no idea about any of that (how could I?). FWIW, I also find it hard to believe that something as low-level as input would behave 100% identically wrongly on two very different platforms, but well, I may be wrong, because I literally have no idea what you’re talking about.

**Comment by darkcircle** [comment]
Thank you for giving detailed guide.
My two system environment is as below.

<Mac OS X>
1. I'm using poedit 1.8.6
2. My language is Korean
3. OS X 10.11.1

<Linux>
1. also using poedit 1.8.6, and Korean
2. IM: nabi-0.99.11 running on X11(-based desktop manager, not the same as GNOME, KDE).
3. Input Manager depens on libhangul-0.1.0, libICE-1.0.9, libSM-1.2.2, libX11-1.6.3, pango-1.36.8, glib-2.44.1, gtk+ version 2.4 or later, and gdk-pixbuf-2.32.1.

phenomenon :
sometimes, I need to change between English and my mother language. I can't see some appear after Find/Replace and insert/delete/modify and looks like freezing. It's just changed after I hit "Esc" key.
If I bring mouse pointer onto translation input field before hitting "Esc" Key, mouse pointer is disappeared on there.

reproduction:
Mac OS X: sometimes
Linux: Always.

**Comment by vslavik** [comment]
> Thank you for giving detailed guide. 

Can you please follow it, then? Instead of ignoring most of it, not reading the article I asked you to read, and following with another semi-description too vague to be reproducible or even *understandable* to people not using computers with Korean? Once again, please actually provide the information I asked for — that is, *detailed reproducible description*. It’s OK that you don’t know what it takes, but *that’s why I linked to an article explaining it.*

I would love to fix the bug (assuming there is one), but I have to know what it *is* first. So far, *literally* the only usable information I have is that you think something is wrong with (some form of) Korean input, somehow, when doing something, somewhere. How am I supposed to work with that?

**Comment by darkcircle** [comment]
Sorry for inconvenience by giving a lack of much information.

Reproduction step what I did:
1. open any po file editable.
2. click any message item about to edit for translation
3. focus on edit field and write something string English and Korean with switching each other language.
4. and this time Ctrl+F to open find dialog
5. input any keyword(English also ok) to find from entire po file.
6. focus edit field again to input English/Korean w/ space key and backspace key.

* in this time, small green block is trailing on the line of translation field and It is freezing.
* mouse cursor is disappeared when I try to click on there.

If here seem to be a lack of information, please let me know.

**Comment by vslavik** [comment]
> Sorry for inconvenience 

This is not about “inconvenience” (although it’s true that explaining things to you over and over is wasteful), this is about *being unable to fix this* because you just won’t provide a usable description and I still have absolutely no idea what “this” even *is*.

> focus on edit field and write something string English and Korean with switching each other language

So this is the first time you mention *mixed-language strings* — kind of relevant and important. And yet you still, despite being repeatedly asked to, didn’t provide *specific* instruction on what *specifically* to type and perhaps even more important, *how*. Surely the idea that *not everybody in the world is Korean* can’t be so hard to comprehend?

>  and this time Ctrl+F to open find dialog

To further illustrate how poor your original description was, you didn’t even mention Find at first. I suspect  you are *still* withholding important information, in part because nobody else, except you, complained about anything like this (and it’s not because Poedit isn’t used in Korea or Asia more generally: it is, a *lot*). I would greatly appreciate it if you could finally stop trickling little tidbits like this and wrote down the detailed, accurate and specific reproduction steps I requested.

> focus edit field again to input English/Korean w/ space key and backspace key.
>
> * in this time, small green block is trailing on the end of line of translation field and It is freezing.
> * mouse cursor is disappeared when I try to click on there.

I’m sorry, but I’m just flabbergasted by this. It makes no sense to me. I don’t know what green blocks or what not you’re talking about (again: as I previously explained, shocking as it seems, I am *not* familiar with Korean keyboards/IMs). I don’t know what does mouse has to do with anything. What I do know that is that you simply *can’t* focus input control with space *or* backspace, so that part sounds crazy to me and I wonder what else is similarly wildly inaccurate.

Above all, it’s not at all clear from what you wrote *why do you even think there’s anything wrong* with what you (loosely) describe. Again: not familiar with Korean IMs. You need to describe the behavior in detail (the above is very far from detailed) and *explain what is wrong with it*. That includes comparison with other apps etc. — for all I know, you are complaining about standard behavior of all apps.

> please let me know

I did, above, twice already… You need to describe *EVERYTHING*, every little detail, no matter how insignificant you think it is.

**Comment by vslavik** [comment]
Giving up on this ticket for now.
