### ISSUE TITLE
Proxy configuration setting support

### ISSUE THREAD

**Issue by igorlino** [vslavik/poedit#223]
From time to time when moving to strange very badly configured networks with custom proxy settings The suggestions don't work any longer as there is no network, but the root cause is that Poedit is not able to detect the settings. (Win7)

If it be possible to have in the preferences menu a way/section to setup explictly proxy information then it would be solid rock under rough circumstances.

**Comment by igorlino** [comment]
error messsage is
WinHttpSendRequest:12002: Time limit has been exceeded

**Comment by vslavik** [comment]
>  but the root cause is that Poedit is not able to detect the settings.

Nope, the root cause is that you don’t have your Windows system configured properly with proxy settings. Poedit uses WinHTTP (i.e. shares proxy settings with all .NET apps too and your misconfiguration has wider consequences), which is configured separately from MSIE. See http://superuser.com/questions/489527/how-can-i-configure-proxy-settings-for-all-apps-system-ie-etc for how to fix it.

> If it be possible to have in the preferences

I don’t think there’s any reason to duplicate OS-wide settings in Poedit (and every single other application…). But I should add a note about it to a FAQ and I will once I get around to updating the website.

**Comment by igorlino** [comment]
yes, tricky tricky tricky. I'm not .NET developer only web developer so I only used either, like WebStorm preferences, or the Config Panel of windows, that works for Chrome for example.

Thanks for the info.

Seems like for non-IT people this WinHTTP-awareness is totally overkill.

**Comment by igorlino** [comment]
and thanks for the fast feedback (in this and the other issue I raised) :+1:

**Comment by vslavik** [comment]
> Seems like for non-IT people this WinHTTP-awareness is totally overkill.

There’s no “WinHTTP-awareness” nor any relation to you being a .NET developer or not. WinHTTP is simply the HTTP library used. I mentioned .NET merely because the same proxy setting affects it and if Poedit is broken on your computer, *so are any apps using .NET* and the breakage is much more serious than only Poedit.
