### ISSUE TITLE
Support context in translations with _x function

### ISSUE THREAD

**Issue by benoitchantre** [vslavik/poedit#225]
It appears that terms using a context with `_x` aren't supported by Poedit, for example:
`_x( 'Comment', 'column name', 'my-text-domain' )`

I have added `_x`as keyword, but the terms that use this function stay in english.

Have I missed something?

**Comment by vslavik** [comment]
Keywords with context are, of course, fully supported. You just didn’t configure it correctly. See the documentation, which is linked to from the very window where you added the keyword and where the syntax for contexts is explained. Or use the WordPress wizard which sets it up correctly for you.

Unfortunately I can’t know what exactly you did incorrectly, because you decided not to share the file(s) or a reasonably  detailed description of you did (see http://www.chiark.greenend.org.uk/~sgtatham/bugs.html for some hints), but contexts are very much fully supported and specs like `_x:1,2c` are handled correctly by both Poedit and xgettext.

P.S. Probably better to use help@poedit.net for questions, and leave the issues tracker for development issues...

**Comment by benoitchantre** [comment]
@vslavik Thanks for your answer, I have probably done something wrong.
