### ISSUE TITLE
Package names for compiling on Ubuntu?

### ISSUE THREAD

**Issue by edent** [vslavik/poedit#227]
Is there a definitive list of packages a user needs to install in order to compile the latest version?

This is what I have so far

`apt-get install libwxgtk3.0-dev wx-common  libicu-dev libstkspell-dev lucene++ boost-defaults`

I'm still getting `configure: error: missing Lucene++ library` when running `./configure`

Can someone let me know what magic I need to invoke to get the latest version installed?

**Comment by vslavik** [comment]
See the `README` file. See Ubuntu’s own documentation for how to install its own packages. 

P.S. Please only use this issue tracker for reporting *issues*, not for asking questions, as asked to at http://poedit.net/support

**Comment by vslavik** [comment]
Since the hint that you need to RTFM wasn’t taken, let me elaborate:

1. If you’re not familiar with compiling from sources, you absolutely *must* read Ubuntu’s very own documentation on this very topic first: https://help.ubuntu.com/community/CompilingSoftware
2. Observe how it has a section helpfully titled “Troubleshooting the configure” which tells you how to troubleshoot things like this. In fact, its very first point is *that you need development packages* for, well, development. Which you clearly don’t have, as `config.log` probably confirms (and `configure` says you need to read).

**Comment by edent** [comment]
I am very familiar with compiling from source.  I do it often.  I'm sorry that I'm not familiar enough with Lucene to know exactly which dev package I should be installing.

Most maintainers are happy to say "you'll need to apt-get the following packages..."  

Looking at the number of people asking you for help - it seems that there are three options.

1. You could provide pre-built binaries for multiple platforms.  I appreciate that's probably a bit of a pain to manage.
2. You could write a quick guide to how to compile on popular platforms - and perhaps some of the common bugs which people encounter.
3. You could be rude to each and every person who asks a question.  Thereby reducing the chance that they'll use your software and contribute back to it.

It's fairly obvious which path you've chosen.

In the meantime, I'm following this guide - https://twistedlinux.wordpress.com/2015/10/23/install-poedit-1-8-6-from-source-on-xubuntu-14-04/ - if it works, I'll be sure to submit a pull request to help you improve your documentation.

Please enjoy the rest of your weekend.

**Comment by vslavik** [comment]
> I am very familiar with compiling from source. I do it often.

I’m confused. How do you not know you need `-dev` packages, then, or check `config.log` for specifics of the failure? You can’t blame me for assuming you don’t know autotools well when the only information you provide points that way.

> I'm sorry that I'm not familiar enough with Lucene to know exactly which dev package I should be installing.

There’s exactly **one** of them…
(The dependency listed in the README and configure is Lucene++, not Lucene, BTW, but I assume that’s a typo above.)

> Most maintainers are happy to say "you'll need to apt-get the following packages..."

I don’t use your distro (or even know what *version* of it you use, which is kinda relevant here), I can’t possibly know. Do you know how *many* different Linux distros are out there? Do you seriously expect me to know what every single obscure distro uses? That’s ridiculous.

That’s why I list the actual dependencies in the README, figuring that it’s trivial to match to packages to people compiling from sources.

> You could provide pre-built binaries for multiple platforms.

Traditionally, that’s what Linux distributions do — *and they do provide them*. That’s what they are *for*. Source code is for people who know their way around Autoconf and Linux.

> You could write a quick guide to how to compile on popular platforms 

Or you could read the available guides. There’s Poedit’s README. There’s documentation on using configure. There’s Ubuntu’s handbook that explains to you the Ubuntu specific bits.

Sorry, but the lack of documentation absolutely isn’t the problem here. It’s all there, you just didn’t read it. Don’t blame *me* for that!

 > You could be rude.

A bit unfair coming from a person who wouldn’t be polite enough to follow the instructions at http://poedit.net/support…

**Comment by skftn** [comment]
@vslavik is your typical turbo-nerd who tells people they need to _rtfm_ and _not built software from sources if they do not understand it_ - in other words: your typical C++ programmer who suffers from a god complex.

Just dont bother; edit your language files in vim people :hankey:
