### ISSUE TITLE
Improve merging defaults for fuzzy entries and fuzzy status UI

### ISSUE THREAD

**Issue by lanurmi** [vslavik/poedit#236]
Updating an existing translation from a POT in Poedit 1.8.6 does not generate any fuzzy entries in the PO. The translator may need to re-translate hundreds of entries that have barely changed.

Steps to reproduce:
1. Get http://translationproject.org/PO-files/fi/coreutils-5.2.1.fi.po
2. Get http://translationproject.org/POT-files/coreutils-8.24-pre1.pot
3. Update the PO from POT.

Actual results:
466 translated, 0 fuzzy, 1254 untranslated.

Expected results:
Similar statistics that `msgmerge -U` on command line leads to:
466 translated messages, 674 fuzzy translations, 580 untranslated messages.

**Comment by vslavik** [comment]
Poedit does produce fuzzy entries on merge unless you explicitly ask it not to by disabling *Consult TM when updating from sources* in Preferences→TM — as you apparently did.

**Comment by lanurmi** [comment]
Okay, that seems to be the setting that affects this. However, I have not disabled it myself, it is off by default.

Just to check, I did a fresh install of Poedit on a Windows system that has never had Poedit installed before -- and the *Consult TM* setting is disabled after a fresh install.

**Comment by vslavik** [comment]
> However, I have not disabled it myself, it is off by default.

Ah, indeed, I forgot about that change — sorry about the disinformation! :-(

FWIW, future versions of Poedit will have this as a tri-state setting (off, consult-tm and a new one, consulting only previous version of the file, with the new one being the default) and I think this contributed to my confusion about the default. Sorry again :(

**Comment by lanurmi** [comment]
The current default is nasty especially for those not familiar with how gettext works — they don't know to expect automatic fuzzies upon merging, so they don't suspect anything is wrong. They just curse the amount of work they need to re-do. This has actually happened to someone, which is why I reported this issue.

**Comment by vslavik** [comment]
> The current default is nasty especially for those not familiar with how gettext works

Funny story: this was actually changed *because of* users not familiar with gettext. I was getting a lot of complains about msgmerge prefilling of translations (back then, this wasn't configurable at all and was always done). Translators, even professional ones, would assume, upon receiving a PO file to work on, that fuzzy entries are already translated and would ignore them or worse, un-fuzzy without review.

I get *much* fewer (= you and one other person so far, in >year) complains about the new behavior. That doesn't mean it's perfect and I'm leaning towards a different one (see above), together with making it more clear in the UI that the fuzzy entries are for review. But it's not as clear-cut as you think.

It's also worth pointing out that it is certainly not the case that this causes *any* pointless re-doing of work — that's simply not true under normal circumstances. This *only* affects strings that changed *a little bit* between updates of the PO file, i.e. relatively small part of the file. It doesn't affect unchanged source strings (the only situation when "re-doing" would be a 100% accurate term to use), it doesn't affect large differences in source strings (no msgmerge match). Normally, source strings are almost always fixed and change rarely. If you say this causes "[large] amount of work they need to re-do", that indicates some highly unusual workflow to me.

**Comment by lanurmi** [comment]
Admittedly I have also encountered (even professional) translators who are confused about whether "the yellow lines" require some work or not, and they usually assume "no". However, unless starting a translation from scratch, fuzzy entries may well exist in the file a translator is given, which was merged with `msgmerge`. Therefore not generating fuzzies by default in Poedit only solves half of the problem; their meaning should still somehow be communicated to the user. I wonder if e.g. SDL Trados has something analogous to fuzzies and how does it present them.

The scenario where sometimes a lot of source strings could change by a little bit doesn't require a particularly unusual workflow; it could be a result of performing a grammar/spelling/terminology check on all the msgids. Or changing all `%d`s to `%ld`s.

**Comment by vslavik** [comment]
> Therefore not generating fuzzies by default in Poedit only solves half of the problem; their meaning should still somehow be communicated to the user.

Yes, I remarked on that above. 

My current thinking is that there should be a "needs review" textual badge (in color matching the highlighting color) next to the translation entry field, where it should be more noticeable than the fuzzy button in toolbar, and more explanatory. Alternatively, having such label on each list item, but I think it would be too busy and cluttered. Of course, if you have other suggestions, I'd be glad to hear them.

> Or changing all %ds to %lds.

Fair enough…

(I'm reopening this with a changed subject because this issue accumulated enough useful reference for handling the issue underlying your original report: unobvious default and confusion about fuzzy meaning.)

**Comment by lanurmi** [comment]
I don't have the perfect solution in mind, but something I was thinking about:
* Show fuzzy rows colored yellow in the list view (as it is now), but do not show the fuzzy translation in the list — perhaps easier to grasp that those rows are somehow incomplete, not just funny-coloured.
* At each row, show the fuzzy translation in the editable text field down below, but somehow very visibly label it as e.g. "Computer-generated incomplete suggestion" until the user edits the field.

**Comment by lanurmi** [comment]
Additional remark: In some free/open source projects the developers just love modifying dozens and dozens of  translatable strings by adding a full stop (.) to the end, or removing it. Maybe back and forth even. Removing and adding `\n`s in the strings is popular too. This is another argument for generating fuzzies by default.

**Comment by vslavik** [comment]
> Additional remark: In some free/open source projects the developers just love modifying dozens and dozens of translatable strings by adding a full stop (.) to the end, or removing it. Maybe back and forth even. Removing and adding \ns in the strings is popular too. This is another argument for generating fuzzies by default.

*And* to use `--previous` by default, to preserve the previous version, which Poedit now does (71018ad7e5c7c8b9346befad1c217a34e089580a).

**Comment by vslavik** [comment]
There are some more UI improvements to further clarify the “needs review” state coming soon, but I think the majority of this issue is covered, so closing now.

This is how the respective setting looks now (with the highlighted one, i.e. default `msgmerge` behavior, being the default):

<img width="423" alt="screen shot 2016-11-07 at 14 53 04" src="https://cloud.githubusercontent.com/assets/145881/20068805/5aafd582-a51a-11e6-954f-fc24d9ca2802.png">
