### ISSUE TITLE
Missing configure script

### ISSUE THREAD

**Issue by Vdragon** [vslavik/poedit#238]
According to the installation section of the [README](https://github.com/vslavik/poedit/blob/master/README):

```
 Unix
------
Do the usual thing:

    ./configure
    make
    make install
```

There should be a configure script in the root directory of the source, but no such file is found.

BTW, the attempt to generate the configure script using `autoconf` was failed with:

```
configure.ac:7: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:15: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:16: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:108: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:110: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:225: error: possibly undefined macro: AC_DEFINE_UNQUOTED
```

**Comment by Arthur2e5** [comment]
Try autoreconf instead. 
The build script at https://github.com/AOSC-Dev/aosc-os-abbs/tree/staging/extra-i18n/poedit shows nothing special so…

**Comment by vslavik** [comment]
It is not at all true that the [source tarball](https://github.com/vslavik/poedit/releases/download/v1.8.7-oss/poedit-1.8.7.tar.gz) from http://poedit.net/download doesn't contain `configure` — it very much does, as it should.

So the entire issue is that you are either (a) confused about the difference between downloads and git repository, or (b) decided to — instead of going to download the latest release from the obvious place, http://poedit.net — go hunting for downloads to GitHub and got confused by their [idiotic "Source code" buttons](https://news.ycombinator.com/item?id=11087857).

In case of (a), please finish reading the README, in case of (b), please complain to GitHub (and perhaps look at upstream's site for releases in the future).

**Comment by Vdragon** [comment]
Thanks for pointing out, I've acquired the release by `git clone "https://github.com/vslavik/poedit.git" Poedit` and checkout the release tag v1.8.7-oss .

The reason to clone the entire repository instead of just grabbing the released source tarball is that I somehow suspect that issue #237 is not a bug in Poedit, but a bug in the input method [HIME](http://github.com/hime-ime/hime), which turns out to be just a wrong decision at all.

**Comment by Vdragon** [comment]
Moving my comment on the PR to avoid discussion separation:

```
Thanks for pointing out, I've stopped reading the README further once I found the "Installing from sources/Unix" section.

I would suggest to somehow improve the README by specifying those subsections only applies to released source tarballs, though.
```
