### ISSUE TITLE
Add sorting by reference

### ISSUE THREAD

**Issue by sirdanielk** [vslavik/poedit#240]
I think it would be good idea to add sorting by "reference" which would mean sort by what source file translation belong to, or more generally by source folder. 

Ideally, i would love to see another view eg. on the right, with all source files that have translatable strings. By choosing one source file, i would see then filtered list of strings, only from one file. Or just intended strings put on the top. 

For translator its much easier and more precise to choose what strings to translate first. Which one are more important, which strings might be translated later; based on source file. Helpful in very big projects.

Egzample of new view with references:
src/buttons/source.*
src/input/source.*
src/main-gui/source.*
src/output/source.*
src/settings/advanced-source.*
src/settings/source.*
src/settings/source1.*
src/yetanotherproject/source.*

After clicking one of file, i would get filtered list of strings. Or relevant strings on top. Alternatively, filtering would be based on folder.

**Comment by vslavik** [comment]
There is already sorting by file order, which is a similar thing and is what translators _actually_ care about — i.e. locality of the strings. Almost nobody (except you) cares for *source code location* as a translation, with the exception of the need to look up the string in context (which too, is already there). IMHO filtering by source file makes precious little sense and would needlessly complicate the UI.

Feel free to implement it, submit a PR and convince me otherwise with the quality of your implementation, but I have no plans to implements this myself.

**Comment by sirdanielk** [comment]
Thanks for your reply, but i was expecting that..

First of all, there is no help file for your settings, so i had to find out how sorting options work by myself - by file order does not work as expected on my 2k+ string .po file, this option sorts strings alphabetically almost same as sort by source option, cant distinguish between the two. Thats why i proposed new feature. Not sure if i found bug in poedit. Untranslated strings are always alphabetically sorted for me no matter what. Grouping untranslated strings by source would be same what i proposed by filling this issue..
Also, unfortunately i dont see reference to the source code on the right side of poedit window as discussed in #167 I think will leave ths as is since reference subject is a bit touchy.

Thanks for developing this program.

**Comment by vslavik** [comment]
> First of all, there is no help file for your settings

First of all, you're not entitled to anything. Second, going to the View menu for settings that affect *viewing* things doesn't require a genius expert, or a manual, and the items are rather self-explanatory.

> this option sorts strings alphabetically 

Unless you use some unusual extraction method (not Poedit's builtin) or unless you *sort your PO files yourself* with some tool, no, file order _is not_ alphabetically. This is simply not the case. If your files are sorted alphabetically, it must be because you did it to them.

> Also, unfortunately i dont see reference to the source code on the right side of poedit window 

That bug *also* mentions where it *is*, you should have read it in its entirely instead of just the title. Again, looking at the menus to see what's there would go a long way.

**Comment by Stadly** [comment]
I think filter the strings by reference could be quite useful.

Applications often have a modular design. You have a core application, and different modules can be built and loaded into the core application to provide new functionality. From my understanding, it's not a good idea to have separate `.po` files for each module when using gettext, but the translatable strings from all modules should rather be combined into a single `.po` for the entire application including all modules.

To reduce the time it takes to translate your application to a new language, the work is often separated between several translators. Letting the translators translate a module each can often be a good solution. The way I currently do this is to look at the references in Poedit, find the strings that belong to a module (this isn't so hard, due to the `xgettext -F` flag) and ask a translator to translate the strings with those entry IDs. Strings that are used by multiple modules will be translated by the translator translating the first module using the string. Asking the translator to filter the strings so that only those with a reference matching `/module/foo/` are shown would be even easier than this approach.

Another use case is when there is not enough time to translate all parts of the application, and which modules should be translated first must be prioritized. This is, for example, not uncommon with Web sites, where modules delivering public content may be more critical than other parts. In this case, it might not be sufficient to translate all strings in the part of the `.po` file that has a first reference `/module/public/...`. If a string used in the module `public` was also used in the module `foo`, the string would not be positioned together with the other strings concerning `public`, but rather together with the strings concerning `foo`. The result is that translating all strings used by a specific module is quite hard, since they are not necessarily positioned together in Poedit. However, if one could filter the strings so that only those with a reference matching `/module/public/` were shown, it would be very easy.

**Comment by vslavik** [comment]
> I think filter the strings by reference could be quite useful.

Please *read* preceding comments first before commenting yourself. Your PRs are welcome.

**Comment by Stadly** [comment]
> IMHO filtering by source file makes precious little sense and would needlessly complicate the UI.

I did read the preceding comments. That's why I present use cases arguing that filtering by source file/directory might make sense.

Unfortunately I lack the competence to implement it myself. My aim was to add my thoughts to the discussion whether implementing the feature is worth considering, which I think it is.
