### ISSUE TITLE
Cannot cancel when quitting Poedit

### ISSUE THREAD

**Issue by zwpwjwtz** [vslavik/poedit#245]
## How to reproduce
1. Modify a po file;
2. Press Ctrl-Q;
3. Click "cancel" button;
4. Program quit directly.

## Version Info
Poedit 1.8.7
wxgtk 3.0.2 & wxgtk2.8
KDE Plasma 5.5.4 (Qt 5.5.1)

## Related Bug
Not sure if it is related to #169

**Comment by zwpwjwtz** [comment]
Sorry for mislabeling the issue. Only "cancel" button does not work.
Also reproduce in Ubuntu 15.04 & 16.04.

**Comment by zwpwjwtz** [comment]
@vslavik Any idea?

**Comment by vslavik** [comment]
> @vslavik Any idea?

Sure, one: this kind of bugging is annoying and inappropriate. Your bug report is appreciated (one of the few that include everything necessary to reproduce), bugging me because you feel you're entitled to faster reaction times/fixes is not (and you are not). I'm dealing with issues as fast as I can. As a matter of fact, I fixed this yesterday, just didn't push yet. Now I regret doing so a little bit, because the lesson you'll take from it is that bugging works :(
