### ISSUE TITLE
Direction of RTL text in the suggestion panel is wrong

### ISSUE THREAD

**Issue by SafaAlfulaij** [vslavik/poedit#248]
The RTL text layout direction in the suggestion panel is LTR, as full stops appear at the beginning (right side) of the second sentence (As in English) while they should appear at the left.
OS: Windows 10
PoEdit version: 1.8.7 (4193 build)
![poeditproblems](https://cloud.githubusercontent.com/assets/3509617/13512081/a9f20762-e1a9-11e5-9d8a-437aacdcb38b.png)

**Comment by vslavik** [comment]
Please provide more details so that people not fluent in Arabic have a chance. At the minimum, the PO file in question would be helpful and so would be some explanation of how it *should* look. E.g. is the suggestion shown correctly when you copy it to the translation? In other words, is it a matter of bad display or bad data?

Thanks!

**Comment by SafaAlfulaij** [comment]
You can see in the Translation input box that the full stop is to the left of the sentence, which is correct because the the direction of the text is RTL. In the suggestion item, the full stop is to the right (talking about the second line of course) while the text direction is RTL.
It's like the problem if the full stop is like: "**.**This is a sentence" (At the beginning), while it should be "This is a sentence**.**" (At the end/right side in case of LTR text/left side in case of RTL text).
Things can get worse if parentheses are there!
And I can guarantee that it's a display problem, the data is correct.

Visual Explanation:
![poeditproblems_direction_explain](https://cloud.githubusercontent.com/assets/3509617/13548705/67408952-e307-11e5-83ff-e15cb1038582.png)

It's strange that this problem is only with multi line text, the single line text's direction is correct! :)
![poeditproblems_correct_suggestion_direction](https://cloud.githubusercontent.com/assets/3509617/13548641/0efacb00-e306-11e5-9c4c-d927860b2816.png)

**Comment by vslavik** [comment]
Thanks! However, please do provide the PO file I asked for. The reason I ask for it is not to bug you with meaningless demands, the reason is that I *need* to be able to reproduce it. It's nice that you "guarantee that it's a display problem", but you can't possibly know what (invisible) directional indicators are there, so I need to test it myself.

> Visual Explanation:

So your only complain is about the period? Are you *sure* the actual text doesn't have the period in an embedded LTR region? (That's why I asked about copying, by the way, because I'm reasonably sure the text area does things correctly.)

That only multiline layout is affected may actually make sense if a newline resets directionality somewhere.

**Comment by SafaAlfulaij** [comment]
I don't think that inserting LRM/RLM/LRE/RLE characters is a good practice! The input box should handle that without problems, but oh, wxWidgets? Can't say anything about the RTL support in that toolkit. But I really thank you for all the work you did to support RTL! You did a great work in that! :)

Anyway, here you are, this is the file:
```
#
msgid ""
msgstr ""
"Project-Id-Version: Test\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-04-27 17:42+0530\n"
"PO-Revision-Date: 2016-03-05 19:41+0300\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && "
"n%100<=99 ? 4 : 5);\n"
"Last-Translator: Safa AlFulaij <test@gmail.com>\n"
"Language-Team: \n"
"Language: ar\n"
"X-Generator: Poedit 1.8.7\n"

msgid "File"
msgstr ""

msgid ""
"Currently selected Data storage folder is readonly. The storage folder was temporarily switched to Internal "
"memory. Please choose valid storage directory."
msgstr ""
"مجلّد تخزين البيانات المحدّد حاليًّا للقراءة فقط. نُقل مجلّد التّخزين مؤقّتًا إلى الذّاكرة الدّاخليّة. فضلًا اختر دليل تخزين "
"صالح."
```
(I added an empty entry because of the source input display issue that I reported.)

**Comment by vslavik** [comment]
> I don't think that inserting LRM/RLM/LRE/RLE characters is a good practice! 

That's a) besides the point and b) uninformed — they exist for a reason, said reason being that there are situations when they are *needed*. 

I should have all I need here, thanks. I'll look into it a.s.a.p.
