### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#256]
Hi,

While translating the app into hebrew I noticed there are some missing strings to translate in Crowdin (not sure about other langauges):
New item
Edit item
Delete item
Move up
Move down
Poedit Preferences (the title header of the preferences window)
http://prntscr.com/aiqakz  (most of it is missing from Crowdin)
http://prntscr.com/aiqb8j
http://prntscr.com/aiqbj2
http://prntscr.com/aiqbnb  (and I'm guessing all the other update-related windows that I can't possibly reproduce now aren't translatable)

There might be more, that's all I found..

Thanks.

**Comment by vslavik** [comment]
> New item

You don't say where, but if I had to guess, it's in the list control, which will be replaced soon-ish anyway, so I'm going to ignore those — it's not worth any effort.

These strings come from wxWidgets and are translated (or, as the case may be, not in Hebrew) in there. That means much fewer translations (wx's translation file is *huge*), but on the other hand, those strings are rarely seen, so it's mostly OK. When some are too visible to get such second-class treatment, I pull them into Poedit proper, 

> Poedit Preferences (the title header of the preferences window)

Ditto, but this is a high-visibility string that *should* be migrated into Poedit proper to give it better coverage.

> http://prntscr.com/aiqakz (most of it is missing from Crowdin)

These were intentional. That'll change in Poedit 2, but not now.

> http://prntscr.com/aiqbnb (and I'm guessing all the other update-related windows that I can't possibly reproduce now aren't translatable)

This is the WinSparkle updater project at https://crowdin.com/project/winsparkle (see also Poedit's project description where it tries to explain this). I took the liberty of adding Hebrew there if you want to tackle it (testing translations is a bit more complicated there, email me if/when you'd like a Hebrew-including version).

**Comment by ItielMaN** [comment]
> You don't say where
Just to make sure we're talking about the same thing, it's in the Catalog manager when adding/editing a project, and in catalog's properties > Source keywords tab.

**Comment by ItielMaN** [comment]
While testing Poedit on Mac OS X El Capitan, I see some more untranslatable strings:
Services
Hide Poedit
Hide Others
Show All
Quit Poedit

If I'm not mistaken these appear on the first or second tab.

**Comment by vslavik** [comment]
You’re right, added now (they too come from wxWidgets), thank you!

**Comment by ItielMaN** [comment]
I have some more untranslatable strings:
Poedit Error  <-- This one is the window's title
nplurals = 1 but plural expression can produce values as large as 1     <--- I guess there are more strings like this one I can't possibly reproduce

**Comment by vslavik** [comment]
> Poedit Error <-- This one is the window's title

I imported this (and other one) too. They come from wx and there are probably quite a few more. At some point, I have to call it quits and say that for full translation of very rare error etc. strings, one needs to translate wxWidgets too.

> nplurals = 1 but plural expression can produce values as large as 1 <--- I guess there are more strings like this one I can't possibly reproduce

This (and many other strings) come from [GNU gettext tools](http://savannah.gnu.org/git/?group=gettext) and need to be translated there.

**Comment by ItielMaN** [comment]
Well that's way over my head.
If you have no more comments for this issue, it can be closed.
If I'll find more (native, non GNU/wxWidgets) strings I'll report back in a new issue.
