### ISSUE TITLE
Poedit cant open po file if there is an 'á' in the file.  

### ISSUE THREAD

**Issue by mxsxs2** [vslavik/poedit#264]
Hi.
The software seems not to handle the Hungarian characters too well.
If there is any of éíöóőüúű is in the po file, then character is going to be converted to the English equivalent.

If there is an 'á' located in the file then the application wont open at all.

![capture](https://cloud.githubusercontent.com/assets/13612429/14333732/15804c42-fc48-11e5-9ce8-be1fb0f4b0a7.PNG)
![capture1](https://cloud.githubusercontent.com/assets/13612429/14333738/1c36b6b6-fc48-11e5-965a-76b7d0f94658.PNG)

**Comment by vslavik** [comment]
> The software seems not to handle the Hungarian characters too well.

This is preposterous. It would be great if you could, as a rule of thumb, *not* immediately assume that the developer is grossly incompetent (*translation* app not handling charsets?!) and instead consider the possibility that the thing the application is telling you *is actually correct*.

Your file is broken and was probably created manually by somebody who didn’t know what they were doing. Most likely, based on your description, the file lies about the charset it uses in the header and Poedit complains, because it cannot reconcile the lie with the reality of how the file actually is encoded. But I can’t be sure, because you spent extra time pointlessly censoring the screenshots and didn’t have any left to attach the actual file :(
