### ISSUE TITLE
Catalog manager allows creating nameless projects

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#268]
Hello,

It seems that clicking "OK" in the "Add/edit catalog" dialog (in the catalog manager) without entering any text will result in the manager "thinking" a catalog was actually created.
STR:
1. Open Catalog manager
2. Without having any catalogs in the list, click the "New" button
3. Without entering any text in the new dialog, click OK
4. In the left panel, the table will appear empty (catalog, total, untrans etc) while it shouldn't appear at all (and for comparison, repeat steps 1-4 but click cancel instead of OK. The table will not appear)

Thanks.

**Comment by ItielMaN** [comment]
Well, not exactly "nameless projects" since no projects are really created. Just the table appears needlessly.
But you get my point :)

**Comment by saudss** [comment]
ggggg

**Comment by vslavik** [comment]
As far as I understand it, this is normal behavior. Yes, it’s ugly that the list is shown when nothing is selected in the list, but it doesn’t break anything, so I’m not going to bother making this prettier — the whole manager thing is ugly and barely functional and needs serious rework anyway.

**Comment by saudss** [comment]
I am not sure if this mail for since my mail was in CC . So if this mean sending to us.
Let me tell that your mail showing someone has something but without nothing.
At the end of the day if we do excise as per below :
nothing + nothing = nothing.
nothing - nothing = zero
Get well soon.
Regards
Sent from Outlook Mobile

    _____________________________

**Comment by vslavik** [comment]
@saudss you received the notification because you previously commented on this issue (your stupid spammy comment read, in its entirety, “ggggg” and was since deleted). I don’t know why you felt the need to do that or why you felt the need to add another crazy and/drunk comment like this now, but please stop and don’t post on this project again until you have something sensible to say.
