### ISSUE TITLE
Multiline source text in list is treated as RTL text

### ISSUE THREAD

**Issue by SafaAlfulaij** [vslavik/poedit#275]
I just downloaded the last update, and noticed a problem in the subtitles grid.
The source text is treated as RTL, and the place of the dots is wrong.
There is also a strange behavior that the multi-line sentence order get lost (swapped) in the grid entry.
Check the highlighted string and see where is "You're awesome!".
The string is:
`You’re awesome! Thank you so much`
`for purchasing Poedit Pro.`

![poedit_grid_issue](https://cloud.githubusercontent.com/assets/3509617/15891799/f3e960a6-2d7e-11e6-976d-04ae0329b049.png)

Huge thank for your work! :+1:

**Comment by vslavik** [comment]
Please be (much) more specific (see e.g. [this article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html). It’s not at all clear to me what the perceived problem is, why you’re sure it’s a Poedit one (and not bad PO file content), even what you *mean* and above all, I lack the file PO file to reproduce.

As an aside, I cannot discourage you from using Arabic as the source language enough. Just don’t. Gettext is not well suited for that (among other things, it makes it impossible to use plural forms in any sensible way). I suggest that you do what the rest of the world does and use English as the source code language.

**Comment by SafaAlfulaij** [comment]
Well, sorry about that!

First, when the UI is translated to Arabic:
![Arabic UI](https://cloud.githubusercontent.com/assets/3509617/15976257/3b5c28a6-2f5a-11e6-8c96-6f6de1e7a0d6.png)

As you can see, the ordering of the English sentences is reversed in the grid.
And the full stop placement is wrong as well, which means that the text direction is set to RTL while is should be LTR for English text.

_Notice that the source text of the file is English, check the second screenshot to make sure._

Next, with an English UI:
![English UI](https://cloud.githubusercontent.com/assets/3509617/15976256/3b5b85e0-2f5a-11e6-9252-08b792ab23a0.png)

Now we can see that the Arabic sentence ordering is reversed, and the direction is set to LTR. Check the comparison between the grid item and the translation text edit box.

I think that less text and more screenshots is better for our cases with direction of text :)

**Comment by vslavik** [comment]
> I think that less text and more screenshots is better for our cases with direction of text :)

Well, no, that chaotic drawing makes no sense to me. As always: If you find issues with Poedit, *describe* them and provide *reproduction steps* — that includes a PO file as I asked above.

**Comment by c72578** [comment]
Here are some steps to reproduce:
OS tested: Windows 7, 64Bit SP1
Poedit: 1.8.8

- Download current ar_SA.po for Poedit from Crowdin
https://crowdin.com/project/poedit/ar/3/download
- Start Poedit and Change the UI Language to Arabic. Restart Poedit.
- Open the downloaded ar_SA.po in Poedit
- Search for "awesome" using ctrl+f (find in source texts ticked) ...
- A picture in Poedit similar to the first screenshot from SafaAlfulaij will show up

Remark (Václav, you know this of course, but it helped in my case):
The UI language of Poedit can also be restored using regedit, just in case somebody tries "ar" - is not so familiar with it and wants to restore to "en" ore a different language
[HKEY_CURRENT_USER\Software\Vaclav Slavik\Poedit]
ui_language

**Comment by ItielMaN** [comment]
I'll try to make the issue more clear.

**When Poedit UI is English/LTR langauge:**
When the source text has (unnecessarily long but) multiple lines, such as (taken from Poedit strings for translation):
`Purchasing the full version will unlock more features\nin this and future versions of Poedit, including:\n\n`
or
`You’re awesome! Thank you so much\nfor purchasing Poedit Pro.`
and the **translation text** is RTL, Poedit will swap the translation lines' positions (in the preview, not in the editor below), and part(s) of the translation will be displayed as LTR (for example, the dot will be located at the beginning of the sentence).
So instead of displaying:
`You’re awesome! Thank you so much\nfor purchasing Poedit Pro.`
Poedit will display this (and I'm trying to transliterate it as much as I can into english):
`.Poedit Pro Thank you so much for purchasingYou’re awesome!`
(The missing space between "purchasing" and "You’re" is intended- that's how it looks)

**When Poedit UI is RTL language:**
Ditto, but for the **source text**.
The source text is displayed as:
`.for purchasing Poedit ProYou're awesome! Thank you so much`
Whille the translation makes sense.

Hope this clears thing up :)

**Comment by ItielMaN** [comment]
Thanks Václav, can you possibly provide the updated exe file (or installation) so we would confirm this is fixed?
