### ISSUE TITLE
© is preceded with bogus symbol when creating or updating .po file from .pot

### ISSUE THREAD

**Issue by sszachow** [vslavik/poedit#280]
**S/W:**
Poedit 1.8.8 (4339)

**PLATFORM:**
Windows 7 Enterprise with SP1

**PRECONDITIONS:**
- Have .pot file with following lines at the beginning (UTF-8 w/o BOM):
```
# Some name
# © Copyright 2014-2016 some company
# Some license notice
#
#
#, fuzzy
msgid ""
msgstr ""
```

**STEPS:**
1. Open .pot file from preconditions in Poedit.
2. Create .po file for some language, for instance German (Germany).
3. Open created file in notepad.

**EXPECTED:**
There are no bogus chars added.

**ACTUAL:**
Following char is added before the '©' symbol: 'Â'.
It looks like this after creating or updating existing .po file:
```
# Some name
# Â© Copyright 2014-2016 some company
# Some license notice
#
#
msgid ""
msgstr ""
```

**Comment by vslavik** [comment]
Please actually provide things necessary to reproduce, i.e. basic information such as your platform (which is always relevant) and attach the file instead of describing what (you think that) is in it.

Please also try with a *valid* POT file, because yours isn't. It lacks the header which contains, among other things, specification of the file's charset. You uses a non-ASCII character and didn't specify what charset you encoded it in, so you're basically expecting Poedit and GNU gettext toolchain to read your mind and guess the intent correctly.

I agree that Poedit or whatever probably shouldn't make such a change (innoculous as it is), but on the other hand, it's just following the time-proven GIGO principle. Unless I'm missing something, that is.

**Comment by sszachow** [comment]
Hi @vslavik,

Setting charset in pot file helped.
Closing this issue.

Thanks!
