### ISSUE TITLE
Is there a way to see the "References" without right clicking?

### ISSUE THREAD

**Issue by denis-bisson** [vslavik/poedit#282]
Hi!

I am a proud registered user of **poedit** and I love it.

I know I am lazy but more it goes, more I found annoying having to right click on entry to see the References. You know, the little text that appear below "References:" when we right click on an entry?

Would it be possible to see it without having to right click like in a dedicated new column, or into a status bar, etc.

I tried to cycle through the menus and did not find an options for that... I know, I'm lazy... I am using most of the time the keyboard and to view that "References" is the only moment I'm using the mouse during a **poedit** session. Pressing the kind of popup menu key on my keyboard doesn't bring up that popup menu neither... So because of all this, that's why I am making this suggestion, if it's not already there.

Other than that, I'm using it and I love it.

Denis Bisson.

**Comment by vslavik** [comment]
> I tried to cycle through the menus and did not find an options for that... 

It’s in *Edit → Show References*. I suppose *View* or *Window* menu would be more appropriate…

>  Pressing the kind of popup menu key on my keyboard

I don’t know what you mean by that, sorry. If there’s some bug (i.e. Poedit behaves differently from other native apps on whatever operating system you use), please file a separate bug and include details such as versions of everything (OS, Poedit), detailed and accurate descriptions of steps to reproduce and expected+actual behavior.

**Comment by denis-bisson** [comment]
Hi!

Now, I need to go, but I'll write back later here.

Regarding what you did not understand, I was talking about that key:
http://www.howtogeek.com/wp-content/uploads/2015/07/a-keyboard-shortcut-that-can-be-used-in-place-of-the-context-menu-key-01.jpg

I don't think it's a "problem" because anyway in many application it does not bring the popup men anyway... But sometimes it does and I just wanted to let you know at least I've tried that. Since it would have been just a way with the keyboard to quickly see the reference. But I would have much prefer to see that little sentence shown for the reference in a status bar, in a new column, on the right side, something like that. :-)

I'll add something later. I need to go.

Denis Bisson.

**Comment by denis-bisson** [comment]
>It’s in Edit → Show References. I suppose View or Window menu would be more appropriate…

  Regarding that, yes, I've already seen that maybe two weeks ago. I am under the impression that this function is doing a little bit more than just showing the reference: it attempts to open it via external viewer or something like that. In my case, it does not work and anyway, I would prefer to don't spend time making it work because I guess I would need to install the actual compiler who generate the .PO file, which I do not necessarily have, on that machine for example...

  But just seeing the hint, the reference itself, helps.

  For a while, I've tried to work with that window you're talking about. Even if it ends up with an error like "Error opening file!", I was hoping to work simply by looking at the top of the window where it was written "Source file occurrence:". Since this is update as we cycle through the expression list, I though it would work... But it is still annoying because often in the process we need to do ATL-TAB to go back and forth in different applications and when we come back to the poedit tool, that infamous window is not bringing back on top. I know I'm lazy but it is a little annoying that I need to bring it manually. Also, it does not fit cleanly since it's not attached or included into the poedit main window...

  For all this, that's why I was hoping there was a way to simply see that reference as a hint somewhere... You have a label where it says "Source text:". Maybe the reference could be written between parenthesis at that place, in smaller letter, something like that. Or even above, etc.

  I do programming too and even if the Edit-->Show preference things would do the job, I am not sure I would like it to attempt to open it each time. If it is my own application I am translating, I know it. Just see the reference will tell me the context and I would not need more...

  But again, all this is simply my little humble point of view from a lazy guy. Ha! Ha!

  I will keep be a proud registered user of the tool! ;-)

Denis Bisson.

**Comment by denis-bisson** [comment]
...and by the way, I forgot to write that when there two identical expression in the .PO file, to help us to give the context, you write between bracket the reference where it's coming from!!! That's this little hint I would like to view for all the expression, not only for those present more than once in the same .po file...

Ok. Ok. It's my last post on this... :-)

Denis Bisson.

**Comment by vslavik** [comment]
> I am under the impression that this function is doing a little bit more than just showing the reference: it attempts to open it via external viewer 

You are wrong. Please do try to actually use it.

> ...and by the way, I forgot to write that when there two identical expression in the .PO file, to help us to give the context, you write between bracket the reference where it's coming from!!! That's this little hint I would like to view for all the expression, not only for those present more than once in the same .po file...

This is completely off-topic here (if you insist on using this bug tracker instead of support email, please do keep one issue per one, well, *issue*, otherwise the resulting mess is unmanageable), but this has nothing to do with things "present more than once" — that's *impossible* in gettext PO files. Instead, these items are differentiated by the *context* (please refer to the GNU gettext manual for these concepts) and Poedit is simply showing the context when (and only when) it is provided.

**Comment by denis-bisson** [comment]
Hi!

Well... I'll keep posting here just in case in two years someone re-read that and would like to know how it ends. :-)
But take it easy, I am certainly wrong. :-)
So I'll continue with my single issue and if it's incorrect, simply ignore my post. Fair enough?

Maybe I did not express myself correctly.
Maybe I did not use the right terms.
Let's retry.

In the following image we see the expression "**About...**" two times. Identical. We see that one is coming from a form file called "**tfrmabout**" and in the other we see it's from the main form "**tfrmmain**". We see the references. At two places. We see it between brackets AND we see it at the button as a label. I like that. Sometimes it helps to figure some subtle variances.
http://i685.photobucket.com/albums/vv211/explorerchess/TwoTimesSameShowsReferences_zps4soy64vc.png

For the others above, we don't see it. So that's why I was saying it looks like when the expression is used more than once, it looks like the reference is written and not when it's single unique. For example for the "**<Modified>**" just above, it's not written it's coming from unit "**unlg**", which can be seen if we right click on it.
http://i685.photobucket.com/albums/vv211/explorerchess/SingleExpressionReferencesNotShown_zpsxtekhjl0.png

My humble initial and single issue, was just to know if there was a place, an option, something I overlook after a few weeks, that could make that reference appear somewhere as we browse through the lines.

Like I wrote, I've already tried the "**Edit-->Show references**". I though it was not the proper way, especially with the result. It shows it, you're right, but tell me I am not bright if you want, I had the impression it was attempting to open something else with error message saying "**_Error opening file_**". Also, to have it in a separate window, it goes under the others after we've done a few ALT-TAB and when we come back to **poEdit**, the main **poEdit** window come back  on top but not that one, we need to manually restore it each time. I prefer to right click then to get me reference. It does'nt deserve to be open in a separate window just for a few words...
http://i685.photobucket.com/albums/vv211/explorerchess/EditShowReferencesResult_zpswe0dy2j5.png

So all this just to ask if there was a way to have that infamous references shown in a status bar, in a label, somewhere. In my little short experiences of converting .po files, most of the time, references is what is shorter than. It's way shorter than the source text or the translation text. I was thinking it's me who was not seeing the options to make it appear somewhere in the interface without having to right click or to make appear an isolated window, etc. I was too shy to write it was a "bug" to not show it so I was politely asking if there is an option somewhere I was too stupid to change. Something like this:
http://i685.photobucket.com/albums/vv211/explorerchess/UglyMontageOfWhatIWasHoping_zpsg798tbw2.png

I won't change and keep working with **poedit** because I much prefer it over the others. But just as an example to legetimate why I was sure there was a simple way to show the references for each expression, here are other similar tool showing the references, always, as we cycle through lines, without having to double click, having to right click or living with a separated isolated window:
http://i685.photobucket.com/albums/vv211/explorerchess/SampleWithVirtaal_zpsg4cqjj51.png
http://i685.photobucket.com/albums/vv211/explorerchess/SampleWithBetterPoEditor_zpsrncc2lly.png
http://i685.photobucket.com/albums/vv211/explorerchess/SampleWithEazyPo_zpshs2tszdb.png

I hope all the links for image will work after posting, they were in the preview. :-)

Denis Bisson, still a proud registered user of **poEdit**.

**Comment by vslavik** [comment]
I see. You conflate two unrelated things and because you mentioned viewing references in right click menu prominently (where message context is never shown), I didn't realize you were talking about the *message context* (only) the whole time.

**Reference** = where the string is used in the source code (so that you can look there *for reference* and better understand how the string is used). The error you mention would be because you opened the PO file without actually having the *referenced* source code files.

**Context** = *optional* disambiguation of otherwise identical strings that may require different translations despite being expressed in the same way in English. Because they are optional, they may not be there (it's up to the developer, not Poedit), and Poedit always unconditionally shows them when present. GNU gettext manual [explains them](https://www.gnu.org/software/gettext/manual/html_node/Contexts.html).

If this remains unclear, I strongly recommend reading through select bits of the GNU gettext manual, it's really the best thing to do understand its subtler features, but the above is the gist of it and sufficient for this discussion, I think.

After seeing the screenshots, I think I understand the problem. It's your PO file: it's confusing. It's obvious from your screenshots that it was created by some non-standard tool (if I had to guess, I'd say the tool was developed by somebody unclear about the reference/context thing too — if it's somebody in-house, [this spec](http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html) is invaluable and very well written; if it's a publicly available tool, I'd be interested in knowing what).

Normally, references are locations in actual files, e.g. `whatever.php:13` so tools like Poedit can show line 13 of the file *where the string is used*.  But this tool puts some symbolic ID of the location in there. That's unusual, but fair game: sometimes you just don't have a file to point to (e.g. using a database).

What isn't fair game is that it apparently sometimes puts them same symbolic location IDs into message context. That's not only terribly confusing (case in point: this very issue), but flat out *wrong*. It should either use references for everything and not touch contexts, or put the location ID as the context and don't add references, or always put it into both, but *not* arbitrarily mix and match both approaches.

In short, it's not that Poedit is showing references or contexts inconsistently. It's that your PO file is inconsistent and Poedit is just faithfully showing you what's in the file. Because the tool puts the same kind of strings into both contexts (of some items) and references (of some other items), they understandbly look the same to you and you didn't realize the difference. (*And* I had no clue what's going on from the original description without the screenshots...)

> But just as an example to legetimate why I was sure there was a simple way to show the references for each expression, here are other similar tool showing the references, always, as we cycle through lines, without having to double click, having to right click or living with a separated isolated window:

Poedit's references showing window is persistent and stays on top (it can't be hidden behind Poedit's window if you use the latest version of Poedit). It shows the actual reference, i.e. how the string is used, instead of merely a *link to the reference* as the tools in your screenshots. This is superior: with Poedit, you can see the reference, with others you can't, so you actually have to do all the clicks you complain about *in the other tools,* but not in Poedit! That you have to "live with a separate window" is intentional: otherwise the main window would be overcrowded (see your screenshots).

Of course, the above only applies to when references are used normally. When they are just some symbolic pseudo-locations, Poedit's UI for "normal" references doesn't work well at all. In this particular case, I think the UI should be improved to fall back to a simple list of references if they can't be found as files. If you could share your PO file (here or privately), I'd appreciate it a *lot*, because it would help with testing.

P.S. By the way, you can simply drag the images here, instead of hosting them elsewhere.

**Comment by denis-bisson** [comment]
Hello Sir!

So far, each time I've seen something for the "Context" it was the same text as for the "References" so I use terms indifferently thinking it was the same thing (without thinking in fact!).  But I was wrong. Now, because of your answer, looking at the actual .po file content, I see it's two different things. In my case, the "Context" is not given every time, apparently only when two expressions are the same, at that moment the line "msgctxt" is present and poEdit is showing it.

I will drop here a sample .po file made from a dummy project as an example. Two labels with the same name and one with a unique name. The "msgctxt" is present only for the labels with same names.
![dummy](https://cloud.githubusercontent.com/assets/16710801/16560234/12390610-41c0-11e6-8b62-6b176c2809c0.png)

Ok. Since now I know the correct term. :-) I'll stick to my single issue and the title of it: is there a way to show the "References" as we cycle through the text lines?

I took the time to download the "version 1.8.8 (4339)" to retry again the "Edit --> Show references" because in your answer it made me hope that the isolated window would stay on top. Maybe we could not have a single label in poEdit that would show that "References", I was hoping at least to make that window small in top right and see my "References". Well... When I tried it I keep having the an error dialog message saying "Can't open file 'C:\'..." each time I try it. I tried to place my .PO file somewhere else on the disk but always came up with that error. It does this even if I am running with admin rights.
![error](https://cloud.githubusercontent.com/assets/16710801/16560242/1cd6b446-41c0-11e6-9375-d6a3ef0bfb76.gif)

I took the time to make an animated GIF with the result with "Version 1.8.7 (7193)". I see the window but certainly not stay on top.
![previousversionnotontop](https://cloud.githubusercontent.com/assets/16710801/16560245/271bcb8a-41c0-11e6-8826-908d726f2998.gif)

> It shows the actual reference, i.e. how the string is used, instead of merely a link to the reference as the tools in your screenshots.

  Well... At least we see something that tells where to look in our source code.
  
  I guess I'll be less lazy, use the mouse, and right click with the mouse to see the "References" !
  
  Denis.

**Comment by vslavik** [comment]
> I will drop here a sample .po file made from a dummy project as an example.

I meant actually providing the PO file (and preferably non-dummy), not posting some partial *screenshot* of the file being open in some program... I can't open a screenshot in Poedit.

> is there a way to show the "References" as we cycle through the text lines?

See my previous replies.

>  It does this even if I am running with admin rights.

It works reasonably when the references used in the PO file are reasonable. If your PO file uses some crazy strings that are not files, then of course you're going to get errors: these things are not valid files. See my previous reply for more detailed explanation.

Let me repeat: the only way to fix what you dislike about Poedit's handling of your PO file is to **fix the tool that you use to create the file**. The tool is defective and produces defective PO files. There's no way to fix that in an editor for PO files. You need to fix the source of the problem — which is the mysterious defective 3rd party tool you use.

> I took the time to make an animated GIF with the result with "Version 1.8.7 (7193)". I see the window but certainly not stay on top.

You'll notice I said this is true *if you use the latest version.* You don't — at the moment I write this, 1.8.8 is the latest, not 1.8.7. It's always a good idea to make sure you have the latest version before filling a bug report — chances are it was fixed already.

**Comment by denis-bisson** [comment]
Hello Sir.
  
>I meant actually providing the PO file (and preferably non-dummy), not posting some partial screenshot of the file being open in some program...

  That's what I wanted to do but the kind of web interface rejects it saying "_Unfortunately, we don’t support that file type.  Sélect. fichiers Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP_." I zipped the .PO to have a .ZIP but still get the same message. When I saw that, since the file was so small and could fit in one single image, I though I could post that capture. No matter what, I just dropped them under this link. You won't see more than the whole thing you could see in the capture. You don't need a dropbox account. If they ever propose to login, just close that window, the two sample .PO file will be shown and downloadable.
  https://www.dropbox.com/sh/pjg9m9nwxkfcgib/AAACEV32P6ReHpDoDsIZJn8Fa?dl=0
  

  Regarding the "non-dummy" thing, since this simple test program illustrates the point, I think it was okay to keep talking with them.

>is there a way to show the "References" as we cycle through the text lines?
See my previous replies.

  Well... I am under the impression that you, you think I am hoping it would open the source file with the cursor flashing just next to the line to translate. If it is the case, no, I was not hoping this. I was just hoping to see the same thing as what we see when we right click, like "tfrmdummy.lbluniquelabelname.caption" the example I've just post. Don't worry. When I see "tfrmdummy.lbluniquelabelname.caption" I know exactly where to go! Some applications have many forms, it's hard to remember with just one word to know where it's coming from. But seeing things like "frmEntryEditor.lblParameterSpeed.caption" will tell me right away where to go. I press ALT-TAB, a few key strokes and I'm there. :-) Certainly it would be nice to open the file with cursor at right place but that's fine, I was not asking for that. :-) I was asking if there is a way to see what we see when we right click on the text to translate and we see "Reference: tfrmdummy.lbluniquelabelname.caption".
  
  It was not a "blocked" problem. I just wanted to know if we can avoid to right click with the mouse as I am from the old school using more naturally (and maybe faster) the keyboard and since the menu key on the keyboard was not bring up that popup menu... ( and I don't make this an issue!) It's not such a big deal. Since the few others editors I've tried it was showing that as we cycle through the line without clicking or doing anything more, I was thinking poEdit would do the same and it was just me, not bright enough, to see where I could make it appear as is. So I was asking the question.

>It works reasonably when the references used in the PO file are reasonable. If your PO file uses some crazy strings that are not files, then of course you're going to get errors: these things are not valid files. See my previous reply for more detailed explanation.
  Yeah... More I read, more I am under the impression that you, you though I was hoping the source file would popup with the cursor blinking right on the line. No. I was just asking if there was a way to make the single "references: tfrmdummy.lbluniquelabelname.caption" somewhere without right clicking. We know poEdit is able to read it since it shows it in the popup. So I though it could be displayed freely, just "references: tfrmdummy.lbluniquelabelname.caption".

  Just that.

  Even if the .po file is not "top-notch" respecting the standard regarding filename and line number for the reference info, I was hoping poEdit could show as a static information somwhere in the interface, without right clicking or an extra window, like the few others I've tried just to see what the other did. That's what I was asking. And since it shows it when we right click, we know it reads it.

Denis Bisson.

**Comment by vslavik** [comment]
> I was asking if there is a way to see what we see when we right click on the text to translate and we see "Reference: tfrmdummy.lbluniquelabelname.caption".

Again, it’s simply not possible to do that in the current version. The reason is that Poedit assumes normal PO files and references and your PO file is not.

I agree this should be improved to handle weird cases like yours gracefully too, as I believe I mentioned, but it’s not there yet. I will improve it, but I can’t make any promises as to when exactly, short of a vague “hopefully soon-ish”, sorry.

**Comment by prof7bit** [comment]
> Again, it’s simply not possible to do that in the current version. The reason is that Poedit assumes normal PO files and references and your PO file is not.

I still don't understand why it is "not possible" to show the contents of the reference field somewhere in the UI, there is plenty of vast empty space where it could be placed, lokalize even shows them as their own column in the list of strings. It would be very helpful to have this information during translation. Please reopen and implement. 

Also this is not a "weird case", these po files (as shown by the previous poster) are obviously generated by Lazarus, one of the few top tier cross platform RAD IDEs out there, the fact that you don't know this tool does not automatically make it "weird". The references are namespaces that identify the logical position in the "source" (half of which is generated by the Form-Designer and not user editable anyways). Nowhere is written that the references are meant to contain filenames, they are just "references to the source", this wording can be interpreted in any way you want, and in the case of visual or graphical programming tools (as in the example pointed out in this issue) they simply CAN NOT point to a line of source! And even if they were filenames the translators would not necessarily have access to these files.

**Comment by vslavik** [comment]
> Please reopen and implement.

Seriously? You don't get to make such demands. You're welcome to do the work and submit a quality PR, though. Might want to check the current 5 years newer version before ranting further, too.
