### ISSUE TITLE
[Feature Request] Dark mode/theme?

### ISSUE THREAD

**Issue by issyl0** [vslavik/poedit#292]
First of all, thanks very much for making PO Edit! 🎉

I'm on a Mac (Sierra, the latest OS version) and I wonder if having a dark mode/theme is on your todo list for PO Edit? I usually do work with translation files in the evenings, and the bright white is pretty jarring on the eyes, even with Flux enabled on my Mac, and this feature would be lovely.

I'd try to make a patch for you, but I'm not a MacOS/iOS developer - sorry!

**Comment by vslavik** [comment]
>  and I wonder i

Please don’t wonder and ask questions in the *issue tracker* — see https://poedit.net/support.

Given the app’s use of standard controls all over the place, there’s very little point in doing any dark mode until the OS has proper support. So that would be a no. You are more than welcome to do something about it yourself if this is something that matters so much to you, though.

> I'd try to make a patch for you, but I'm not a MacOS/iOS developer - sorry!

It’s possible to learn new things, you know…

**Comment by vslavik** [comment]
Now that Mojave comes with a native Dark Mode, Poedit (≥ 2.2) supports it: https://poedit.net/news/xliff-and-dark-mode/

**Comment by yarons** [comment]
@vslavik does it also work on Linux? because I can't find it.
