### ISSUE TITLE
Have an option to confirm and disable automatic "fixing" of PO files "bugs"

### ISSUE THREAD

**Issue by auriculaire** [vslavik/poedit#305]
While not standard, the PO files we use contain duplicate strings, which have different translations. In our case the disambiguation is done on the reference (i.e. '#: ...' line). Version 1.8 is unusable because it insists on "fixing" these duplicate strings, without any option to prevent it or completely disable it.

**Comment by auriculaire** [comment]
Actually, while 1.7.7 is better in this regard, having to select which validations are done by the "Validate" button or following a Save would be even better. Currently, we can save our PO files, but need to reload them after a save to continue working as all the duplicate strings are marked as red.

**Comment by vslavik** [comment]
> While not standard
…
> “fixing”

Wow, that arrogance is breathtaking. That you don’t even stop to consider that maybe, just *maybe* it is you that is doing something stupid, that takes one heck of a self-confident mindset.

Poedit *is* fixing them *because they are broken* and the only reason it has to do it in the first place is because of incompetent developers who write broken tools. Non-technical translators then have to deal with the fallout and this makes their lives much easier.

Your files are broken crap. Don’t blame the messenger.

\</rant>

If you generate files in some format, for crying out loud, be a responsible developer and read [said format’s spec](http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html) first. Or at least the user level gettext manual. If you did, you would have understood why duplicate `msgid`s are complete nonsense  and that `msgctxt` exists as a proper (and of course fully supported by Poedit) solution for disambiguation.

This autofix will not be removed or made optional. Fix your own mess.

**Comment by auriculaire** [comment]
Ouch. I did not mean to be arrogant at all. I'm sorry it came out this way. I'm very happy with PoEdit 1.7.7 and have bought a license because I believe so.

I recognize that the PO files I use it with are broken in that they do not follow the standard, but I do not have direct control over that in this case. I just do the translation. I just thought it would be simple to ask for confirmation before silently modifying the files in place. I was caught offguard and actually had to retrieve the files from backup because of the changes made.

I'm surprised by your strong reaction. The quotes merely implied that the fix in this case was not one. It wasn't undermining your work. I'll stick with 1.7.7 for now and look for another tool in the future.

**Comment by vslavik** [comment]
> I just do the translation. 

My deepest apologies then — I was certain from your wording that you (either singular or plural) are the dev of this. It still sounds like someone in your organization(?) is responsible for this misuse of the gettext format — and they really, really, *really* should change it. I’m happy to provide any consultation needed (although in all likelihood “msgctxt is a thing” is all the information needed).

> I'm surprised by your strong reaction.

You can’t imagine the amount of problems such broken files cause in the wild to translators who (understandably) don’t particularly care about gettext as such, the support load it generates and the blame than inevitably gets assigned to Poedit. Please see my reaction in that light: a developer (I thought) who intentionally creates bad PO files, *knows about it* and instead of fixing it, expects the world to accommodate their misuse.

> The quotes merely implied that the fix in this case was not one.

That’s the thing: **it was**. This is not about Poedit being picky or about this being a problem in Poedit. *Nothing in the entire gettext ecosystem* can correctly work with such files! 
1. GNU gettext tools won’t accept them.
2. You can’t create MO files from such broken POs — because 1. and because it’s *technically impossible* to represent that in MO (only one of the duplicates can be stored). MOs are necessary to *use* translations with gettext libraries.
3. None of the gettext libraries, for any programming language, can deal with this, because of both 2. and their APIs.

It simply *doesn’t work* the way your devs think it does. Either (a) they’re unaware and your duplicate translations actually aren’t used or (b) you had to rewrite all the tooling *and* client libraries to support it, which makes one wonder why a custom non-PO file format wasn’t used as well. 

If it’s (a), you guys really do need to fix it and it’s not because of Poedit 1.8, but because of the entirety of the gettext system.

**Comment by auriculaire** [comment]
What I know: The implementation of the PO files was done using an external library (http://www.cherubicsoft.com/en/projects/po-localization) which is causing the issues.

Now, the developers have access to the source code, so with your suggestion of using msgctxt, they could probably modify the library code to make it compliant.

In parallel, I can probably add in some msgctxt in the PO files, which will make the PO file standard-compliant, even if said context is ignored by the library code.

Cheers.
