### ISSUE TITLE
False positive with Percent sign in msgid

### ISSUE THREAD

**Issue by batisteo** [vslavik/poedit#306]
This string raise a check fail but shouldn’t:
```
msgid "10% discount"
msgstr "10%-a rabato"
```

**Comment by vslavik** [comment]
>  but shouldn’t

Do you have any factual basis for your belief that Poedit is wrong here? Because if you do, you forgot to include it… Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html, it explains very well why reproducibility and include full and detailed information  matters.

Absent any evidence to the contrary, this bug appears bogus. You not only did not provide the PO file, you didn’t even quote a single *whole* item and omitted its metadata. Which I’m pretty sure declares the item as being e.g. `c-format` or `php-format`, i.e. telling Poedit *and all other gettext tools* that the string follows certain formatting rules. Which it then doesn’t, neither in the source nor (of course) translation.

You need to fix your source POT and/or extraction method. See the GNU gettext manual for instructions.
