### ISSUE TITLE
Autofixing POs with duplicates doesn't preserve formatting

### ISSUE THREAD

**Issue by auriculaire** [vslavik/poedit#307]
Using 1.8.11 (I have added msgctxt to my PO file to make it compliant), I have the advanced settings set to not wrap the long lines and have kept the "Preserve formatting..." option enabled.

When I open an existing PO files, it will wrap all my lines longer than 79 characters, regardless of the setting value.

I have also tried re-enabling the wrapping, but at a higher value (e.g. 150), but it will still wrap the lines at 79 characters.

**Comment by auriculaire** [comment]
I have also tried re-enabling the wrapping, but at a higher value (e.g. 150), but it will still wrap the lines at 79 characters.

**Comment by vslavik** [comment]
> Actually, the problem is only when there are some duplicate msgids detected at open.

In that case I'm inclined to say it doesn't matter. It's the GIGO principle at work again. If the input is a broken file, all you can reasonably expect is a clearly explained refusal to open the file; anything more is extra.

Yes, it should be fixed ideally, but literally everything else has higher priority. If you feel different, I'd gladly merge your PR, but there's so many things to do on Poedit that *I* am very unlikely to do anything about pretty-formatting recovered broken *and* non-standardly formatted files (because if you just used the de-facto GNU gettext formatting of POs, you'd never notice).

You can always use `msgcat` to reformat the autofixed file to your liking yourself.

**Comment by vslavik** [comment]
Closing as WONTFIX (but would accept PR for it; I'm not *opposed*), because GIGO as explained above.
