### ISSUE TITLE
Possibly missing translation for "Recent" in Windows' Start menu search

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#310]
Hi Václav,

Using Windows 10, hebrew locale.
When typing "Poedit" in the Windows' start menu while the app has a recently opened (PO?) file, there's a "Recent" string that seems to be untranslated, and does not appear on Crowdin.

See screenshot:
<img width="294" alt="recent" src="https://cloud.githubusercontent.com/assets/18016656/21406943/c19729c4-c7d6-11e6-8423-5f0abba71500.png">

I suspect this might be Windows itself that has a missing translation for "Recent" but I'm not sure so I thought I'd verify the matter with you.

Itiel.

**Comment by vslavik** [comment]
I thought this was a wx bug, but apparently, Poedit doesn’t use that code, so it doesn’t seem that way. 

Can you please check how Notepad (after opening some files in it) behaves? Or Explorer (it doesn’t have “Recent”, but has “Frequent”)? Using right-click on the taskbar icon instead of the search interface?

Here, using Czech localization, everything is translated in taskbar and in start menu, but I can see “Recent” in search results too, for *both* Poedit and Notepad.

![parallels picture](https://cloud.githubusercontent.com/assets/145881/21594361/064dc48e-d122-11e6-9438-1a57d2aa2e8f.png)
![parallels picture 1](https://cloud.githubusercontent.com/assets/145881/21594362/0858ffdc-d122-11e6-9a28-a95495578edb.png)

**Comment by ItielMaN** [comment]
> Can you please check how Notepad (after opening some files in it) behaves? Or Explorer (it doesn’t have
> “Recent”, but has “Frequent”)? Using right-click on the taskbar icon instead of the search interface?

Yes, notepad also has the english wording "Recent".
Though, I can see a **translated** sting of "Frequent" in when right clicking the File Explorer's taskbar icon.

**Comment by vslavik** [comment]
> Though, I can see a translated sting of "Frequent" in when right clicking the File Explorer's taskbar icon.

Try the same thing with Notepad, you’ll see that Notepad has it translated there too — just not in the search interface.

I think it’s safe to conclude that this is a Windows localization bug. I’m closing it for now but if let me know if you spot if any application that does have “Recent” translated in the search interface.
