### ISSUE TITLE
Disable automatic fuzzy translations?

### ISSUE THREAD

**Issue by pjotrek-b** [vslavik/poedit#316]
Poedit automatically creates fuzzy translations whenever I create a new catalogue or update from source.

Is there an option to disable this feature?

In my case it adds hundreds of nonsense translations (German), which causes a lot of unnecessary work to remove them :(

Thanks in advance! :)

**Comment by vslavik** [comment]
> Is there an option to disable this feature?

This *preference*, like all the rest of them, is located in Preferences.

Please respect the instructions at https://poedit.net/support and don’t use the *bug* tracker for random questions.

**Comment by vslavik** [comment]
> I always do my homework before bugging anyone with a question.

This issue certainly doesn’t look that way — a bit confusing description, no reproduction steps, no details to speak of, not even absolute basics like version + platform information…  If you give no indication that you did any investigation (if that’s the case) and present no facts, you can’t expect people to assume you did.

> I've disabled "Automatically translate when updating catalog" - but that didn't seem to change anything.

You made some mistake when testing (I don’t know what, see above). *Of course* it makes a difference. Give me some credit, do you think there’s a no-op checkbox just to mess with users? 

> Of course, I've also read https://poedit.net/support
> But I found it better to ask this question publicly (instead of writing an email) - so others who have a similar issue might find this thread here.

Intentionally ignoring support instructions is not very nice — quite entitled, arrogant and asshole-y actually. Perhaps you should put respecting the project’s wishes above your personal opinion because as shocking as it may be to you, there may be actual *reasons* behind such things.

> Don't bother to reply.

Now you’re just being arrogant and extremely rude. OK, then.
