### ISSUE TITLE
Feature Request: Sources keywords - filter by Text Domain

### ISSUE THREAD

**Issue by ma-si** [vslavik/poedit#317]
It would be nice to define witch `text domain` we would like to update in .po file.
Ex. ui.po with 'ui' text domain and dictionary.po with 'dictionary'.

file default/pl_PL.po
PoEdit Source keywords:
translate:1,2c
translatePlural:1,2,4c
updates all text domains:
```
application [ dictionary ]
home [ ui ]
```

DESIRED something like

file dictionary/pl_PL.po
PoEdit Source keywords:
translate:1,2c='dictionary'
translatePlural:1,2,4c='dictionary'
will update only 'dictionary' text domain:
```
application [ dictionary ]
```

file ui/pl_PL.po
PoEdit Source keywords:
translate:1,2c='ui'
translatePlural:1,2,4c='ui'
will update only 'ui' text domain:
```
home [ ui ]
```

Directory tree
```
.
└── i18n
     ├── default
     │   ├── pl.mo
     │   └── pl.po
     ├── dictionary
     │   ├── pl.mo
     │   └── pl.po
     └── ui
         ├── pl.mo
         └── pl.po
```

**Comment by vslavik** [comment]
> It would be nice to define witch text domain we would like to update in .po file.

That's easy: make up your mind what your domain (singular) is. That's all there is to it. Poedit doesn't and can't care about your domain. "Domain" is a piece of software; a translatable chunk. It doesn't make sense to split a single domain (whatever it is you are translating)  into multiple fake intermingled sub-domains. That would be a misuse of gettext.

If your sub-projects are *not* intermingled, then setup separate extraction from their respective independent sub-directories. No problem there.

All this is explained in the GNU gettext manual, which should be required reading for developers using gettext. Poedit has a helpful link to it in the Help menu.

> translate:1,2c
> translatePlural:1,2,4c
> updates all text domains:
> application [ dictionary ]
> home [ ui ]

Ah, so that's why. You are confusing two completely unrelated concepts: *domains* and message *contexts*. No relation. Read the keywords spec documentation, it's linked directly from the properties window precisely to increase the chance that you do. 

The GNU gettext manual also explains, in detail contexts are, what they are for and how to use them. You need to read it.
