### ISSUE TITLE
Attempt at reversing translation

### ISSUE THREAD

**Issue by jonasgroendahl** [vslavik/poedit#324]
Hi,

I have attempted to reverse a translation from Danish to English because I'd like the standard language to be English. My approach has been swapping the terms in the .po file for every entry. I have double checked the original and the new file and it's 100% correctly reversed. Here are the two files (changed from .po to .txt in order to upload):

Original:
[original.txt](https://github.com/vslavik/poedit/files/716797/original.txt)

Reversed:
[translated.txt](https://github.com/vslavik/poedit/files/716798/translated.txt)

When I open the new .po file in poedit , i get that 87% is translated but the remaining i get the error "Error: this is the position of the first declaration". Does the .po file become corrupt when you swap the terms in the .po file like i did? Any other ways to reverse the translation? I really thought this would work :)

**Comment by vslavik** [comment]
This is a *bug* tracker, for reporting *bugs*, not asking idle questions (and especially ones that have no relation to Poedit at all!). Please respect https://poedit.net/support

If you’re manually changing PO files, a prerequisite is becoming competent with the file format. At the barest minimum, you should have read the GNU gettext manual and/or Pology’s PO format spec — it would then be obvious to you what the error means, if it is somehow unclear to you now. 

I’m glad to help with hairy issues (via proper channels), but you *have* to make an effort to study publicly available documentation first.

**Comment by insolor** [comment]
Check if there are no duplicate source (Danish) strings in the reversed file. 



-------- Исходное сообщение --------
От: jonasgroendahl <notifications@github.com> 
Дата: 19.01.2017  17:09  (GMT+03:00) 
Кому: vslavik/poedit <poedit@noreply.github.com> 
Копия: Subscribed <subscribed@noreply.github.com> 
Тема: [vslavik/poedit] Attempt at reversing translation (#324) 

Hi,
I have attempted to reverse a translation from Danish to English because I'd like the standard language to be English by swapping the terms in a .po file.. I have double checked the original and the new file and it's 100% correctly reversed. Here are the two files (changed from .po to .txt in order to upload):
Original:

original.txt
Reversed:

translated.txt
87% is translated but the remaining i get the error "Error: this is the position of the first declaration". Does the .po file become corrupt when you swap the terms in the .po file like i did? Any other ways to reverse the translation? I really thought this would work :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vslavik/poedit","title":"vslavik/poedit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vslavik/poedit"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Attempt at reversing translation (#324)"}],"action":{"name":"View Issue","url":"https://github.com/vslavik/poedit/issues/324"}}}

**Comment by jonasgroendahl** [comment]
thanks for the tip, that was one of the problems, i wasn't aware of the requirement for the msgids to be unique. still trying to figure out the second error message that im getting from poedit!
