### ISSUE TITLE
Localization in GitHub Suggestion

### ISSUE THREAD

**Issue by KeKeCoRe** [vslavik/poedit#330]
Hi, I wanted to ask if it would be possible to have a localization integration in file.mo on GitHub.

As I have seen that there were kinds of plugins on GitHub would be nice to be able to work directly with poedit.

[https://github.com/integrations/feature/localization](url)

**Comment by vslavik** [comment]
This is *bug tracker*, not a questions forum — please follow the instructions at https://poedit.net/support

You may want to [read this article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) first, though, because it's not at all clear what you're talking about (short of observing that putting binary compiled MOs into git makes no sense).
