### ISSUE TITLE
When selecting some text, the selection is sometimes not visible

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#334]
Poedit 2.0beta3
Windows 10
reliably reproducible

1. Start a fresh instance of Poedit
2. Open the attached [demo.po.txt](https://github.com/vslavik/poedit/files/786204/demo.po.txt)
3. Press <kbd>Ctrl+A</kbd>: the whole text is selected, but note that the final "r" extends half a pixel to the right of the main selection, then there is a gap of around one character, and then there is a thin selected vertical line<br>
    ![2017-02-19 21_45_18-demo po - poedit beta-version lauft am 15 03 2017 ab](https://cloud.githubusercontent.com/assets/3233724/23106554/9dc3b452-f6ef-11e6-932b-3b767ca756de.png)
4. Type <kbd>asdf</kbd>
6. Press <kbd>Shift+Home</kbd>, which selects the whole text, but the selection is not visible
7. Switch to another application
8. Switch back to Poedit: the selection becomes visible

----

And here's a variation on the same theme.

1. Start a fresh instance of Poedit
2. Open the attached [demo.po.txt](https://github.com/vslavik/poedit/files/786204/demo.po.txt)
3. Press <kbd>Ctrl+A</kbd>, like above
4. Press <kbd>End</kbd>: the selection is still visible, although it shouldn't be

----

And another one.

1.  Open Poedit with some file.
2.  Press Ctrl+F, type a word that appears in several messages, press Enter.
    _The next message is selected in the list. In the Translation field, the found text is not highlighted, but should be._
3.  Click on the title bar of the main Poedit window.
    _The found text in the Translation field becomes highlighted, as it should._
4.  Press Ctrl+G to find the next instance.
    _The next message is selected, and the found text is highlighted, as it should._
5.  Press Ctrl+G again (without switching applications or anything else).
    _The next message is selected in the list, and the found text is _not_ highlighted, but should be._
6.  Switch to another application and back to Poedit.
    _The found text becomes highlighted, as it should._

----

These are the last ones from my series of strange UI bugs, though while fixing this one, you may find some very related ones.

**Comment by vslavik** [comment]
Damn, so much for fixing this class of issues in 6fb3516136d7b35de1136466a19931db46ef08df.

**Comment by vslavik** [comment]
Confirmed present in 1.8.12 too.

The last one is actually a bit different: by default, text controls hide their selection whey they are out of focus: switch to another app or even another control within Poedit and selection disappears. That's the cause of the Find issue: the control doesn't actually have focus at that time, hence the selection is invisible.

How do you feel about this build: https://jumpshare.com/v/qOtA2RlONOhMuXJUNeZf ?

It changes the behavior so that selection *isn't* hidden when the text field looses focus. This is consistent with e.g. Notepad or Wordpad, fixes Find and has the side-effect of fixing the Select All bug as well.

Do you think it's a problem? Is it something that would annoy you?

**Comment by rillig** [comment]
The test build behaves exactly as I would expect. I don't know what you mean by _problem_ and _annoying me_ in your last sentence. I would be perfectly fine with Poedit behaving in the same way as what Notepad and Wordpad do.

That said, it sounds strange to me when you say _the default behavior is to hide the selection when out of focus_, yet you say that _Notepad does not follow this default behavior_. I always thought Notepad was the _hello world_ application of Windows programming, demonstrating the most basic use of a multi-line text field. Therefore, whatever Notepad does is what I regard as the default behavior.

**Comment by vslavik** [comment]
> The test build behaves exactly as I would expect.

Great, thank you!

> I don't know what you mean by problem and annoying me in your last sentence.

You have an eye for inconsistencies with Windows; you're the kind of user who *notices things*. That's absolutely great and to me, it means that if something feels off to you, I need to take it seriously (because there will probably be hundreds of others who dislike it but never tell me).

And this *is* a noticeable change in behavior and *is* something that isn't entirely common outside of the "entire window text editor" category, so I thought it would be useful to know your opinion. I admit it didn't even occur to me that your perspective could be that the current behavior (excluding the obvious, i.e. the Ctrl+A bug) is wrong and it *should* be more like Notepad. That was enlightening. 

In short: I shouldn't worry about it and should apply the fix. Thanks!

> That said, it sounds strange to me when you say the default behavior is to hide the selection when out of focus, yet you say that Notepad does not follow this default behavior. I always thought Notepad was the hello world application of Windows programming, demonstrating the most basic use of a multi-line text field. Therefore, whatever Notepad does is what I regard as the default behavior.

It isn't — by default, RICHEDIT controls auto-hide selection and you have to force them to behave like e.g. Notepad. [Quoting MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb774367(v=vs.85).aspx):

> **ES_NOHIDESEL**
> Negates the default behavior for an edit control. The default behavior hides the selection when the control loses the input focus and inverts the selection when the control receives the input focus. If you specify ES_NOHIDESEL, the selected text is inverted, even if the control does not have the focus.

I think this boils down to what you expect the control to be. If you regard it as a text input field, the default makes sense. If you view Poedit's editing area *as a text editor*, then it's reasonable to think that the default behavior is/should be a text editor default behavior, i.e. as Notepad. I on the other hand see the implementation of it, i.e. as a small-ish text control — you know, the whole not seeing the forest for the trees thing…
