### ISSUE TITLE
Consistent use of straight or curly quotes

### ISSUE THREAD

**Issue by fbonzon** [vslavik/poedit#338]
The English strings in Poedit source code use a mix of curly quotes and straight quotes. What is the preferred one?

Example with curly quote:
`_("MO files can’t be directly edited in Poedit."),`

Example with straight quote:
`_("don't delete temporary files (for debugging)"));`

**Comment by vslavik** [comment]
Please don't use the *bug* tracker for *questions*. 

As you can see in git history yourself, Poedit has >15 years of history; things changed. You can also see that *recent* commits use typographically correct strings, which is obviously preferred.

**Comment by fbonzon** [comment]
OK. Then do you care about consistent usage, and would accept a PR that changes straight quotes to curly quotes?

**Comment by vslavik** [comment]
"It's complicated?" 

In principle yes, of course, and I'd appreciate cleaning this up very much (ditto for … instead of three-dots). In practice, are you willing to deal with the mess it entails? This isn't just a search and replace, but a bit more:

1. Ensuring that affected strings are changed to wide strings (`L"foo"` vs `"foo"`).
2. Ensuring that affected files begin with UTF-8 BOM (as much of abomination as it is, Visual Studio needs it to compile such wide strings correctly).
3. Refreshing the POT and uploading it to Crowdin (I'll do this part, but it needs to be coordinated with point 4, which has to partially happen *before* and partially *after* this step).
4. Getting all translations from Crowdin, making the replacements in them so that no translations are lost due to this change. This is fun, because

    1. It should be done as quickly as possible to avoid loosing any new translation work
    2. It is non-trivial due to language differences, e.g. «French quotation marks» or „Czech ones“ [and so on](https://en.wikipedia.org/wiki/Quotation_mark)

…And that's why it's currently inconsistent.

(Reopening because you're right, this *should* be fixed.)

**Comment by fbonzon** [comment]
Yes, I'm willing to help and make this happen.

1. and 2. done in #339. I did not add the BOM in .xrc files. Should I ?

Can you make sure it builds, and proceed with 3 ?

4. I do not intend to modify any translation. Only original English strings will be updated, to reflect the same changes as done in the code. I'll try to use text editor commands or a script to automate as much as possible, and to avoid errors. The work to normalize ellipses and quotes in translated strings will be left for translators, according to their respective language rules.

**Comment by vslavik** [comment]
> I do not intend to modify any translation. 
> ...
> The work to normalize ellipses and quotes in translated strings will be left for translators,

As I explained above, loosing translations was — and remains — a major factor in why I didn't "upgrade" the strings. Changing source string while *not* changing the corresponding translation is not acceptable because it provides no indication that the strings need to be updated. And removing their translation (or even fuzzing them, which Crowdin doesn't support well; either doing by updating POT from updated sources) would loose some, potentially highly visible in UI, translations.

The only other possibility is using your PR #339 to add strings to Crowdin, wait until they are translated in all the maintained languages and only merge it then. This didn't occur to me before, but is probably the best way to move forward, even if it will necessarily take more time.

**Comment by vslavik** [comment]
Progress update: 23 languages (of 60) fully transitioned now, a few are in progress (and a few are mostly abandoned localizations that won't stop me from merging this).

**Comment by vslavik** [comment]
Merged now — there's no point in waiting any longer for translations. Thanks for your patience!
