### ISSUE TITLE
Changing tab in plural translations doesn't focus the text field

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#347]
Poedit 2.0beta3
Windows 10

To reproduce:
1.  Open a .po file with a plural translation
2.  Select the plural translation in the list
2.  Focus the translation text field
3.  Press <kbd>Ctrl+Tab</kbd>

Actual: the next plural form tab is focused, having the focus on the tab
Should be: the next plural form tab is focused, having the focus still in the text field

**Comment by vslavik** [comment]
> Actual: the next plural form tab is focused, having the focus on the tab

Actual: Nothing happens. I'm confused: why do you think Ctrl+Tab should do anything, e.g. move to the next plural tab? And how is it even possible that it does anything for you?

**Comment by rillig** [comment]
Pressing Ctrl+Tab is the [traditional Windows way](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Tab_management) to switch the tab in multi-tabbed dialog fields. Therefore I tried it, and it worked for me. Here are the corresponding screenshots:

![2017-03-09 22_01_24-plural po - poedit beta-version lauft am 15 03 2017 ab](https://cloud.githubusercontent.com/assets/3233724/23770627/1178dc74-0514-11e7-8015-5cdf9d8d5871.png)

The Translation field is focused, and you can see the text cursor. Then I press Ctrl+Tab.

![2017-03-09 22_01_47-plural po - poedit beta-version lauft am 15 03 2017 ab](https://cloud.githubusercontent.com/assets/3233724/23770636/1fee2c28-0514-11e7-83de-03f4468bd743.png)

Now the focus has switched to the "Plural" tab.

**Comment by vslavik** [comment]
> Pressing Ctrl+Tab is the traditional Windows way to switch the tab in multi-tabbed dialog fields. 
> Therefore I tried it, and it worked for me.

Again, my confusion was that *this does nothing in Poedit* (and is *supposed to do nothing*). Turns out that [it's caused by Parallels once again](http://kb.parallels.com/en/124069). Once addressed, I can see the behavior you describe.

I don't consider it a problem that Ctrl+Tab doesn't work — this is not the interface it was meant for (and if Poedit ever implements tabs elsewhere than on Mac, it would need to use this shortcut for them). The supported shortcut for tabs navigation is Ctrl+Alt+Left/Right (see the Go menu).

However, the same issue manifests itself in another way: clicking the tabs with mouse leaves focus on the tabs instead of the text control and *that* I see as a problem that needs addressing in the way you say: focus should go to the text control under the tab. Fixing that will also fix Ctrl+Tab.
