### ISSUE TITLE
please consider using a system json library

### ISSUE THREAD

**Issue by LocutusOfBorg** [vslavik/poedit#372]
Hello, I patched the source code to use the Debian available json library
https://tracker.debian.org/pkg/nlohmann-json
```diff
--- poedit-2.0.orig/src/json.h
+++ poedit-2.0/src/json.h
@@ -28,7 +28,7 @@

 #include "str_helpers.h"

-#include "json/src/json.hpp"
+#include <json.hpp>
 using json = nlohmann::json;
```
the library is available directly into usr/include, I don't know if other distros have it too, but some autoconf code to detect it would be awesome :)

**Comment by vslavik** [comment]
> I don't know if other distros have it too

There's a reason why it is the *only* dependency I bundle…

> but some autoconf code to detect it would be awesome :)

I'll be honest: I won't, it's not worth it, because I still have to bundle it, see above.

That wouldn't prevent me from accepting a PR, but in fact, I'm far from sure it's a good idea at all. Consider:

1. Unlike in the case of many other libraries, there's nothing to be gained by using the system version: it's a header-only library, so it's compiled into the executable anyway and no code is shared with other binaries — the primary reason for using system libs, which I get and fully agree with.

2. On the other hand, all the *disadvantages* of a system dependency are present: configure checks to maintain (and deal with differences), compatibility concerns with different versions, harder debugging of bugs if an unexpected version is used.

**Comment by LocutusOfBorg** [comment]
>Unlike in the case of many other libraries, there's nothing to be gained by using the system version: it's a header-only library, so it's compiled into the executable anyway and no code is shared with other binaries — the primary reason for using system libs, which I get and fully agree with.

in case of security issues, debian security team can know (via reverse-dependencies) how many binaries are using that library, upload a fixed version and rebuild them

>On the other hand, all the disadvantages of a system dependency are present: configure checks to maintain (and deal with differences), compatibility concerns with different versions, harder debugging of bugs if an unexpected version is used

well, the configure check might be trivial for some long time, since it is a single include file :)
for the other two points I fully agree :)

**Comment by vslavik** [comment]
> in case of security issues

Fair enough. Embarrassingly I forgot about *this* benefit, despite its arguably even greater importance. Thanks!

**Comment by LocutusOfBorg** [comment]
Thanks to you :) well IIRC Fedora forbids embedded code copies by policy (even in a stricter way than Debian does), so I guess they will take some similar approach as mine...
hopefully the pr is correct enough (even if I really don't understand or speak autoconf)

**Comment by vslavik** [comment]
> Fedora forbids embedded code copies by policy

Wow. To think that Fedora is the reason I considered bundling *more* (because they're still incapable of packaging Poedit fully and disable major functionality due to missing dependencies)…

**Comment by vslavik** [comment]
Closing in favor of #374.
