### ISSUE TITLE
Reduce Boost Requirement to 1.59

### ISSUE THREAD

**Issue by willysr** [vslavik/poedit#375]
Is it possible to downgrade boost requirement to 1.59 instead of to 1.60?

Slackware 14.2 still ships 1.59 and since it's a core package, it will not be updated unless there's a security issue.

if boost 1.60 is really needed, then i have 3 options
- ask boost to get updated in Slackware 14.2 (unlikely to get approved unless there's a strong reason)
- "hack" the configure to use 1.59 and see if it has side effect or not
- postpone updating to 2.0 for Slackware 14.2

any opinions?

**Comment by vslavik** [comment]
No.

**Comment by willysr** [comment]
are there any spesific fixes that only applicable to boost 1.60 and not available on 1.59?

**Comment by vslavik** [comment]
> "hack" the configure to use 1.59 and see if it has side effect or not

As a package maintainer, you are being very irresponsible to even contemplate that. Do you think upstream is so incompetent as to have dependencies *for no reason*? (Thanks for that.) You don't know better than upstream and if you'd break something other than compilation with such cowboy approach, upstream, not you, would get the blame and would have to deal with the inevitable bug reports.

There's a *reason* for this dependency and said reason is actually explained if only you look for it. As a HOWTO, when you are curious about a particular requirement in `configure.ac`, use `git blame`. You can then see that the dependency was bumped in commit bbe8c0ecb68835d3660de1d7d48fea1e2038e66c — which also explains why:

> A modern version of Boost (>=1.60) is required for the executors to work.

As a package maintainer, you should be competent enough to know how to look such information (if you are silly enough to want to mess with the dependencies to begin with). In the future, it would be appreciated if you did your homework instead of asking others to do it for you.
