### ISSUE TITLE
Saving po file in UTF8 drops BOM

### ISSUE THREAD

**Issue by ybaillyvero** [vslavik/poedit#381]
Opening a .po file encoded using UTF8 with a leading BOM (hex EF BB BF).
When saving the file, the BOM is no longer present.
Maybe provide an option in "Preferences / Advanced", or at least write the BOM if it was present in the opened file.

**Comment by vslavik** [comment]
Putting BOM in UTF-8 is [colossally](http://artur.ejsmont.org/blog/content/utf-8-byte-order-mark-bom-strikes-again) [stupid](https://copia.posthaven.com/todays-xml-wtf-utf-8-bom-madness-in-windows-b). Just don't. It's also pointless because no standard/normal/sane PO-generating tool outputs such a thing.

The stupidity and pointlessness of it notwithstanding, such files are *not even valid PO files* and are *not* accepted by standard tools.

```
$ msgfmt -v -c -o /dev/null utf8-bom-abomination.po 
utf8-bom-abomination.po:1:2: syntax error
msgfmt: found 1 fatal error
$
```

So you're looking at it wrong: Poedit is actually (although unintentionally) behaving greatly here and fixes your broken invalid PO file transparently for you. 

> Maybe provide an option in "Preferences / Advanced", or at least write the BOM if it was present in the opened file.

I won't do either. An option to produce broken files is a non-starter, but you are welcome to give transparent, automatic handling a try yourself, though — I would consider a well-written, tested, quality PR. Good luck making GNU gettext tools play ball, though.
