### ISSUE TITLE
JavaScript files are suddengly being parsed

### ISSUE THREAD

**Issue by kAlvaro** [vslavik/poedit#382]
After upgrading to Poedit/2 in a PHP project I'm now getting a bogus string extracted for a JavaScript file:

```
#: Servidor/web/js/jquery-ui.min.js:8
msgid "'"
msgstr ""
```

PHP extractor has the default settings (more specifically, there's `‪*.php` as only extension) and there's no other extractor that has `*.js` among its extensions. It didn't happen with prior 1.x versions I've been using.

I'm using Poedit/2.0.1 on Windows 10 (x64).

**Comment by vslavik** [comment]
If you want to exclude some files from extraction, *exclude* them in Catalog → Properties, that's why the exclusion setting is there (since 1.8 two years ago).

Furthermore:

1. JS files aren't "suddenly" being parsed -- that's since Dec 3, 2014. You must have explicitly deleted the JS extractor, but probably forgot.
2. No, your PHP extractor does *not* have default settings -- if it had, it wouldn't be showing in the list of *custom* extractors that are, by definition, customized.
3. You're not getting "bogus" strings extracted, you're getting strings extracted per your instructions from files you pointed Poedit at.

**Comment by kAlvaro** [comment]
Sorry, I'm kind of confused now..

- Why do extractors have a extension list if gettext will parse all files that are not explicitly excluded?
- Why can I check/unckecked extractors if gettext will use them all anyway?

Sorry, perhaps it's a support ticket rather than an issue report but the Help section does not really explain this.
