### ISSUE TITLE
Missing features in 2.x version

### ISSUE THREAD

**Issue by pedro-mendonca** [vslavik/poedit#383]
Hi @vslavik 

I'm using the Poedit Pro version since 1.x and now I miss a lot some features that disapeared in v.2.x.

Please consider to bring back the following features, as it greatly improve Poedit usability:
- Navigation with keys (e.g.: Pressing the keyboard "C" key to scroll to the next string starting with "C" letter)
- Toolbar button to bulk mark as *Needs Work*.
- Original untranslated strings in **Bold** to make it easier to find when not grouped on top of the list.

Thank you for this great software!

**Comment by vslavik** [comment]
> lot some features that disapeared in v.2.x.

Not a single *feature* disappeared in 2.0. That would be Real Stupid™ of me to do. There were *changes*, some just cosmetic, yes, and it's a human nature to resist change, and I see why you may dislike some of them, but they aren't what I'd describe as "features".

That said, feel free to (in fact, please *do* if required) correct me if I get it wrong below:

> Navigation with keys (e.g.: Pressing the keyboard "C" key to scroll to the next string starting with "C" letter)

This never was a feature, but an accidental side-effect of the control used… on Windows — one, to be perfect honest, that I wasn't even aware of until recently. It doesn't make sense as a feature in Poedit, because this is primarily useful for *picking an entry* from a list, an operation not done in Poedit list.

That said: 2.0 actually (again, accidentally) brings this to macOS. On Windows, wxWidgets' `wxDataViewCtrl` control is lacking it -- but if you feel really strongly about this, you can implement it in wxWidgets and it will bubble down into Poedit. I may eventually get to it myself, especially if more people complain (count so far: 2), but I'll be honest: as something unintentional to begin with, it's not a priority.

> Toolbar button to bulk mark as Needs Work. 

You have the Edit menu for editing operations, including this. Having the toggle in the toolbar was crappy and confusing UI.

(Also, I absolutely can't recommend bulk-ignoring the fact that some translations do *need work* to be good. But it seems highly likely that you know what you're doing, so I trust you do ;)

> Original untranslated strings in Bold to make it easier to find when not grouped on top of the list.

Untranslated items are immediately obvious and noticeable because *the right column is empty*. Plus <kbd>Ctrl+Enter</kbd> navigation gets you right to them. I'm not sure what purpose would making the items bold serve — it won't improve visibility and it does more harm than good when most items *aren't* translate (a more common case). 

---

P.S. I'm always listening at help@poedit.net, but if you want to use the public bug tracker instead, please use it as is common, i.e. one issue per one thing to keep things manageable. TIA!

**Comment by pedro-mendonca** [comment]
Hi again,

>This never was a feature, but an accidental side-effect of the control used… on Windows

A pretty and very usefull side-effect, I must say :)
A use it a lot to jump forward to a section when ordered alphabetically.

> You have the Edit menu for editing operations, including this.

You're right, I'll make use of it in the future.

>it won't improve visibility

Ok, I'll assume this as subjective, different views and I'll probably get used to, but be sure it was noted :)

Thanks for your quick anwser, in the future I'll use the email for these kind of suggestions.
Regards

**Comment by vslavik** [comment]
> A use it a lot to jump forward to a section when ordered alphabetically.

Could you elaborate? E.g. why is it useful to translate in alphabetical order *and* jump around (on prefixes alone, because unlike macOS, Windows doesn't search in the middle of the text or all columns)? Understanding *why* this is so important to you would help me a lot.

**Comment by pedro-mendonca** [comment]
I use both modes of ordering, alphabetical and according source code order.

The strings in sorce code order helps to translate in context (mostly)
Having the strings in alphabetical very usefull to review a translation set and check for consistency of similar strings and check the quality of the translation. In some cases, when you have a dozen of similar strings where just a few words change, this hugely reduces the ammount of time to translate, by identifying the similar translations and quickly copy the common parts.

This is probably is a feature more used by power translators and reviewers, I see myself jumping a lot between alphabetical and source code ordering, because both have their advantages.

**Comment by vslavik** [comment]
Thanks! This is remarkably similar to what the other translator said, so let me reply with what I replied to him too: 

It seems to me that you are in large part (if not entirely) needing this to work around other lacking capabilities in Poedit: 

1. Glossary and/or concordance search support — i.e. offering and checking consistency as a first-class feature.
2. Modern search — i.e. Ctrl+F should show a search bar at the top and then filter the content to only show matching items

Would I be correct in thinking that?

(To be clear, either of these is indisputably much more work to implement than restoring the listview behavior discussed here. So far 3 people complained about this, all of you feeling strongly about it; add the usual silent-to-complaining factor and I think I'm beginning to see the light. Your conscientious workflow may be rare, but this change apparently *is* particularly crippling to it. I'm creating a separate issue for it and will link it here.)

**Comment by naokomc** [comment]
Just commenting to this (already closed and old) issue, to show my interest in glossary feature.
Not opening a new issue because I understand that this is a big task, as you said.

I'm also speaking from someone who uses Poedit for WordPress translation.
Glossary feature will be great for 1) new contributors and 2) paid translators who are not familiar with each locale team's established rules.
I will feel very comfortable recommending Poedit to anyone knowing that the correct glossary terms are always suggested. 
(I'd cry in joy if our glossaries (https://translate.wordpress.org/locale/ja/default/glossary etc.) are always synced & up-to-date for Poedit users)

Even outside of this context, I'm sure glossary can be a very helpful feature for translators since that's a basic and necessary tool for them to achieve consistency.

**Comment by vslavik** [comment]
@naokomc Now that a lot of low-hanging fruit is deal with, this is something I'd like to have in the next major, together with the somewhat related concordance search (#166).

Let's start a new issue for proper glossaries: #551.

**Comment by Ciantic** [comment]
> This never was a feature, but an accidental side-effect of the control used… on Windows — one, to be perfect honest, that I wasn't even aware of until recently. It doesn't make sense as a feature in Poedit, because this is primarily useful for picking an entry from a list, an operation not done in Poedit list.

I used that every day, because I have sparsely translated files, navigating with Ctrl+F is painful. I already downgraded once because of this. This is also a default behavior in many tables and text lists in Windows.
