### ISSUE TITLE
Keybord Shortcut 

### ISSUE THREAD

**Issue by Gotgot59** [vslavik/poedit#391]
Hello, 
I start some translation but i want to switch word without using a mouse. 
Can you explain the way to can add a Keybord shortcut to can be more efficient ?

**Comment by vslavik** [comment]
Please don't misuse this *bug tracker* for vague questions — https://poedit.net/support has clear instructions. Please make sure to read [this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) first, though, because your question is incomprehensible. 

All shortcuts are documented in the menu, as in every other application.

**Comment by Gotgot59** [comment]
Tx for the answer the document is useful and great thinking. 
Ok It was more interesting for the project use : help@poedit.net for asking but truly i just chose remove poedit to my computer to use gtranslator who already have the user functionality of Keyboard shortcut.

**Comment by vslavik** [comment]
Poedit does of course have keyboard shortcuts… sigh.
