### ISSUE TITLE
Change wording of common translation mistake warnings

### ISSUE THREAD

**Issue by lanurmi** [vslavik/poedit#395]
The new Poedit 2.0 feature of warning about "common translation mistakes" is a great addition (and reminds me of PR #75).

However, the current wording "The translation should/should not begin/end with ..." has a bit too unconditional tone. People will be afraid to disobey the computer, when it tells them what should or should not be done. There is no indication the warning is not serious, nor that the "mistake" here is not necessarily a mistake at all.

There are plenty of situations where it makes sense for the translation to have a very different sentence structure than the original. Therefore warnings about e.g. translation not ending in a quotation mark inevitably guide the translators towards sticking the structure of the original English text, which may not be very optimal in many languages.

The warning (if it even needs to be called a warning?) could be rephrased into something that merely states the fact about an inconsistency between the original and translation, and doesn't tell the translator what they should or should not do about it.

**Comment by vslavik** [comment]
> However, the current wording "The translation should/should not begin/end with ..." has a bit too unconditional tone.

Feel free to make or suggest *specific* improvements (although a *much* better time for that would have been before the strings were translated…).

> People will be afraid to disobey the computer,

That's awfully condescending. Have a little faith.

> There is no indication the warning is not serious

There is — it's a **WARNING** for Christ's sake, not an error! 

> There are plenty of situations where it makes sense for the translation to have a very different sentence structure than the original. Therefore warnings about e.g. translation not ending in a quotation mark 

I'm going to call BS on this one. If you change a text from a question into non-question, you messed up and that's exactly what the warning is *for*. This isn't about sentence structure, this is about changing the *meaning* of the string: question or not.

> into something

It's easy to vaguely complain, it's harder to actually come up with better phrasing (case in point: this very issue's vagueness). Space is limited, clarity is important (lots of users with limited English), so is guiding towards fixing the issue.

I don't think the use of "should" is bad here; it's certainly better than anything else *I* was able to come up with. That said, I'm happy to be proven wrong if it makes Poedit better.

**Comment by lanurmi** [comment]
> There is — it's a WARNING for Christ's sake, not an error!

Yes, like "WARNING - Dangerous voltage inside!" isn't an error and can be safely ignored. People familiar with compilers will probably implicitly understand the distinction, but in the real world even a warning is usually something to be taken seriously.

> It's easy to vaguely complain, it's harder to actually come up with better phrasing

Fine. "Inconsistency detected: translation starts with a space". "Difference detected: ...". "Possible mistake: ...".

>> There are plenty of situations where it makes sense for the translation to have a very different sentence structure than the original. Therefore warnings about e.g. translation not ending in a quotation mark

> I'm going to call BS on this one. If you change a text from a question into non-question, you messed up and that's exactly what the warning is for. This isn't about sentence structure, this is about changing the meaning of the string: question or not.

I clearly wrote QUOTATION MARK, not question mark. Please learn to read before calling BS and ranting about something I wasn't even talking about. If you don't know the difference of those words, please see a dictionary.

I am sorry I have insulted you with this suggestion I reported. Your response is incredibly angry considering the pretty neutral tone of my suggestion. Is this the kind of support you also provide as personal support to paid Poedit Pro users, as promised [on your site](https://poedit.net/pro)? For what it's worth, I *have* paid for Poedit Pro.

**Comment by lanurmi** [comment]
![Non-mistakes](https://cloud.githubusercontent.com/assets/5632407/26073770/6a7d5bfa-39b8-11e7-81df-da31eb4bad9a.png)

**Comment by vslavik** [comment]
> People familiar with compilers will probably implicitly understand the distinction, but in the real world even a warning is usually something to be taken seriously.

That may be a valid point (more on it later), but allow me to point out that *you* clearly weren't confused by it, so your objection is so far theoretical (and IMHO a bit too condescending, but I'll be the first to admit I may be a tad too optimistic).

> Fine. "Inconsistency detected: translation starts with a space". "Difference detected: ...". "Possible mistake: …".

These don't take into account the requirements I listed and so are strictly worse (longer, less clear). It also doesn't make sense to change all the warning messages themselves in this way, but if anything would call for tweaking the UI.

> I clearly wrote QUOTATION MARK, not question mark. Please learn to read before calling BS and ranting about something I wasn't even talking about. If you don't know the difference of those words, please see a dictionary.
> 
> I am sorry I have insulted you with this suggestion I reported. Your response is incredibly angry 

You're projecting too much into written word. I'm sorry you feel that way, but re-reading my reply, even with an eye towards your accusations, there simply isn't anything of the sort, neither "angry" nor offended — just a disagreement with your stance. I realize you'd rather I 100% agreed, but this is a *bug tracker* and honestly and directness are important for reaching the best possible solution. I even explicitly said (even though it goes without saying) that I'll merge improvements that prove me wrong.

And yes, I made a mistake (although the larger point still stands), sorry. You know full well it was a brain fart, so your offense over the imagined tone of my reply is particularly rich in irony given the above-quoted paragraph.

Regarding the Pro version, in addition to what I wrote above, you didn't ask for support, but submitted a bug to the Open Source version's bug tracker. My records also indicate your Poedit Pro 2 (don't know about V1) license is a (well-deserved) translation contributors' one -- but neither of that is relevant here, so not sure what that was about.

Anyway, let's stick to technical stuff, shall we?


You raise two valid issues — neither of which is what the subject of this bug says and *neither of which would be fixed by the proposed banishment of the word "should"*:

1. The meaning of a *warning* may not be clear to some users (especially when there are no errors to see the distinction in their representation).
2. Some warnings have too many false positives (punctuation classes).

Regarding the first point, the appropriate solution is to handle this in UI. Either by prefixing *all* warning messages with such an indicator or adding an explanatory info button, having it explained in a brief working screen tutorial etc. Perhaps a status bar summary of errors+warnings would drive the meaning home, e.g. with "QA issues" label. Since the word "warning" isn't actually used in the UI yet, there's room for this.

Regarding the second, such things take fine-tuning and there already were changes based on various users' (none of who misunderstood the concept of warnings, BTW) productive input: 51219cf62a35f5e49e7752ffe2323f1fa9933df9, 2061d79521a3252115a8c6947b04894083d365e9 or e864e7e6f903a8deb334ed890d7f62b0a100c911.

You screenshot example nicely demonstrates that punctuation checks need to be limited to a few whitelisted cases that the warning was *meant* to cover: e.g. `:!.` or `([])` *when used as both leading and trailing*.

To reiterate, this is *not* about poor wording of the warning, but about *false positives* that should be eliminated.

By the way, the screenshot also nicely shows what a gray area this is. While the warnings Poedit gives you are *wrong*, it's arguably not wrong to *flag* these entries. No.2 takes liberties with the text and would ideally be flagged (but is too hard to detect to be worth it, I think). No.3 is clear: the warning worked here (there may be reasons to stick to ASCII rendering). Changing the quotes style is something a warning should probably be made about too, at least for some languages...

**Comment by lanurmi** [comment]
>> People familiar with compilers will probably implicitly understand the distinction, but in the real world even a warning is usually something to be taken seriously.

> That may be a valid point (more on it later), but allow me to point out that you clearly weren't confused by it, so your objection is so far theoretical

I've been using various compilers for 20 years and gettext for 15 years, both from a translator's and developer's perspective. It would be silly of me to assume the average Poedit user has a similar background.

> Regarding the Pro version, in addition to what I wrote above, you didn't ask for support, but submitted a bug to the Open Source version's bug tracker. My records also indicate your Poedit Pro 2 (don't know about V1) license is a (well-deserved) translation contributors' one

Yes, indeed I didn't ask for support because I didn't pay money for my Pro 2 license, and the issue is specific to V2. However, I did pay for V1; you can check your records for order id POE150403-5746-82192. Not that it's relevant, no.

Also, is it your policy to reveal in public who has acquired a Poedit license, and what kind of license? Granted, it is not very sensitive information, and you do not explicitly promise privacy anywhere on the order page.

> your offense over the imagined tone of my reply

The imagined or perceived tone of your reply matters, because that is all the reader has available when communicating by text. And after all, you used capital letters, exclamation mark and the expression "for Christ's sake" in your reply. Do you honestly feel those are considered entirely neutral to use, and there is no risk of anyone perceiving them as anger?

> To reiterate, this is not about poor wording of the warning, but about *false positives* that should be eliminated.

I'd argue that no matter how you improve the checks, there will always be false positives in some rare cases. And that is fine, because the nature of these checks is somewhat inconclusive.

> While the warnings Poedit gives you are wrong, it's arguably not wrong to flag these entries. 

Finally something we completely agree upon!

> No.2 takes liberties with the text and would ideally be flagged (but is too hard to detect to be worth it, I think).

IMHO changing the word order is not about "taking liberties", it is about making a good translation. Blindly sticking to the English word order just makes some translations really awkward in other languages. There can be a reason why e.g. the translation should end in a quote if the original does, but that's rarely the case, and certainly not a case in any of the examples in the screenshot. And yet, I agree it was correct to flag those, but I would myself call them something less severe than a warning; e.g. a "note", or "information".

> No.3 is clear: the warning worked here (there may be reasons to stick to ASCII rendering).

We agree that it was correct to flag "(C)", but as for reasons: if something relies on the text being ASCII, arguably it should be ensured on the code level, and not left up to the dozens of translators to decide.

> Changing the quotes style is something a warning should probably be made about too, at least for some languages...

I don't think ASCII quotes are the proper quote style for writing any language; not even English. Using the proper Unicode quotes should not be discouraged. For example, all the GNU software aims at using Unicode quotes; much of that is even automated.

**Comment by vslavik** [comment]
> It would be silly of me to assume the average Poedit user has a similar background.

Sure. But, again: in practice, this doesn't seem to be a problem. In practice, people don't seem to be confused by it so far.

> Do you honestly feel those are considered entirely neutral to use, and there is no risk of anyone perceiving them as anger?

Well, yes…? It's an expression of some level of exasperation, e.g. over a self-contradictory claim (warning with a warning icon gives no indication it's a warning). That's it.

> Also, is it your policy to reveal in public who has acquired a Poedit license, and what kind of license? 

No. As a reminder, *you* brought it up. I censored all mentions of it now (including, shortly, this one).

> IMHO changing the word order is not about "taking liberties", it is about making a good translation. 

Changing word order is, indeed, often *necessary*. I was referring to the extra added quotes.

> if something relies on the text being ASCII, arguably it should be ensured on the code level

E.g. code written for (not necessarily modern) terminals doesn't *explicitly* require ASCII, it's an implicit need, reflected in the source strings. For a developer, it is IMHO reasonable to assume that translators will translate faithfully and preserve tone/style/idiosyncrasies.

> I don't think ASCII quotes are the proper quote style for writing any language; not even English. 

Agreed. But *if the source text* uses ASCII ones, again, for reasons that may not necessarily be obvious to a translator, there's an argument to be made that so should the translation to preserve the style. 

But here I was referring to something else again: the change from double to single quotes, changing the style. I know I wouldn't appreciate that in Poedit as the developer and would much prefer bug reports asking to correct source strings (an effort currently underway in Poedit, BTW, that is time-consuming due to the sheer number of translations).

**Comment by lanurmi** [comment]
>> Do you honestly feel those are considered entirely neutral to use, and there is no risk of anyone perceiving them as anger?

> Well, yes…? It's an expression of some level of exasperation, e.g. over a self-contradictory claim (warning with a warning icon gives no indication it's a warning). That's it.

Okay, perhaps a cultural difference in communication then. I guess we'll just have to live with it.

>> Agreed. But if the source text uses ASCII ones, again, for reasons that may not necessarily be obvious to a translator, there's an argument to be made that so should the translation to preserve the style.

How many real-world projects (utilizing gettext) do you know that use anything beyond ASCII in their source strings? I can't think of any, but I sure can think of many that use gettext as a kind of abstraction layer that keeps Unicode characters out of the actual code base, and it is the very idea that translators use the correct Unicode characters when appropriate. That "(C)" -> "©" line in the screenshot is an example of that.

> But here I was referring to something else again: the change from double to single quotes, changing the style. I know I wouldn't appreciate that in Poedit

If we are talking about something like examples of command lines, where the actual quote character matters, then sure that needs to be preserved.

Beyond that, quote style is a property of the orthography of a language, not a property of a piece of software. In Finnish, for example, there are a lot fewer correct use cases for single quotes than in English. Using single quotes in the translations shown in the screenshot would not be properly written Finnish. And as you surely know, in some other languages the quotes would need to be e.g. » «.

**Comment by vslavik** [comment]
> How many real-world projects (utilizing gettext) do you know that use anything beyond ASCII in their source strings?

A *lot*. Not just Poedit (to name the elephant in the room), but all of GNOME for example.

> but I sure can think of many that use gettext as a kind of abstraction layer that keeps Unicode characters out of the actual code base

Nope, a major flaw with that it doesn't provide proper typography for English (without extra effort with fake translations).

**Comment by lanurmi** [comment]
As a sidenote to our previous topic:
>> Also, is it your policy to reveal in public who has acquired a Poedit license, and what kind of license?

> No. As a reminder, you brought it up. I censored all mentions of it now (including, shortly, this one).

No. As a reminder, I asked a general question about the support that paid Pro users receive. I didn't say what kind of a license I have, or whether I have any kind of license. *You* brought it up and revealed to the public that I indeed have a Poedit license.

>> but I sure can think of many that use gettext as a kind of abstraction layer that keeps Unicode characters out of the actual code base

> Nope, a major flaw with that it doesn't provide proper typography for English (without extra effort with fake translations).

Err, what is "Nope" supposed to mean here? That because using gettext as an abstraction layer is a bad idea in your opinion, it means nobody is using it as an abstraction layer? Even though I specifically said I know many such projects.

**Comment by vslavik** [comment]
> I didn't say what kind of a license I have, or whether I have any kind of license.

You wrote that, and I quote from GitHub notification email, "For what it's worth, I have paid for Poedit Pro." Until then, seeing that you used the OSS tracker, I assumed the opposite. The previous implied accusation in public that I somehow mistreat a paying customer was bad enough (and the sole reason I felt the need to correct the record), but this is outright untruth. It seems there's just no satisfying you and anything I do is wrong :(

I don't think there's any point in continuing here. The issue degenerated into being completely unactionable with independent issues and tons of off-topic talk, so I'm closing it now. I'll address the false positives and new issues should be filled for specific UI improvements. If you wish to talk about anything else further, please use email to help@poedit.net.
