### ISSUE TITLE
Poedit extractor doesn't fetch WordPress page template name

### ISSUE THREAD

**Issue by fxbenard** [vslavik/poedit#404]
```php
<?php
/**
 * Template Name: Name Template
 *
 * The template for the name page.
 *
 * @package Theme
 * @since Theme 1.0
 */
```
This is extracted by GlotPress and Grunt.

**Comment by fxbenard** [comment]
`<?php
/**
 * Template Name: Name Template
 *
 * The template for the name page.
 *
 * @package Theme
 * @since Theme 1.0
 */

`
This is extracted by GlotPress and Grunt.

**Comment by vslavik** [comment]
Poedit has support for extraction from plugins and themes, not templates, and "template" doesn't seem to be a translatable WordPress entity as far as I can tell, so I'm not sure just what exactly is it that you're asking for here.

If you think that's something that should be supported, please provide explanation of how that should work, how it relates to translation, themes or plugins. Some pointers to relevant WordPress documentation would be nice too...

P.S. Please *attach* files instead of pasting mangled, corrupted copies as comments. Or at least paste into code blocks, as I edited your comment.

**Comment by vslavik** [comment]
In short: what am I missing here?

**Comment by fxbenard** [comment]
Hi Vlasick, it's supported by translate.wordpress.org

Download https://wordpress.org/themes/hestia/ for example and use your extractor and compare it to this one.

https://translate.wordpress.org/projects/wp-themes/hestia

3 strings missings

**Comment by vslavik** [comment]
> Hi Vlasick

I've been called *names* in the many years past, by people having trouble with Slavic names, but this particular mangling is something truly special 😂 Thanks for making my day.

Thanks for the pointer, I see what you mean now — apparently this part of a theme can be visible in (potentially localized) admin UI. Exhaustive details at https://developer.wordpress.org/themes/template-files-section/page-template-files/

Will be fixed in 2.0.3.

**Comment by fxbenard** [comment]
Happy if I made your day "Vslasick". hahaha

Thanks for the fix.

**Comment by alleknalle** [comment]
Hi Vslavik,

how does this actually work? When I'm creating .POT file from my theme I don't see the template names in there?

I've got a template file which starts with:
``

**Comment by vslavik** [comment]
@alleknalle This is a Pro feature.
