### ISSUE TITLE
Safari indention not working

### ISSUE THREAD

**Issue by sakuraiwanaga** [vslavik/poedit#424]
As I am using Poedit for `default.po`, recently I have notice that the new line will now work on safari browser.

I have used lots of indention code.
Ex. `\n, \r\n, <br>, PHP_EOL;`

```
msgid "test"
msgstr ""
"This is the sentence part."
```

Do you have any solution to make the safari work too?
Thank you.

**Comment by vslavik** [comment]
You seem to be deeply confused about how HTML, WordPress, PHP or translations work. Please read WordPress documentation **NOW**. They have very good handbook for theme/plugin developers-beginners like you (I'm guessing that this is about WP, because it would be kinda typical; but you didn't say).

Poedit is a translations editor and PO/MO files contain *translations:* just dumb replacement of an English string with a translated one, with *no* understanding of the content or formatting. It would be technically impossible for Poedit to produce some magical thingies in place of strings that could somehow break Safari. You have bugs in your code and are not properly doing the output. Which is why you need to read WP docs. If you're unclear on how line breaks and such work in HTML, read up on HTML basics too.

Also, `default.po` is something people who didn't read the docs do in place of a proper POT file (as explained in detail in WordPress docs as well as in GNU gettext manual). Don't do it.

**Comment by iwanaga-sakura** [comment]
Thanks for the reply!
I will read the docs
