### ISSUE TITLE
Relative paths to sources are not set correctly

### ISSUE THREAD

**Issue by amorphine** [vslavik/poedit#425]
Poedit 1.8.7.1
When I create a new po file the program asks me to save it before I can add sources. 
I save it to

>  /var/www/project/wp-content/themes/minima-lite/langs

After saving base bath is set to the path po file is located in.
When I try to add 

> /var/www/project/wp-content/themes/minima-lite/

 as a source folder therelative  path becomes '.' but it should be '../'
The only way to fix it is to add any subfolder like 

> /var/www/project/wp-content/themes/minima-lite/subfolder

so it changes the base path and relatives paths become correct

**Comment by vslavik** [comment]
The latest version is 2.0.3. Even in 1.8 series, the latest is not .7, but .13. Please don't waste developers' time by submitting bug reports against ancient versions and *always* verify in the latest version first.

That said, relative paths of course do work correctly. You didn't provide any reproduction instructions that could be followed, so I can only guess this is some confusion on your part. If you believe otherwise, please provide actual description of the problem (your description is very confusing and unclear) reproduction instructions, with actual files. Please read [this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) first too.

**Comment by amorphine** [comment]
>The latest version is ....
For the user the lates version is a version from their repository usually. Github threads often appears as Google search results - so that hack I found may save someone's time.

**Comment by vslavik** [comment]
> For the user the lates version is a version from their repository usually.

If you're too entitled to follow normal OSS practices, then file bug report with your distribution (none of which ship this old version in their respective current versions either). Your expectation that upstream will provide you with free support for *years old* versions is quite simply unreasonable.

>  so that hack I found may save someone's time.

You didn't describe any hack and this confusingly (non)described issue is certainly not going to help anyone — on the contrary.
