### ISSUE TITLE
Poedit not finding strings because of //comments present

### ISSUE THREAD

**Issue by jonbhanson** [vslavik/poedit#433]
Hello,  I had trouble with Poedit not finding translation strings in my source file.  I verified that the __ keyword was in my catalog properties, and the source file was in the source paths of the catalog properties.  Then I found this solution: https://stackoverflow.com/questions/14486914/poedit-does-not-parse-all-strings-in-php-files-in-path
One answer suggested that the comments that begin with the double slash // were preventing poedit from finding the translation strings.  I changed all my // comments and instead used /* comments */ in my PHP source.  This fixed the problem.  So, it seems that there is indeed a bug when // comments are used.  Thanks for the great product, though!
Jon

**Comment by vslavik** [comment]
Sounds like utter nonsense to me. And you provide *zero* evidence for your extraordinary claims, just some vague hand-waving with no specifics.

Have a hard look at your own code and assumptions, instead of cargo-culting some unsubstantiated years-old nonsense from SO. Don't make it your first assumption that you are perfect and gettext devs (an experienced bunch with literally *decades* of experience) would make mistakes in something as basic as comments parsing

If you do believe there's a bug, kindly read `SUPPORT.md` -- which you were asked to do when you created this issue, but apparently decided that following instructions is beneath you -- and proceed accordingly.
