### ISSUE TITLE
Failure merge between two file .po

### ISSUE THREAD

**Issue by alessandromacchi** [vslavik/poedit#442]
HIi!
I'm using the latest version of Poedit, I don't find nothing that can help on _GNU gettext manual_.
I'm trying to do a merge between this two file. I open the first.po in Poedit then I go to **Catalog** and select **Update from POT file**, select **PO files** and last I choose the second.po, but the first.po became a copy of second.po losing all its content.
The problem, I think, is second.po because I create this file through a script in python, that extract from file with .tiwg extension and after write header and all things in second.po,  with **open("second.po", "w")**. 
I already try to do the merge with **msgmerge**, that don't work also. 
Why is there this behavior? How can I fix the second.po or are there other solutions?

I'm using the lastes version of Poedit, on a VirtualBox that have UbuntuMate 16.04 all running on Windows 10
[file_po.tar.gz](https://github.com/vslavik/poedit/files/1380320/file_po.tar.gz)

**Comment by vslavik** [comment]
> Why is there this behavior?

That is explained, in extreme detail, in the manual that you did not read (if you did, you would find your answers there).

You also, despite being explicitly asked to do it, twice now, *still* didn’t read the instructions.

This is not a place for asking question, nor for providing personal assistance with reading gettext docs. This is a *bug tracker*. It’s only purpose is *reporting bugs*. Please don’t abuse it.

Read the gettext manual. It explains everything.

**Comment by vslavik** [comment]
Also, for crying out loud, if you create a third duplicate issue, as you did, while still ignoring everything you were told, I will have no other choice but to block you. So don’t.

**Comment by alessandromacchi** [comment]
I don't reopen a third issues. I'm sorry for the First issues, I don't read the rules, but the second for my opinion is quite explicative, if isn't I'm sorry.

I read twice the gettext manual but I don't find my problem. Please, if you know what or where It is on the manual, Can you tell to me? Thank you.



Il giorno 12 ott 2017 10:37 PM, Václav Slavík <notifications@github.com> ha scritto

Also, for crying out loud, if you create a third duplicate issue, as you did, while still ignoring everything you were told, I will have no other choice but to block you. So don’t.

**Comment by vslavik** [comment]
> but the second for my opinion is quite explicative, if isn't I'm sorry.

You completely ignored 4., mostly ignored 2. (I'm pretty sure you did not in fact read the entire gettext manual *twice* in less than 15 hours…) and ignored the introductory section explaining that you shouldn't ask questions here, but file only Poedit bugs. Since you say you used `msgmerge` with the same results, you *know with 100% certainty* that this is not a Poedit bug — yet you file it as one.

>  Can you tell to me?

You fundamentally misunderstand how updating / `msgmerge` work in gettext. It is beyond the scope of bugtracker (or reasonable support expectations) to provide you a detailed personal explanation of matters well covered by the available documentation.

msgmerge, together with other basic gettext concepts, is explained in the manual very well. Heck, there's enough of explanation in msgmerge's manpage (which is also part of the manual and which would be an obvious thing to read if you don't get correct results while using it):
```
MSGMERGE(1)                                          GNU                                         MSGMERGE(1)

NAME
msgmerge - merge message catalog and template

SYNOPSIS
msgmerge [OPTION] def.po ref.pot

DESCRIPTION
Merges  two  Uniforum style .po files together.  The def.po file is an existing PO file with transla-
tions which will be taken over to the newly created file as long as they still match;  comments  will
be  preserved,  but extracted comments and file positions will be discarded.  The ref.pot file is the
last created PO file with up-to-date source references but old translations, or a  PO  Template  file
(generally  created by xgettext); ANY TRANSLATIONS OR COMMENTS IN THE FILE WILL BE DISCARDED, however
dot comments and file positions will be preserved.  Where an  exact  match  cannot  be  found,  fuzzy
matching is used to produce better results.
```

There's no bug here. Both Poedit and `msgmerge` are working exactly as intended. Apparently, you're expecting them to do *something* other than that, but you don't even actually say what that might be...
