### ISSUE TITLE
Allow to input personal Google Key

### ISSUE THREAD

**Issue by teolemon** [vslavik/poedit#444]
I'm a happy pro user, and I'd be even happier if you could allow me to input my personal Google Key for the Google Translation API, including a choice to choose the new neural version (more expensive).

Also, I'd like to be able to pre-translate from the Google Translate Neural API

https://cloud.google.com/translate/docs/premium

**Comment by vslavik** [comment]
Poedit Pro does not use (only) Google Translate, so no, not going to happen, sorry.

**Comment by vslavik** [comment]
It occurs to me that I should have commented not on what this issue asks, but what I think you're *really* asking about — sorry about my overly narrow reading.

I'm aware that MyMemory (used by Poedit) is no longer on par with the latest Google Translate (which, by the way, doesn't have a premium edition anymore for some time, see your link, it's now standard quality). MyMemory guys are aware of it too [and are working on it](http://www.modernmt.eu). Independently of that, I'm looking into improving the quality, particularly of the human-submitted (rather than machine) translations. You should begin to see improvements in Poedit 2 in the coming weeks/months.

**Comment by teolemon** [comment]
The core issues, and I should have been more clear about it, are the following:
-The human suggested translations are somewhat puzzling, indeed.
- MyMemory sometimes fails to provide a machine translation. 
- I was assuming they came from the V1 while v2 is available.
So my feature request was all about:
- reduce the price / avoid the V2 prise hike for you by enabling the option to shift the API payment to us.

**Comment by vslavik** [comment]
Starting with 2.1 (now [in beta](https://poedit.net/download)), Poedit ditches MM for machine translation and uses a combination of [DeepL](https://deepl.com) (if your language is supported, that's what you want to use — [better](https://www.deepl.com/quality.html) than Google's, even w/ NMT), Google Translate and Microsoft Translator.
