### ISSUE TITLE
Option to disable useless warnings?

### ISSUE THREAD

**Issue by creshal** [vslavik/poedit#445]
Warnings over inconsistent capitalization (can be due to different capitalization rules), changed line endings (can be due to localization switching a . for ! for emphasis), and all the others are just getting in the way and creating useless noise. Please add a way to disable them globally.

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue). Instead of vaguely complaining about how something you use for free is "useless", you could have actually reported *specific* issues if there are any legitimate false positives. Or, you know, provide a PR yourself. 

>  changed line endings (can be due to localization switching a . for ! for emphasis),

That sort of objectively bad translations is *exactly* why the warnings are in there…

**Comment by creshal** [comment]
> Instead of vaguely complaining about how something you use for free is "useless", you could have actually reported specific issues if there are any legitimate false positives. Or, you know, provide a PR yourself.

Or could just have downgraded to an older version without 'em, or write my own POEdit clone with blackjack and hookers, yadda yadda. 

> That sort of objectively bad translations is exactly why the warnings are in there…

I can come up with plenty of other examples – date format strings, e.g., where different "line endings" aren't even line endings to begin with, and just formatting characters. Or cases where line endings are changed for all locales, including the source locale, without updating the source (because it's from an external provider, e.g.).

> you could have actually reported specific issues if there are any legitimate false positives

Since you seemed to ignore various other cases reported on Stack Overflow and elsewhere, I figured this was the easiest solution. 

Additionally, so far I haven't found a way to reduce all the different cases to detectable conditions, and IMO it'd be a waste of (your) time to play ping-pong to get all the dozens of cases nailed down I've ran into just this afternoon alone, without having a single case where they actually helped correcting a mistake… Globally disabling them is probably the easiest solution.

**Comment by vslavik** [comment]
Please find some other venue for such inappropriate comments. This is not the place.

> Since you seemed to ignore various other cases reported on Stack Overflow and elsewhere,

As shocking as it may seem to you, I really don't read *the entire Internet*. The direct feedback I *do* have is generally appreciative of them (a few freeloading yet entitled a-holes notwithstanding) and *constructive*. 

Again, you are welcome to contribute something back and submit a PR if you can you can improve something. So far the only specifics you provided point to the warning doing its job of discouraging crappy translations. If anything, your rant serves as an argument *for* having them, because you apparently think it's OK for translations to significantly change UI's tone — it's not, and it's correct that Poedit (notice the spelling, BTW) warns about them.

For now, I have no plans to allow globally disabling the QA checks. I may reconsider at some point, but right now, *I* won't be making such changes. Again, others — such as you — are welcome to have a go at it.
