### ISSUE TITLE
[Feature Request] Edit source string in place

### ISSUE THREAD

**Issue by allansun** [vslavik/poedit#446]
In my project I have developers from all over the world. Not all of them a fluent in English. Sometimes they make some funny mistakes. 

It would be so nice if I could edit the source string in POEdit and get them updated in the source code directly.

**Comment by vslavik** [comment]
There's exactly one place where it's technically possible or makes any sense to edit source strings: *in the source code*.

Please do read the GNU gettext manual (it's linked from the Help menu) to understand basic concepts behind gettext. You have a fundamental misunderstanding of how gettext works.


P.S. Name's Poedit, not "POEdit".

**Comment by allansun** [comment]
Hi @vslavik 

Thanks for your prompt reply.

However I don't quite understand what I got wrong with the basic concepts behind gettext.

For example I have a phrase in my source code (example from my post above) 'Not all of them **a** fluent in English'. It suppose to be 'Not all of them **are** fluent in English'. 

When I review the translations I found this is a mistake so want to fix it in the source code.

Obviously we don't want to have an English translation. So to correct this problem I have to go through the translation list in PoEdit, right click on it, click the reference, and then click 'Open in Editor' (Sublime in my case), CTRL+G and input the line number which I had to remember, to navigate to that particular line, and then correct the mistake in source code. Save the file, switch back to PoEdit,   which had already lost focus on the 'reference' window, so I have to click that window again to close it.

In my currently project I have almost 2000 strings to go through, some of them appeared in multiple files so I had to repeat the previous procedures again and again. Hence I proposed this feature request. Am I missing anything here?

Sorry for mistake between POEdit and PoEdit.

**Comment by vslavik** [comment]
Ah, you want to edit multiple files, some of them source, *simultaneously*. That's so bizarre to me that it didn't even occur to me that you could mean that, even though now that you explained it I can see how your original text should have been read that way — sorry.

I suppose that has some use, but would also be incredibly fragile (multiple files, possibly in formats unknown to Poedit, properly handling quotation etc. etc.) — for what is extremely limited use. I'm leaving this closed, because *I* will certainly not implement such capability for the above reasons, at least not in foreseeable future. But if you feel this is important, please do give it a try and submit a PR, I'll be happy to accept such contribution and help you out with getting it merge-ready.
