### ISSUE TITLE
Poedit producing invalid .mo files

### ISSUE THREAD

**Issue by ValerioBulla** [vslavik/poedit#447]
I am getting a weird issue where compiling .po files with Poedit results in invalid .mo files.
The files won't work with gettext, and msgunfmt returns an error when trying to run ( file "filename.mo" is not in GNU .mo format).

Manually compiling the very same .po file using the tools bundled with Poedit (located in GettextTools\bin) produces a valid file, so I figured it must be Poedit that's causing the issue.

This happens with every .po file I tried creating. I am using latest Poedit 2.0.4 (downloaded from the official website) on Windows 10 x64.

**Comment by vslavik** [comment]
Please follow the [guide](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) you were asked to read when you created this issue. You seem to be making the assumption that I am so incompetent that compiling MO files — the single most important thing in Poedit — doesn't work for *anyone*. The reality is that if you're having some issue, it's with something *specific to you or your computer* and you need to describe these specifics:

1. Please attach a sample file. It's impossible to do anything about a bug accusing Poedit of creating "invalid" file with no sample demonstrating just in what way it is "invalid".

2. Ditto for a PO file you compiled it from. You say "every file I tried", but I can't know *what* files you tried, and it certainly weren't all POs in existence. It's entirely possible there's something wrong with all POs you have.

3. Please show the manual command that succeeded. Because Poedit does nothing else than invoke `msgunfmt` to make the compilation.

4. Please provide a description of how you named the file, in what directory (full path) you put it, on what filesystem and/or disk. Make sure step 3. above is invoked — and works — *in the same location*.

Right now my only guess is that step 3 was either with a different PO or in a different location and you have some permissions problem. That could of course be completely wrong, though, hence the need to provide details.

Thanks!

**Comment by ValerioBulla** [comment]
Well, first of all, I apologize if it sounded like I was accusing you or your work, that is not what I meant at all, I was just trying to describe the issue.

That said, details:
I created the .po file directly from Poedit, extracting the strings from a source .php file.
The full file path is D:\Vagrant\Project\src\locale\it_IT\LC_MESSAGES\it_IT.po
The project folder is a Vagrant box shared folder, but the machine was not running. The file system is NTFS.

The manual command that successfully compiled the file was `msgfmt -o it_IT.mo it_IT.po`, I ran it from a regular cmd window in the LC_MESSAGES folder containing the .po file, after putting the bin folder containing the gettext executables in the Path variable.

I am attaching the .po file I created with Poedit, as well as the .mo file generated from within the program.
Thanks!

[files.zip](https://github.com/vslavik/poedit/files/1441537/files.zip)

**Comment by vslavik** [comment]
> accusing you or your work, that is not what I meant at all

Well, you did file the bug here and not with Vagrant or Windows, no?

> The project folder is a Vagrant box shared folder

Did you try doing the same in *another*, normal, location, such as in your documents folder. If you did not, please do (incl. providing the resulting files). That's the most sensible explanation. I'm guessing the difference with manual invocation is that Poedit puts the file in a temporary location first and then moves it. If you look at the file, *something* is messing with it:

<img width="954" alt="screen shot 2017-11-03 at 17 11 49" src="https://user-images.githubusercontent.com/145881/32384206-6bd0cc38-c0ba-11e7-851a-23c62bcccac3.png">

Poedit calls `msgunfmt`, then moves the file, without touching the content. Some process that handles shared folders is in charge of moving data around, so it's reasonable to expect that it reads the files and perhaps does some ill-advised attempt at conversion.

> but the machine was not running

I'll venture a guess that while a specific VM may not be, some Vagrant bit is.

**Comment by vslavik** [comment]
> ValerioBulla closed this 10 minutes ago

A word of explanation would be appropriate, methinks...
