### ISSUE TITLE
Ability to disable "The translation should not end with"

### ISSUE THREAD

**Issue by mrsombre** [vslavik/poedit#448]
We are using macros system for translations, ie `$api.example-response$`. When translation is with a dot at the end we got "The translation should not end with" error. Even when ""Check spelling" is disabled.

Can we have an option to disable this feature as of it completely annoying.

**Comment by vslavik** [comment]
> Can we have an option to disable this feature as of it completely annoying.

That's a curiously strong wording about a tool you use for free...

You misuse gettext in a way that it is explicitly not meant to be used (by not using English as the source text). It is therefore not all that surprising that tools — and by far not only Poedit and not only this one feature — will give suboptimal results. That's to be expected. You'll find that if you use gettext as it is meant to be used, everything will work more smoothly. 

If it is so "completely annoying" to you, do something about, submit a good quality PR. But *I* am not inclined to change it just because you use gettext in a weirdly masochistic Java-infected way.

**Comment by mrsombre** [comment]
I'm sorry if my words confused you somehow. BTW just for a discussion:

> by not using English as the source text

1. If we would change English source in some case (i.e. typo or our redactor change text a bit without changing its meanings) than we should change all occurrences of this source across project and change all translations (because source key changed).
2. There are a lot of places in project where we have complete paragraphs to translate, it's not very comfortable to see long text as source key.

We have used English as source but at some point we can't deal with this problems and switch translation to macros system which is pretty fit to our needs.

I just ask to add **an option** to disable errors like wrong case and wrong string ending. Is it really hard?

**Comment by vslavik** [comment]
Again, you are using gettext in ways that it isn't meant for (that includes your point 2). Please don't add arguments about this fact here, it's waste of time.

> which is pretty fit to our needs.

Your complaining in issues here would indicate that it is not "fit"… but of course, you apparently blame Poedit, not yourself, for the unfitness.

> I just ask to add an option to disable errors like wrong case and wrong string ending.

"Just add an option" is one of the stupidest arguments in software design. Among other things, it _doubles_ the number of configurations that need to be tested.

> Is it really hard?

I guess it is, because you didn't do it and didn't submit a PR, did you? I can't say I appreciate your attitude: you act as if I owed you accommodating your fringe requirements to fix your self-imposed problems. That is really not the case. I may consider your contributed code, if it's good and you have solid arguments for including it, but I don't owe you doing that work for you — _especially_ with that entitled attitude of yours.
