### ISSUE TITLE
Split screen for two translations

### ISSUE THREAD

**Issue by mrsombre** [vslavik/poedit#449]
It would be great if it will be a feature to open more than one PO files at a time. One just for reference. IE when we translating to Chinese we can look at the English translation.

**Comment by vslavik** [comment]
Don't misuse gettext (as evidenced in #448) and you won't need this as much.

Auxiliary translations make sense in some limited situations (*not* the one you mention, but for pairs like Czech-Slovak or Russian-Ukrainian). They're planned, but not a priority due to limited usefulness. If it's very important to you, contribute.

**Comment by jeblad** [comment]
This would be useful for all the Scandinavian (North Germanic) languages, and in particular the two Norwegian forms Bokmål and Nynorsk. It is now more efficient to open the two files in GNOME Edit and copy-paste, occasionally translating by using the extension for Apertium, than using poedit.

**Comment by jeblad** [comment]
Not sure why my comment was marked as duplicate. I pointed out why this kind of feature is useful for Scandinavian languages. They are very closely related.

**Comment by vslavik** [comment]
Closing: Will pursue one of the referenced approaches instead.
