### ISSUE TITLE
Invalid PO files with newlines within references aren't parsed well

### ISSUE THREAD

**Issue by magistere** [vslavik/poedit#451]
Hello Václav,

I've noticed that PoEdit damages file contents while translating LyX's PO (http://lyx.org/). When you open `1.po` from attached ZIP archive and then just save it without any modification, it becomes `2.po` with loosing information.

PoEdit 2.0.4 on Windows 7

[po.zip](https://github.com/vslavik/poedit/files/1548893/po.zip)

**Comment by vslavik** [comment]
*If* by "loosing information" you mean loosing some reference lines (you don't actually *say,* despite the importance), then I would say it follows the age-old [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) principle. Your lines contain `0x0D` characters (DOS newlines) in them instead of whitespace. Apparently you expect such misplaced characters to be interpreted as plain spaces, even though they are not. A more reasonable interpretation would be as, well, a *newline*, which makes your PO files syntactically invalid.

It's a small miracle Poedit handles this garbage as well as it does. If you think there's a room for improvement, by all means, submit a PR, but as far as I am concerned, best effort is enough for invalid files like this one. And loading them and only loosing syntactically invalid parts sounds good to me.

> PoEdit 2.0.4 on Windows 7

(The name's "Poedit", did you not notice that your weird spelling is not used anywhere? Also please follow the issue creation instructions next time and ensure you have the latest version — you don't — and use meaningful descriptive subjects.)

**Comment by magistere** [comment]
Thanks for fast response and sorry for misspelling the name of Poedit. So the problem is invalid input file and I'll forward this issue to LyX's team.

**Comment by donovaly** [comment]
I created the po file using msgmerge:
https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html
I use msgmerge version 0.18.1. This is an old version and has of course bugs but saying it creates garbage is a bit harsh.

**Comment by vslavik** [comment]
@donovaly Please observe that I said no such thing. I said the input PO file was garbage — which it indisputably is:

<img width="540" alt="screen shot 2017-12-12 at 08 54 412" src="https://user-images.githubusercontent.com/145881/33873210-637b0c50-df1a-11e7-841f-94a35332650d.png">

GNU's `msgmerge` is a high quality respectable tool and the de-facto standard for POs manipulation; Poedit uses it too. I have never seen it produce corrupted output. I have *also* never seen it insert stray `0x0D`s all over the place.

You need to look further than the immediately preceding step — after all, you don't blame zip or GitHub's web server for the corruption either. The answer to what went wrong in creating that PO with near certainty lies in what you fed into `msgmerge`, how and where.

`msgmerge` is a UNIX tool. Depending on your build and version of it, it may (I think) have some resilience to CRLF/DOS/Windows line endings; I'm honestly not sure about the precise behavior, except for knowing that the MinGW builds can mostly handle DOS line endings. My best guess is that a series of events like this happened:

1. You generated some POT with one reference on one line (a non-canonical, but easy to produce, formatting). The produced file used CRLF line endings.
2. You then fed it into `msgmerge` on some UNIX, where the tool only understood LF line endings. As part of generating its output, `msgmerge` normalized references to fit multiple on a line. Because it didn't understand `0x0D`=`CR` portion, it considered it part of the file:line reference.
3. *Something* then normalized line endings to be UNIX=LF (because the lines don't end in CRLF and step 2 would cause CRLF line endings to be preserved).

Does that sound plausible?

For best results with GNU gettext tools, including `msgmerge` it's best to have POs and POTs consistently with UNIX line endings.

**Comment by donovaly** [comment]
Hello Václav,

many thanks for your analysis. You were right, the line endings were the problem. As simple as it was, I just updated from gettext 0.18.1 to 0.19.8.1 using these binaries:
https://mlocati.github.io/articles/gettext-iconv-windows.html

Using its msgmerge helps. This gives ma a.pot file with UNIX line endings and entries like this:
```
msgid "Credits"
msgstr ""

#: src/frontends/qt4/ui/AboutUi.ui:84 lib/layouts/agu_stdtitle.inc:81
#: lib/layouts/apa.layout:205 lib/layouts/apa6.layout:315
```
To avoid that Poedit breaks the lines I just have uncheck in the Poedit settings the option to break the lines at 80 chars.

So in fact updating gettext was the key.

Many thanks for Poedit!

(by the way, don't be upset if people misspell Poedit like e.g. "PoEdit". You can imagine how many users of LyX write "Lyx" or "lyX" or just "lyx" or "LYX". )
