### ISSUE TITLE
Can't get rid of the bottom scroll bar (openSUSE)

### ISSUE THREAD

**Issue by wsxy162** [vslavik/poedit#474]
Poedit: 2.0.7
OS: openSUSE Tumbleweed 20180511

![2018-05-14 03-48-52 -1](https://user-images.githubusercontent.com/6559703/39971303-507a94b6-572b-11e8-9a91-f9e9eea6aa29.png)
This scrollbar always settles down there, not matter what i resize the windows or add/remove the ID column. I presume enlarged app window will remove it.
PS: The UI language is Chinese, I don't kown if this will affect my reported issue.

**Comment by vslavik** [comment]
Please follow the [instructions](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) you were asked to follow when you created this issue. In particular, you forgot to provide the PO file, list of your View menu settings and details about your build (GTK+, wxGTK etc. versions). See (and *read*) step 3 of the instructions to understand why it's pretty much impossible to fix such bugs otherwise.

**Comment by wsxy162** [comment]
This bug is not about some specific PO files. There is the view setting. I removed poedit-lang.
![2018-05-14 21-36-37](https://user-images.githubusercontent.com/6559703/40000767-3db13be8-57bf-11e8-9d2a-d2a7756507be.png)
GTK+ version: 3.22.30 wxGTK: 3.1.1.g3

**Comment by wsxy162** [comment]
I tested poedit 2.0.7 on fedora 28 with GTK3+ 3.22.30 and wxGTK 3.0.4, they don't have this problem. So maybe this a packging issue on openSUSE. I have reported in [openSUSE bugzilla](https://bugzilla.opensuse.org/show_bug.cgi?id=1093503).

**Comment by vslavik** [comment]
> This bug is not about some specific PO files.

It's wonderful that you are so knowledgable about Poedit's codebase that you can make such claims so confidently. You will therefore, I am sure, have no trouble debugging it and producing a patch to fix the issue. 

Or if you don't feel up to the task, it would be great if you could follow the instructions. I wrote them for a reason, you know. I wrote the code, I *know* of several factors in a specific PO file (or class of PO files, which may be all you ever use), e.g. the number of strings in it.

> So maybe this a packging issue on openSUSE.

Again jumping to conclusions. This can't *possibly* be a "packaging issue", you're just wasting their time. OTOH, you yourself write about a significant difference, in wxGTK version. *There's* your relevant difference.

**Comment by vslavik** [comment]
> I don't think upload some po files would help for this

If you're expert enough for a qualified opinion, please submit a patch with a fix. If you're not, please *listen to the experts* and provide the information they need — you "just want to solve the problem", so cooperating is in your best interest. 

> don't know why you are acting so tough

You're wasting my time arguing about what you think *I* need, instead of just providing the information *I* think I need. Sorry that I'm not particularly happy about it. 

> And the instructions? Even doesn't mention them.

This doesn't make much sense grammatically, but both the instructions shown when you create a new issue and my comments above instructed you to attach the PO file needed to reproduce. I see you attached some file, but it's clearly not the one from the screenshot, so I'm left confused here.

> And you miss the "maybe" word, it's your judgement.

None of what I wrote is "judgement". If you're referring to the packaging remark, yes, I do *know* it's not packaging-related.

**Comment by wsxy162** [comment]
For a clarify, I did take a see at instruction before I summitted this issue, 4. doesn't mention about GTK+  and wxGTK, so I didn't write about these and 5. my first thought it's not about a specific PO file so I didn't upload one. For my totally apologize, my first opinion is simple and native.

This is you really wanted PO file 
[NetworkManager-master-po-zh_CN-156831_BDUSpyR.merged.zip](https://github.com/vslavik/poedit/files/2009916/NetworkManager-master-po-zh_CN-156831_BDUSpyR.merged.zip)
or a snapshot about that one.
![2018-05-17 00-11-58](https://user-images.githubusercontent.com/6559703/40129575-3417bc48-5967-11e8-81dd-73a6429a9c3d.png)

**Comment by wsxy162** [comment]
Found the packaging difference between opneSUSE and others, wxWidgets-3_0 in openSUSE is build to wxGTK2 not wxGTK3. If I specified wxGTK3-devel to build poedit, the bottom scrollbar will be gone.

**Comment by vslavik** [comment]
Thanks. Then I guess it makes sense to close this issue, if using up-to-date GTK+ addresses it?

**Comment by wsxy162** [comment]
I have summited a packaging fix to openSUSE. Closed this issue.
