### ISSUE TITLE
Despite required components are installed application persists to alert about non-installed component.

### ISSUE THREAD

**Issue by Ricky-Tigg** [vslavik/poedit#476]
**OS**: Linux – Fedora 28 Desktop
**Component**: poedit.x86_64 2.0.7-1.fc28 @updates

Despite required components are installed, application persists to alert about :
![poedit x86_64_2 0 7-1 fc28](https://user-images.githubusercontent.com/26058215/39990470-eed0ea7a-576c-11e8-8976-4ef25d02ac57.png)

In terminal:

**Available components are**:
`$ dnf list | egrep -i "spellchecker|aspell|myspell" | egrep -i ".x86_64|.noarch"`
`aspell.x86_64                            12:0.60.6.1-21.fc28           @anaconda`
`aspell-fi.x86_64                         0.7-10.fc28                   @fedora ` 
`perl-Text-SpellChecker.noarch            0.14-10.fc28                  @fedora  `
`...`

Component '**myspell'** is not registered in Fedora 's repositories.

**Installed components are**:
`$ dnf list installed | egrep -i "spellchecker|aspell"`
`aspell.x86_64                              12:0.60.6.1-21.fc28         @anaconda`
`aspell-fi.x86_64                           0.7-10.fc28                 @fedora `
`perl-Text-SpellChecker.noarch              0.14-10.fc28                @fedora`

**Comment by vslavik** [comment]
> Despite required components are installed, 

If they were installed, you wouldn't get the warning. Either you don't have them installed, or you didn't give the system a chance to reflect the additions (e.g. by restarting the desktop or at least Poedit).

Poedit uses GtkSpell. If GtkSpell says you don't have a spellchecker, something is wrong with your system, not Poedit. I don't use Fedora, I can't help you with installing things on it. 

If you believe the issue is in Poedit, please provide evidence that Suomi spellchecking works correctly in e.g. Gedit.

**Comment by Ricky-Tigg** [comment]
System was booted since then. Installed **system localisations** are _English_ (default) and _Finnish_. Despite those sets, _French_ and _Finnish_ were respectively unexpectedly present and missing from gedit's list related to checkspelled languages. On [Gnome](https://help.gnome.org/users/gedit/stable/gedit-spellcheck.html.en) _Gedit_ appears to rely on echant component to operate.  For Finnish checkspell component **enchant2-voikko** is then required and therefore was installed manually in the context of your request.  As follow, others components were either installed as dependencies or as default.

`$ dnf list installed | grep -i enchant`
`enchant.x86_64                             1:1.6.0-20.fc28             @anaconda`
`enchant2.x86_64                            2.2.3-2.fc28                @anaconda`
`enchant2-voikko.x86_64                     2.2.3-2.fc28                @fedora  `
`python3-enchant.noarch                     2.0.0-3.fc28                @anaconda`

As noticeable on _Fedora_ operating system, checkspell suggestions applying to Finnish operate now as intended in _Gedit_, but installation of subsequent component is without effect on _Poedit_,

**Comment by vslavik** [comment]
Again: please provide *evidence*, e.g. screenshots. Please also verify Poedit is actually using the same GTK+ version (2 vs 3) as Gedit et al. Make sure you actually restarted Poedit *after making any spellchecker-related changes*. Check with some other language too. In short, *investigate* — as I said, I don't use Fedora, I can't. You're using Linux; the need to dig into things a bit yourself comes with the territory.

You seem to be dead-set on this being a Poedit issue, but it really isn't. Poedit uses GtkSpell, which uses Enchant. And Poedit reports a missing dictionary when [setting GtkSpell language](https://github.com/vslavik/poedit/blob/master/src/spellchecking.cpp#L84) fails to accept the language. It's not like there's anything fancy done by Poedit around it.

If you say Enchant accepts the language in some applications but not others, my only guess would be that you have two Enchant libraries on the system — and only one of them has the dictionary added. Use `ldd` to check.

**Comment by vslavik** [comment]
Damn. Actually *your very own comment above* shows that you do have two versions of Enchant. So there's your problem: your Poedit is built against an older version. *Probably* because Fedora built it against GTK+2 and not 3. 

Why you installed `enchant2-voikko` only without `enchant-voikko` is beyond me, but there's your cause.

**Comment by c72578** [comment]
Just for the records here:
Poedit under Fedora is currently built against wxGTK3 and gtkspell3, whereas gtkspell3 is built against enchant [1, 2].
As soon as enchant-voikko is installed, the required dictionary is found by poedit (just tested with [brasero.master.fi.po](https://l10n.gnome.org/POT/brasero.master/brasero.master.fi.po)):
`sudo dnf install enchant-voikko`

[1] https://src.fedoraproject.org/rpms/poedit/blob/master/f/poedit.spec
[2] https://src.fedoraproject.org/rpms/gtkspell3/blob/master/f/gtkspell3.spec

**Comment by vslavik** [comment]
@c72578 Thanks for confirmation!

I have since then learned about the source of the confusion: Enchant (which is maintained again, yay!) has an ABI-incompatible new version 2.x *which Gspell requires*; GtkSpell on the other hand requires 1.x. Fedora's decision to ship both and not even bundle things like Voikko into a single package for both was IMHO unfortunate and e.g. Ubuntu 18.04 probably opted for an older Gspell version for this reason.

Anyway: the one thing I can do to mitigate this is to use Gspell if available instead of GtkSpell — it is after all official part of GNOME, so it makes sense to do so.

**Comment by ekuester** [comment]
Another complaint with same content but this time for german spell checking ... I've installed from the fedora repositories poedit-2.2.1-1.fc29.x86_64.rpm and have the same alert (but for german). Would it be better to compile from GitHub source? Should I have a look into the SPEC files and make my own RPM?
