### ISSUE TITLE
Poedit adds an extra space after every string, when selecting text

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#479]
Using Windows 10, Poedit 2.0.7.

STR:
1. Open any PO file (yeah, I know you hate it when people say that, but really, any PO file) with some strings in it.
2. Focus the source text field (or the translation field, assuming there's some text in there).
3. Hit Ctrl+A.
4. An extra space is added **(just visually)** in the end of the text.

![default](https://user-images.githubusercontent.com/18016656/40443565-68c8d2b6-5ecf-11e8-903a-b0722d191ca5.png)

I **think** this was reported somewhere here, but didn't find it with the search option.

**Comment by vslavik** [comment]
This apparently standard behavior of RichEdit 5.0 as used in Windows 10 — compare with WordPad, which uses the same control and which behaves the same. 

The same thing happens when you drag-select from beginning of text to its end (but not when you do it backwards), which was first clue that this is control's native behavior. I'm going to close this as WONTFIX, because making our own edit control would be a bit overkill for something cosmetic and barely noticeable like this. IOW I would *like* to fix it, but don't see a reasonable way how.
