### ISSUE TITLE
Last 2-3 characters in Source Text and Translations entries are being visually truncated 

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#489]
Using Windows 10, Poedit 2.0.8. This used to work okay in 2.0.7.

STR:
1. Open any PO (or POT) file. For this example, use [this file](https://github.com/vslavik/poedit/files/2032415/index.zip)
2. If Poedit is RTL, the last 2 characters are being truncated (from the table) for every Source Text entry, and if LTR- for every Translation entry
(In the [rambo.zip](https://github.com/vslavik/poedit/files/2073299/rambo.zip) POT file, some strings are missing 3 characters, like those with the space in the end)

![default](https://user-images.githubusercontent.com/18016656/40991525-b98142e2-68fc-11e8-9782-0f2b9f06349f.png)

**Comment by vslavik** [comment]
> Open any PO 

Well, not *any* — only any *direction flipping* one, which is why I didn't notice, my literacy in Hebrew being a bit… ahem… limited. 

So it's either this or full fix for #481. The latter is cosmetic, this is is serious, so I am reverting the source column fix from #481.

Here's a test executable: https://jumpshare.com/v/BuCsntjWuSiPA1kzFcmg

**Comment by ItielMaN** [comment]
LGTM on the test file.
