### ISSUE TITLE
Custom syntax highlighting

### ISSUE THREAD

**Issue by smulloy21** [vslavik/poedit#494]
The current syntax highlighting is great - we'd love to add on to it. Being able to mark all code elements as distinct from text would be a huge boost to productivity. Could be a custom configuration, since different projects will use different code formatting.

**Comment by vslavik** [comment]
You're being vague to the point of incomprehensibility.

For example, you talk about "code formatting", but no such thing is involved in translation and if you mean highlighting of format elements in strings, those are typically standard, using language-provide capabilities, and it's absolutely not true that "different projects" using the same language would use different syntax, or that using homegrown custom syntax is a reasonable or common thing to do (as seems to be implied).

So I assume you didn't mean *that*, because it wouldn't make much sense, but then I'm at lost about what you actually meant. All I can tell you right now is that if you'd "love to add" something, well, do it, and submit a PR — or at least explain yourself in detail, with specifics and examples. [This](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) is helpful (and isn't about bugs only).

**Comment by smulloy21** [comment]
Yep, we definitely seem to be misunderstanding each other. This is likely due to my being new in this space. 

What I'm referring to is that poedit currently has syntax highlighting for standard html elements (e.g. the paragraph tags would be highlighted in the string `<p>Hello, world</p>`). What I'm pointing to is adding highlighting for other code and templating elements to mark them as clearly distinct from text that needs to be translated (e.g. the variable contained in angular brackets in the string `{{ num }} years old`). 

Hopefully this helps to clarify - if there's a way to do this already, that would be great to know. This may simply be a matter of ignorance on my part as to what 'language-provide capabilities' are. I'll look more into this, and in the meantime, any insight you have is appreciated!

**Comment by vslavik** [comment]
> if there's a way to do this already, that would be great to know.

There is: don't use homegrown syntaxes. Your programming language probably (because again: you omit any specifics) provides *standard* formatting strings syntax and Poedit already highlights it: https://www.gnu.org/software/gettext/manual/html_node/Translators-for-other-Languages.html#Translators-for-other-Languages

**Comment by smulloy21** [comment]
I did provide a specific example - we're looking for a way to highlight the angularjs brackets and variable `num` in the string `{{ num }} years old`. 

This is not a homegrown syntax, but it is specific to the javascript framework we are using. As another example, while the html paragraph tags are highlighted in the string `<p>Hello, world</p>`, the first would not be if it included an angularjs directive, such as `<p ng-show='someVariable'>Hello, world</p>`.

Hopefully this helps clarify.

**Comment by smulloy21** [comment]
In addition to angularjs support, we are looking for support for jinja2, which is a templating language for python. An example string would be `'Hello %(name)s!'` where `%(name)s` marks a string variable `name`. More examples can be found here: http://jinja.pocoo.org/docs/2.10/extensions/#id2

This is why I framed the feature request as, in your words, an overly generalized solution. I would not expect every development team needs angularjs and jinja2 support in particular. There are many templating engines - these are specific to our stack. Having a way to customize syntax highlighting seems like the simpler solution, rather than adding support for each templating syntax as they are requested one by one. Feel free to close this issue, though, if you see no value in this.

To take a step back, I do fully admit my first post could have been clearer and more detailed. I appreciate that you do seem to be trying to be helpful in pointing out areas where I could be more specific. Your tone, however, has been condescending and rude. I mention this in case it is unintentional on your part. This conversation has been unwelcoming to say the least, and is a good example of a negative experience that would easily make a potential user not want to come back, let alone not want to contribute to or evangelize your project. See here for reference: https://opensource.guide/building-community/

**Comment by vslavik** [comment]
> Having a way to customize syntax highlighting seems like the simpler solution

That's a fair argument — *if* you're the person doing the work and sufficiently knowledgable about the code base to be capable of competently evaluating that. If that's the case, please phrase your feature requests in the form of a PR with a patch. If it's not the case, then again: you simply can't make *qualified* judgement calls on this topic. FWIW, as the person with some expertise with the codebase in question, I'm reasonably confident that adding a few highlighters is simpler that doing a user-extendable customizable one (even without accompanying GUI). 

Jinja2, of course, uses Python format string syntax, i.e. common to various uses of a popular language — and again, it's an omission (one that could be fairly classified as a *bug*) that it's missing. That's 2 out of 3 that custom highlighting would be a poor fit for. 

> Feel free to close this issue, though, if you see no value in this.

It's rather obvious, I think, that I do see value in "this" (see: not closed yet) for some value of "this". There's definitely value in supporting AngularJS syntax, not least because it and variants, are common. There's value in having this fully customizable as well, but I think it's not *worth* the amount of work required. But if somebody feels differently, I'd be happy to merge such a PR. I'm not *against* it. 

> I do fully admit my first post could have been clearer and more detailed.

In light of what else you wrote, let's be perfectly honest, shall we: it was very, very bad. Coming from a developer who should know better, it was rude and disrespectful of the time of the developers you expected to spend time at least triaging your issue. Don't tell people "your time is worthless" if you want them to be nice to you.

You seem to be forgetting that an Open Source community is a *two* way street. Even that hipstery OSS guide for the kids that you link to teaches you that, if you read *all* of it.

> Your tone, however, has been condescending and rude.

I recommend that you try to not be as judgmental of people (who might not be privileged Americans, but might come from a different society and learned English the hard way) solely based on written text.

I went out of my way to *explain* every bit of *why* and how you did a poor job — because you definitely didn't realize that. I did my best not to dismiss you. If I closed the issue as unreasonable at first sight, a) you'd probably get offended by *that* too, and b) I'd never get to the bottom of it. If I didn't push you, you wouldn't push back with important, valuable specific information.

> See here for reference: https://opensource.guide/building-community/

How hypocritically *condescending* from somebody who lectured me on condescendence a few sentences back.

**Comment by vslavik** [comment]
Closing this because I am unlikely to implement fully user-customizable highlighting myself.

Dear future reader of this issue: if you'd like to see highlighting for a specific syntax that isn't supported, but is reasonably widely used (i.e. not internal/homegrown), file a separate issue for it. For example:
 * #496 — core gettext formats
 * #497 — AngularJS and similar

For entirely customizable highlighting, I'd accept a PR doing it.
