### ISSUE TITLE
first untranslated entries ?

### ISSUE THREAD

**Issue by gbonline** [vslavik/poedit#500]
Hi, I'm using Poedit 2.0.9 in italian so I'm not sure for the menu voices I'm talking about.
In the Visualize menu there is a feature "First untranslated entries" but I can't se any changes on the items list when I check this feature. I tried different options of sort in couple with the feature, but nothing.
For me the untranslated entries have the source equals to the translation, so when I check the feature I'd like them to be listed at the beginning, then sorted by as checked.

**Comment by vslavik** [comment]
This is a *bug tracker*. Please don't abuse it for non-bugs things like asking question — that's what you have https://poedit.net/support for.

> For me the untranslated entries have the source equals to the translation

No. Untranslated entries are entries *that don't have a translation*. If they do have a translation, even a bad one or identical to the source, they're not untranslated, because they *do* have a translation.
