### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Doezer** [vslavik/poedit#508]
I used Poedit behind a corporate proxy thus I have no access to suggestions
![image](https://user-images.githubusercontent.com/11655673/44662917-5f9a9e00-aa0f-11e8-840f-bf41f69b818d.png)
Support for HTTP proxy would solve this (looked for it in the preferences but didn't see any)

**Comment by vslavik** [comment]
You didn't see any because Poedit uses your system-wide proxy settings — and you apparently have those broken. You either don't have the proxy setup in Internet Explorer / Windows at all, or you do, but manually meddled with .NET config too, preventing automatic use of MSIE's.

Read this: https://superuser.com/questions/489527/how-can-i-configure-proxy-settings-for-all-apps-system-ie-etc

Closing as duplicate & not-a-bug.
