### ISSUE TITLE
Source language not identified if compiled without CLD2

### ISSUE THREAD

**Issue by gandriyko** [vslavik/poedit#523]
Translation memory panel in empty after update to Poedit 2.2.
ArchLinux, latest version.
Console: 

```
(poedit:2608): Gtk-WARNING **: 21:09:53.695: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkToggleButton)

(poedit:2608): Gtk-WARNING **: 21:09:53.695: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkToggleButton)

(poedit:2608): Gtk-CRITICAL **: 21:09:53.695: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

```

**Comment by vslavik** [comment]
When you created this issue, you were asked to read [this](
http://www.chiark.greenend.org.uk/%7Esgtatham/bugs.htm). Please respect the project's instructions and do so.

As it is, this issue is non-actionable because you don't provide *any* relevant information (the one piece of specifics you provided, GTK+ layout warnings, is while appreciated unfortunately almost certainly unrelated) — you don't really describe what happens (I very much doubt the sidebar is literally *empty* and devoid of anything, and you don't describe what it shows you), where you got Poedit from (arch packages, official snap one). That's probably a consequence of you jumping to unwarranted conclusions: that this is because of the 2.2 update (it probably isn't), that it is unrelated to your PO file (it probably is), that there actually is something matchable in your TM (hard to say).

Can you please provide a more detailed description, including specific files and ideally your TM export as TMX?

**Comment by gandriyko** [comment]
File for testing
[test.zip](https://github.com/vslavik/poedit/files/2479337/test.zip)
Screenshots:
https://i.imgur.com/KUcWB7M.png
https://i.imgur.com/FDqHYkC.png

**Comment by vslavik** [comment]
> I've the same problem. It's impossible to import any po file into the translation memory. 

In other words, it has absolutely nothing to do with *this* bug at all. Please don't hijack other bugs and file a separate one. Make sure to read *and follow* the instructions shown to you when you create a new issue.

**Comment by vslavik** [comment]
This isn't a matter of TM, but of Poedit's failure to detect the source language from short and/or weird PO files (see the screenshots — it doesn't say "English" in the other one).

That's certainly the case with the artificial test file you attached. Would you have a real-life real file in which you encounter this problem?

**Comment by gandriyko** [comment]
[django.po.zip](https://github.com/vslavik/poedit/files/2612620/django.po.zip)

**Comment by vslavik** [comment]
> django.po.zip

This file's source language is correctly recognized by Poedit and doesn't exhibit any such problem. It also doesn't contain the string "Test". A little extra verbosity would once again not hurt...

**Comment by gandriyko** [comment]
It does not depend on specific po-file. This bug appears in any po file. 
I made screenshot: https://i.imgur.com/FDqHYkC.png
Translation suggestion is ALWAYS EMPTY in version 2.2.

**Comment by vslavik** [comment]
The thing that you described so far, with the reproduction steps you provided, *is* specific to that specific bad file. 

If you disagree, provide usable reproduction instructions, instead of some random screenshots that show nothing (for example: the list would be empty with empty TM). Read the instructions I linked above. 

And no, despite your assumptions, it is *not* the case that TM just doesn't work at all in 2.2. It's a bit preposterous assumption to make, really.

**Comment by vslavik** [comment]
> I don't know how I can explain situation.

Please do read the article I repeatedly asked you to read. It really does help with understanding how to report issues in a way that a person other than you can follow and do anything about. 

If you don't provide detailed, accurate, exhaustive reproduction instructions that actually describe your situation (including such absolute basics as providing a full copy of your TM, specific PO files and specific instructions on what specifically to do in Poedit, down to specific strings), there's very little I can do. I can't see your computer. You have to either cooperate (again, reading the article is a necessary first step) or you can use a debugger and investigate it yourself. But I can't very well do anything remotely with only a few vague screenshots. 

You can also see for yourself that no TM-related changes were made since 2.1.1: https://github.com/vslavik/poedit/compare/v2.1.1-oss...master — i.e. it is either unrelated to something Arch Linux did.

**Comment by Fat-Zer** [comment]
Hi, It looks like, I've got the same issue on gentoo. It looks like the regression was introduced with a86559f. It's likely that the reason you haven't noticed it is because you haven't tried to to build with cld2 support turned off. 

Steps for reproduce:

1. Build `--without-cld2`
2. Add some phrases to translation memory.
3. See that language detection fails and there are no suggestions displayed.

Possible fixes:

1. Use English as default if built without cld2 or fallback language in any case.
2. Provide some GUI for user to choose the Original language.

------

PS: I'm not know why Arch and Gentoo don't include cld2 support. Are there some licensing issues? And is there any documentation on how to build it?

**Comment by vslavik** [comment]
@Fat-Zer Thanks for the detailed — and spot on — analysis! Indeed, if you have a degraded build, then this breaks even if the file's content is reasonable 😥

> PS: I don't know why Arch and Gentoo don't include cld2 support. Are there some licensing issues? And is there any documentation on how to build it?

Yes, there is documentation in the tarball. No, there are no licensing issues. The question why these distros choose to provide degraded packages (it's not just CLD2, but online capabilities as well), is best asked of them, not me. FWIW, Poedit's configure script rather forcefully [tells them it's a terrible idea](https://github.com/vslavik/poedit/blob/c645c61fb7b2b1550244e7187ef33831cbb8580d/configure.ac#L317) and I am very surprised by distros intentionally (Gentoo's ebuild has comments to the effect) doing it.

**Comment by Fat-Zer** [comment]
> Yes, there is documentation in the tarball.

Hm... where exactly? and what tarball? I meant how to build cld2 (just in case)...

> The question why these distros choose to provide degraded packages

Can't say for Arch, but for Gentoo, it's likely because nobody wants to maintain 2 more library packages, which provides no more than (I don't want to seem ungrateful, but just going to frankly describe the maintainer's POV) quite a minor functionality to a single and not most important app. Moreover the cld2 seems to be unmaintained by upstream, has no release tarballs and looks like have no supplied build functionality.

> FWIW, Poedit's configure script rather forcefully tells them it's a terrible idea

It would be more helpful, if it mentioned what exactly functionality being lost.

**Comment by vslavik** [comment]
> I meant how to build cld2 (just in case)…

Please avoid off-topic comments like this. You're in *Poedit* tracker, really not the place asking how to build CLD2 (and indeed, I assumed you were being on-topic and asking about Poedit). 

> It would be more helpful, if it mentioned what exactly functionality being lost.

It does, right above it. Thanks for the condescending lecture, though :(
