### ISSUE TITLE
Crowdin Integration with bigger PO files - 12002 Operation timed out

### ISSUE THREAD

**Issue by gorfreed** [vslavik/poedit#540]
I am trying to use POEdit for one of my projects on Crowdin, but I cannot checkout the main PO file via the POEdit interface, as it only gives me the following error when selected: 12002 Operation timed out

![image](https://user-images.githubusercontent.com/6634117/50375052-cd3e8b80-05f7-11e9-9ece-d9dc8aa31a15.png)

I confirmed that in general this connection works - although just with PO files smaller in size. I cannot split the PO of my project (about 300k strings / 1 Mio. source words), which works fine with POedit when opened "offline" on desktop. Do you know about any Crowdin API limitation or setting that could potentially cause the timeout?

**Comment by vslavik** [comment]
I think you are jumping to conclusions — even long downloads wouldn't result in *time out*. If Crowdin is incapable of generating the PO file quickly, that would seem a more reasonable complain towards them, not Poedit.

But nothing in what you wrote substantiates the assumption that it is size related. And of course censoring the screenshot doesn't help matters. Please follow [the instructions](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) shown to you when you created this issue and provide both usable reproduction steps and basic information like your Poedit version, OS version etc.

Also: At first sight, something seems fishy about your OS: there's no way the OK and Cancel buttons would be this ridiculously small normally. What's up with that?

**Comment by gorfreed** [comment]
Not sure what you are getting at with your defensiveness in your arguments. I also didn't make any conclusions, but was asking for potential causes which you have deferred to Crowdin. I have to censor the file and project names on the screenshot in order not to disclose my client, I have purchased Poedit Pro (dfinck@loquatics.com) as I am currently looking for an alternative workflow for a large volume continuous game localization project which needs a quick client-based PO editor with CAT integration for the different teams to interface with. While your software seemed to be a match for these criteria, I also need to make sure I can hand the setup over to the project managers knowing there is at least some constructive/solution-oriented support from the developer - which seems questionable unfortunately.

**Comment by gorfreed** [comment]
As I have written in my original post, I suspected this to be a Crowdin limitation. I am not sure what sore spot I have hit with my question, but if you have any sincere aspirations to sell Poedit PRO for professional use, you simply cannot start your support responses with your paying customers (!) by first questioning the validity of their claim and then lecturing them about how to submit bugs to you. NO MATTER how dumb you think these questions are - you simply cannot do that. If you want to have users use a specific channel for reporting bugs (instead of Googling a support contact for POEdit like I did), why don't you include the email address or a link in your error prompts? There is nothing of that sort, which is basically asking for these requests coming in all over the place.

I sense some anger here that might have built up when you had to deal with other issues, but it certainly is misdirected a me - in no shape or form have I complained about your software. Crowdin has confirmed the limitation on their end by now, and I know from other projects that we worked on that we certainly could make it work for a large live project like this one - however, would also need to work with you on this and I feel that you are not really looking for working on custom integration projects for your software anyways. Which is shame since this means I have to use one of the "big" and unwieldy software platforms instead of a lean alternative one like POEdit. Anyways, thanks for your time and best of luck.

**Comment by vslavik** [comment]
Sorry, but I'm confused by your reaction. I didn't "lecture" you on anything, I asked you to please contact directly for commercial support — that's all. I also didn't "question validity" of anything (a screenshot being a rather strong proof of it happening), but questioned the implied assumption it's a client-side issue. As it turns out, I was 100% right about that, wasn't I?

And I'm *very* confused by this claim:

> why don't you include the email address or a link in your error prompts? There is nothing of that sort, which is basically asking for these requests coming in all over the place.

1. The support page is prominently shown on the homepage, labeled "Support".
1. Both of the emails you received point you to the support email address.
1. It's in-app in the Help menu as well.
1. Even googling "poedit support", as you said you had to resort to, goes there.

So really, short of ugly banners with email in every possible place in-app, I'm not sure how more prominently I could have shown support contacts — all the obvious places make effort to point you there. The GitHub repo, on the other hand, is not exactly plastered all over the place, it takes extra *effort* to go there, so it's natural to assume issues there are for OSS.

Finally, I'm sorry that my crystal ball was performing suboptimally at the time and didn't identify your anonymously created issue, which in no way indicated your identity or license status, as coming from a customer. Magic being inherently unreliably, I'm not quite sure how to improve that either.
