### ISSUE TITLE
Colorize 'Untranslated' entry, to make more distinguishable.

### ISSUE THREAD

**Issue by darkcircle** [vslavik/poedit#541]
Untranslated entry is  distinguishable, because that entry has no translated message (msgstr)
but sometimes, some users usually just eye-focus on original msg during scroll up/down, users can miss untranslated message.
I know that this problem can be solved by selecting sort by translation + untranslated entry first,
but every users are not want to set this option in all the time.

untranslated entry was colorized by navy-blue similar color, in previous version.
some people hate blue, so red, green, violet, pink, and another one is also ok,
simple program is the best, but, this feature is needed for many translators.
we would better to note that this feature is sometimes, useless for color-blindness person,
so faux bold'n italic also can be needed.

**Comment by vslavik** [comment]
> this feature is needed for many translators

Translation: you (one person) dislike that this changed a few years back. It's not "many" and you don't "need" it (or at least your description didn't make it clear *why* you *need* it).

This was an intentional change and I don't plan to roll it back. As you point out yourself, the untranslated entries are immediately obvious from the fact that *they don't have a translation* and any further emphasis would be redundant.
