### ISSUE TITLE
Non-breaking space

### ISSUE THREAD

**Issue by Li-An** [vslavik/poedit#564]
Hello, non-breaking space is very important in french typography. Since last version, when I type a non-breaking space, PoEdit shows a non found character icon.

This is a sentence with only non-breaking space managed by my Bepo driver.

See capture 
![space](https://user-images.githubusercontent.com/689870/56468126-1c6ebe80-6428-11e9-8803-ee3183ce3576.png)

**Comment by vslavik** [comment]
> Hello, non-breaking space is very important in french typography.

Perhaps you should provide a better explanation instead of assuming everybody is French…

> Since last version

That's certainly not true. It doesn't help that you don't say what you think the "last" version was, what the current version you use is, what your operating system is, what *else* changed since the last time you used Poedit (and its "last" version) etc. When you created this issue, the tracker asked you to consider all that information, to include sample files, to describe steps to reproduce (I really have no idea how and what you typed, if you don't tell me) and to [read this guide](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) — could you please do it?

Thanks!

**Comment by vslavik** [comment]
Also from the looks of it, you might have used a custom font. If you did, perhaps you've chosen one with bad Unicode coverage.

**Comment by Li-An** [comment]
Sorry, I did not want to upset anybody. 
You are right, I changed the default font.
