### ISSUE TITLE
"Wrong type, required: wxBitmap but: wxIcon" error displayed

### ISSUE THREAD

**Issue by super7ramp** [vslavik/poedit#571]
## Environment

- Poedit version: 2.2.2
- wxGTK version: 3.0.4
- GTK+ version: 3.24.8
- Operating system: openSUSE Tumbleweed (20190512)

## Bug

"Wrong type, required: wxBitmap but: wxIcon"  error is displayed in a popup window.

It looks like commit b33970a replaced wxBitmap with wxIcon in PoeditListCtrl but a part of the code still assumes the presence of wxBitmap.

I tried [this naive patch](https://build.opensuse.org/package/view_file/home:1Antoine1:branches:M17N/poedit/poedit-2.2.2-null-variant.patch?expand=1) and it seems to fix the problem - at least I don't have the error anymore in my environment.

### Steps to reproduce

1. Open example po file: [yast-rpm-groups-master-fr.po.zip](https://github.com/vslavik/poedit/files/3185689/yast-rpm-groups-master-fr.po.zip)
2. Scroll until you reach the "C++" chain.

Problem occurs when a chain is displayed for which there is not icon in first column.

**Comment by vslavik** [comment]
Thank you!

The number of permutations of wxGTK versions I need to support is seriously getting out of hand :(

The `HAS_BROKEN_NULL_BITMAPS` part doesn't apply to you, so that shouldn't have an effect (but it did alert me to it *too* being broken). The rest seems to be on the right track, I'll just need to test it with the wx snapshot Poedit uses internally.

**Comment by david-geiger** [comment]
Same issue here on Mageia Cauldron!

Regards,
David
