### ISSUE TITLE
Feature request: ability to select to keep deleted translations while updating from source

### ISSUE THREAD

**Issue by zapper** [vslavik/poedit#595]
Hello,

It would be nice if Poedit would have ability to select if I want to keep deleted translations while updating from source.

**Comment by vslavik** [comment]
Poedit does keep deleted translations in accordance with standard GNU gettext tools' behavior where they can be restored if they start appearing in source strings again. See GNU gettext docs.

If you're asking for them to stay visible in the UI and be translatable and treated as normal translations, I'm not going to do that, because it again doesn't make sense: deleted strings are, by definition, *not used anymore*, it would be a waste of resources to translate them.

**Comment by robert-j-engdahl** [comment]
@zapper If you are updating your translations from multiple sources you should use a script instead.   That way you can make sure that only the texts you no longer need are deleted.  Alternatively you could use a different po-file for each source project.

If there are strings that no longer exist in the source, but they went into say a database, you could eternalize them by referencing them in your source with a Noop() invocation, you never need to invoke.
