### ISSUE TITLE
Context specifier - msgctxt merged with actual string (msgid)

### ISSUE THREAD

**Issue by naro** [vslavik/poedit#619]
PoEdit: OSX Version 2.3 (5889)

I'm not sure if I do something wrong but when I generate a .po file from Django 2.2 with pgettext('no variant', 'Not set') in the source code, I get the following record in the .po file:
```
#: forms.py:41
msgctxt "no variant"
msgid "Not set"
msgstr ""
```

That looks about right, but when I open the .po file in PoEdit, it's displayed as 
![poedit](https://user-images.githubusercontent.com/518956/75133904-c8cea080-56dc-11ea-8ea4-3498d5421cc2.png)

and when the translation is saved, it results in the following record in the .po file:
```
#: forms.py:41
msgid "no variantNot set"
msgstr "Bilingual"
```
It looks like a bug.

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (it's the same from when you created this issue) and provide full steps to reproduce, which includes at the minimum providing an example file and detailed steps to reproduce. 

If this was a bug that universally happens, as you are evidently assuming (because you don't see the point in providing details), it would be horrible, data-destroying one. Fortunately, that's simply not the case. *Something* you left out in your description matters a great deal. Hence why I'm asking you to provide much more details.

TIA!

**Comment by naro** [comment]
Hi Vaclav,

it's indeed a bug not in Poedit, of course.  It was caused by syncing generated .pot file with already partially translated .po file using a tool that does not know how to use msgctxt. I switched to msgmerge and it works now!

I'm sorry for taking your time.
