### ISSUE TITLE
unportable test operator in deps/icu4c/source/configure*

### ISSUE THREAD

**Issue by 0-wiz-0** [vslavik/poedit#623]
The configure script uses `==` for comparisons. This is only supported by bash's `test`, not even GNU coreutils' `test` supports it. POSIX specifies `=` as comparison operator.

Patch:
````
--- deps/icu4c/source/configure.ac.orig 2020-02-03 14:01:01.000000000 +0000
+++ deps/icu4c/source/configure.ac
@@ -1287,13 +1287,13 @@ fi
 # Now that we're done using CPPFLAGS etc. for tests, we can change it
 # for build.
 
-if test "${CC}" == "clang"; then
+if test "${CC}" = "clang"; then
    CLANGCFLAGS="-Qunused-arguments -Wno-parentheses-equality"
 else
    CLANGCFLAGS=""
 fi
 
-if test "${CXX}" == "clang++"; then
+if test "${CXX}" = "clang++"; then
    CLANGCXXFLAGS="-Qunused-arguments -Wno-parentheses-equality"
 else
    CLANGCXXFLAGS=""
````

**Comment by vslavik** [comment]
`deps/icu4c` is a third party submodule.

Instead of filing this sort of bugs, please submit patches. If you're qualified enough to compile from git and spot such issues, you're qualified enough to fix them, and are best equipped to do so, as you're the one being hit by them.

If you want to avoid digging in sources, I recommend using binaries or tarballs from https://poedit.net/download, or existing packages for whatever it is you're using.
