### ISSUE TITLE
warning: locale::facet::_S_create_c_locale name not valid if LC_ALL is not set

### ISSUE THREAD

**Issue by vgiorgi** [vslavik/poedit#632]
Using LC_ALL is strongly discouraged as it overrides everything: https://wiki.debian.org/Locale

If LC_ALL is not set, saving will rise this warning:
![image](https://user-images.githubusercontent.com/2556196/82411623-cc26bd80-9a7a-11ea-97bf-58029d510c36.png)
**locale::facet::_S_create_c_locale name not valid**

To reproduce it remember that after changing locale a restart is needed.

**Comment by vslavik** [comment]
When you created this issue, you were asked to read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md). Please do so, and follow the instructions therein; in particular, following the link in step 3 is a must. Thanks!

In particular, your claim *as you phrase it* is simply not true. Not having `LC_ALL` set doesn't present any difficulties neither for Poedit nor LucenePlusPlus nor libstd++ — it's the last one via the middle one that is giving you the warning. This is not surprising, as neither of the first two uses `LC_ALL` at all.

It seems more likely that you have in fact invalid locale settings on your system and the preachy bit of this issue is a red herring. If you believe this is incorrect and there *is* a bug in Poedit, please either submit a patch or description sufficiently detailed to provide reproductory evidence (see the link above).

**Comment by vslavik** [comment]
Submitter incommunicado  →  closing.
