### ISSUE TITLE
Incomplete text and inactive button for "Needs Work"

### ISSUE THREAD

**Issue by milotype** [vslavik/poedit#651]
There seems to be an issues with the "Needs Work" button.

- The text is cut off in Croatian – it should show "Zahtijeva doradu".
- The button itself cannot be activate by mouseclick. Activating through the menu or shortcut does work.

Poedit 2.4 (6007); MacOS 10.11.6

![NeedsWork](https://user-images.githubusercontent.com/43657314/88327118-0a648580-cd27-11ea-8340-84a5fb8c8640.png)

**Comment by vslavik** [comment]
Can you please clarify the *precise* meaning of "activate by mouseclick"? I.e. what *exactly* do you do with the mouse, given the many buttons and positions you can do it at? Do you perhaps have multiple items selected in the list, and all of the editing area disabled?

**Comment by milotype** [comment]
Steps to produce:
- I have only one item selected
- I move my mouse over the `Needs work`-button
- I cannot activate the button

Deactivating an already marked item aslo doesn't work.

Expected behaviour:
- It should be possible to activate and deactivate the button with the mouse, when single item is selected

Screenshot
- ![Button2](https://user-images.githubusercontent.com/43657314/88376860-83eb8a80-cd9e-11ea-80a3-e4ecdd383fe9.png)

**Comment by vslavik** [comment]
I'm trying to get a detailed description of something as utterly obvious as this because following your instructions, even after interpreting them with some reasonable assumptions (e.g. you don't say whether you actually *clicked* anything, but I assume you did), doesn't lead to any problem with clicking here (the Croatian translation being messed up I can confirm). So either the problem is specific to your 4 years old OS version (which I can't check quickly right now, on account of the old version) or there's *some* crucial difference between my and your interpretation of the above.

Let's try to identify which is it:

1. What does "cannot activate the button" mean? Does anything move? Does it toggle back? Does the control do nothing visible at all (this is what I assume you mean)?

2. Can you please check if this is *visual* only (no animation, but the item was marked correctly in the PO file), or factual too (no change made to the file)? I.e. use mouse to toggle the status, then go to another item in the list. Now that the toggled one is not selected, did its status change in the list? What about if you go back to it, is it now correct, or still wrong?

**Comment by milotype** [comment]
I hope it's not my "old" Mac OS version :-( …

IMO, it's most likely the first issue … not able to toggle when clicking the button …
Please note: it does work through the menu -> Edit -> Translation Needs Work

About the second question: toggling is generally not possible. In "BBEdit" (which I use for comparing files) there is no difference whatsoever, when I compare the source file and a saved file where I tried to toggle the item.

**Comment by vslavik** [comment]
> I hope it's not my "old" Mac OS version :-( …

I'm inclined to say it is. That is, a bug *in Poedit* that only manifests itself on 10.11. Time to install it in a VM.

> Please note: it does work through the menu -> Edit -> Translation Needs Work

Yes, you said that. The only relevant changes since 2.3, as far as I can tell, addressed visuals only: 5a19fd4d6ff1f6a67a552eed2be2d73f5be95a0b and 83d964dd97060e75cf47d104062b5f83d510133a

**Comment by milotype** [comment]
**Damn !!** I cannot upgrade my Mac Pro (early 2009) beyond 10.11.6 …

Please do check – if you haven't already – if the issue about `The text is cut off in Croatian – it should show "Zahtijeva doradu".` is also due to my "old" Mac.

Just to inform you:
Keyboard shortcut `⌘U` for toggling the button still works on my Mac OS version. So the issue isn't very important, so ignore it.

Thank you for all your help!

**Comment by vslavik** [comment]
> Please do check – if you haven't already

See above - that one I can see here.

**Comment by vslavik** [comment]
Confirmed occurring on 10.11, *not* occurring on 10.12.

**Comment by milotype** [comment]
OK, thank you!

**Comment by vslavik** [comment]
Related, but not quite the same: #593.

**Comment by vslavik** [comment]
Thank you for spotting and reporting this!

These turned out to be two unrelated bugs: one rendering, affecting all macOS versions and more translations than just Croatian, fixed in 730d57c, and one affecting OS X 10.10 and 10.11, fixed in 04594f2. 

Poedit 2.4.1 is going to happen, with the fixes included, soon — there was a new GNU gettext 0.21 release that warrants it anyway, even if it weren't for this.

P.S. If I could talk you into enabling beta updates in preferences, it would be appreciated, as you're an active user on older OS X versions likely to spot such breakages early...

**Comment by milotype** [comment]
> P.S. If I could talk you into enabling beta updates in preferences, it would be appreciated, as you're an active user on older OS X versions likely to spot such breakages early...

Yes, sure. I'm glad to help …
Before I activate it, please let me know, do the Beta versions overwrite the stable version, or can I ran two PoEdits simuntaniously (Beta and stable)?

**Comment by vslavik** [comment]
The preferences are shared, but nothing prevents you from having /Applications/Poedit.app and /Applications/Poedit-2.4.app for example as a backup...

**Comment by milotype** [comment]
Do you mean, I can simply duplicate "PoEdit.app" (currently I'm using v2.4) and rename the copy to "Poedit-2.4.app"? So my current "PoEdit.app" I could launch for checking future betas?

**Comment by vslavik** [comment]
Yes, as literally with any Mac app. Well, Poedit.app, naturally, not PoEdit.app, because Poedit isn't and never was spelled that way.

**Comment by milotype** [comment]
Just to inform you ...
I've installed Poedit 2.4.1. The issue #651 is solved from my point of view!

Also, I've activated the Beta-release updates as you've suggested ...
I'll keep in touch.

**Comment by vslavik** [comment]
Thanks for the confirmation!
