### ISSUE TITLE
Plural rules outdated

### ISSUE THREAD

**Issue by DJm00n** [vslavik/poedit#672]
Seems that plural rules in Poedit a bit outdated (At least for Russian and Ukrainian languages).

Latest [CLDR plurals.xml](https://github.com/unicode-org/cldr/blob/latest/common/supplemental/plurals.xml):
```xml
<pluralRules locales="ru uk">
   <pluralRule count="one">v = 0 and i % 10 = 1 and i % 100 != 11 @integer 1, 21, 31, 41, 51, 61, 71, 81, 101, 1001, …</pluralRule>
   <pluralRule count="few">v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, 1002, …</pluralRule>
   <pluralRule count="many">v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 11..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …</pluralRule>
   <pluralRule count="other">@decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …</pluralRule>
</pluralRules>
```

Current [language_impl_plurals.h](https://github.com/vslavik/poedit/blob/master/src/language_impl_plurals.h):
```cpp
{ "ru"   , { "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);", 3 } },
...
{ "uk"   , { "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);", 3 } },
```

Please update.

**Comment by vslavik** [comment]
> Please update.

Instead of creating bugging issues with "please update", do it yourself and submit a PR. Open source is *two*-way street.

That said, it is unclear why do you even think anything is wrong with the RU and UK rules you quote above. I rather suspect it comes from a misunderstanding of gettext's plural forms handling. A quick Google search suggests these as good enlightening links:
https://bugs.python.org/issue28692
https://code.djangoproject.com/ticket/26123
