### ISSUE TITLE
the source language is assumed to be English.

### ISSUE THREAD

**Issue by jmichault** [vslavik/poedit#675]
I get a "Language of the translation is the same as source language" error when I open a file to translate into English (I am using Esperanto as the source language).

Source language should be an option, it should not be forced to English.

**Comment by vslavik** [comment]
1. Source language is not assumed to be English, as you, well, assume. It is detected, pretty reliably (emphasis on *pretty*, e.g. mixed language content fails for obvious reasons, Esperanto may well fall into "too exotic to work" category).
2. Therefore, having followed [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) would have been beneficial, because e.g. attached file would have informed reasons for misdetection and would have made fixing any issues possible. Can you please provide it?
3. The PO file format is the thing that assumes (for not unreasonable reasons) that source code is in English, not Poedit. Poedit does in fact support an extension for specifying source language, and [it is documented](https://github.com/vslavik/poedit/wiki/PO-Extensions).

**Comment by jmichault** [comment]
Thank you very much for this clear and complete answer.
I searched unsuccessfully in the PO documentation for the field for the source language.
I am glad to learn that poedit manages an additional field for this purpose, which is perfect for me.

**Comment by vslavik** [comment]
> Thank you very much for this clear and complete answer.

Perhaps you could demonstrate your thanks by doing what I politely asked you to do (this being the 3rd time), instead of closing the issue?

**Comment by jmichault** [comment]
poedit version : 2.2.1
operating system : linux debian 10 (buster)
example file attached.

[komenci.md.po.zip](https://github.com/vslavik/poedit/files/5831574/komenci.md.po.zip)
