### ISSUE TITLE
Translate by key

### ISSUE THREAD

**Issue by bleizstudio** [vslavik/poedit#683]
Hi,

I have used PoEdit from time to time for years. I am on a big Php project via Symfony and I noticed that the key translation is missing an important thing. Today when we design a program we no longer put the sentences in it, we put keys and we put the message in a POT template.
This has the consequence for those who have the pro version, the translation assistance is not done. I use the tag to deliver a message to translator 
```
#. FR: J'aime PoEdit !
msgctxt "Bullet"
msgid "message.key"
msgstr "I love PoEdit !"
```
Would it be possible to put an option in the program so that it fetch the original message in the tag or in a tag without worrying about the key. I think this is totally feasible and it would allow PoEdit to evolve on current needs.

Regards,
Thank You

**Comment by vslavik** [comment]
Your POT files with translation include violate the file format specification.

Poedit is not going to support invalid POT files. 

This is a case of *You're Using It Wrong ™*, this - i.e. not putting actual text in `msgid` - is not how gettext works and how it should be used. See gettext manual. The issues you're inevitably facing with tools such as Poedit are not due to the tools' limitations, but simply a consequence of misusing gettext.
