### ISSUE TITLE
Dark Mode for Windows

### ISSUE THREAD

**Issue by Sencaid** [vslavik/poedit#810]
Hello, I would really like to use poedit, but since I'm very used to dark mode and I haven't found a way to make poedit dark, I wanted to ask if it will be supported in the future. If necessary, I would also work on implementing it. I don't think it should be that hard

**Comment by vslavik** [comment]
> I don't think it should be that hard

Great, looking forward to your PR since it's "not that hard" for you! I sure am glad you showed up, because this project really could use somebody so super-competent that this daunting task is "not that hard" for them. 

Closing in favor of your upcoming contribution.

(I just hope you wouldn't babble something like that with no competence or functional understanding of the code. But no, of course you wouldn't. I mean, what kind of person would do *that*? That would be like a whole new level of arrogance, wouldn't it?)
