### ISSUE TITLE
Possibility to Delete Translation Entries

### ISSUE THREAD

**Issue by ravage84** [vslavik/poedit#817]
Context:
It can happen, for example due to merge conflicts, to have duplicate translation entries in a PO file.
Currently, it seems there is no way to correct this invalid PO file state other than manually editing the file as there is no context menu item to delete a translation entry.

![grafik](https://github.com/vslavik/poedit/assets/625761/22b4e472-0483-4899-b495-347dcc454b5b)

Feature request:
Allow to delete translation entries  through the context menu.
At least, when there is an issue with them.

Rationale:
This breaks the process of keep working in Poedit for translation tasks.
That should not be necessary.

**Comment by vslavik** [comment]
> It can happen, for example due to merge conflicts, to have duplicate translation entries in a PO file.

This is something you should address when merging. Possible file corruptions due to merges are much wider than just duplicated entries, it doesn't make much sense to address just that particular one. And removing entries from generated translation files manually doesn't make sense outside that case either.
