### ISSUE TITLE
macOS suggestion shortcuts omit Cmd and prevent entering digits (German, Slovenian)

### ISSUE THREAD

**Issue by tsabsch** [vslavik/poedit#867]
On macOS, the shortcuts to use a suggested translation (from the TM) have changed from `⌘1`, `⌘2`, ... to just `1`, `2` etc. (although they are still displayed as `⌘1` etc.). This implies I cannot enter a digit if there is a suggestion with the same digit from the TM.

I believe this is a regression for 3.5, since I remember it working in previous versions.

If needed for reproduction, I can try to create a TM and po file that would make use of the TM.

Poedit: 3.5.1 (7273), free version
OS: macOS Sonoma 14.6.1

**Comment by vslavik** [comment]
Give me some credit: do you honestly think this would be universally broken (which is how you phrase it) with nobody noticing? Crucial basic, relevant information is missing here, including:

1. Just what *exactly* you mean by claiming that "the shortcuts have changed". That is, how *exactly* did you observe or otherwise determine that? What does the sidebar show? What does the *Edit → Suggestions* menu show?

2. Did you actually try to use a shortcut?

3. What are your language *and* keyboard settings? Including a description of just how exactly you _type_ "1", where is "1" located on your keyboard and what language do you use Poedit localized in?

4. Did you actually verify your "belief" that this is new in 3.5? If not, please do it, it's not that hard to download and run an older version.

**Comment by tsabsch** [comment]
Hi, it wasn't my intention to imply anything, I just tried to describe my observation. Apologies if I phrased it badly and insufficient; In my opinion your response was unnecessarily offensive anyway.

> with nobody noticing?

Well, I noticed something, right? 🙂 

> Just what exactly you mean by claiming that "the shortcuts have changed". That is, how exactly did you observe or otherwise determine that? What does the sidebar show? What does the Edit → Suggestions menu show?

Please see the following screenshot:

![Bildschirmfoto 2024-09-27 um 10 45 57](https://github.com/user-attachments/assets/46dc50ab-231e-4c53-a2fc-95b35c5eef54)


In this situation (without the open Edit->Suggestions menu though) and with the cursor having focus in the translation textbox, if I try to press ⌘+1 (or any other combination of ⌘+Digit up to 6), nothing happens. Yet, if I press just `1` (or any of the other digits until 6), the suggested translation is used. As you can also see in the screenshot, the Edit -> Suggestions menu shows the shortcuts without the ⌘. So there is a difference between the shortcuts shown in the sidebar and the ones in the menu. I actually wasn't aware of this in before.

> Did you actually try to use a shortcut?

I'm not sure if my description above already answered this. FWIW, other shortcuts, for example ⌘+B (use original string) or ⌘+T (open Terminology tab) work as expected and documented.

> What are your language and keyboard settings? Including a description of just how exactly you type "1", where is "1" located on your keyboard and what language do you use Poedit localized in?

I can reproduce this on both the built-in Macbook Keyboard (couldn't find an exact specification) and an external Magic Keyboard (Model A1644). I can reproduce this with the standard `ABC` layout (which is also known as `Mac International English`, if I'm not mistaken) and `EurKey v1.2`. Please see the following screenshot which shows the layout. The digits are located in the second top row (below the function keys).

![Bildschirmfoto 2024-09-27 um 11 10 19](https://github.com/user-attachments/assets/f77b8276-e041-4e35-8785-f3562fffd443)

I use Poedit localized to German.

> Did you actually verify your "belief" that this is new in 3.5? If not, please do it, it's not that hard to download and run an older version.

Fair enough, I should've done that in before. I can confirm my "belief" that the behaviour changed between 3.4.4 and 3.5; in 3.4.4, I can select suggestions via ⌘+1 etc. As can be seen in the following screenshot, the Edit->Suggestions menu also shows the shortcuts including the ⌘.

![Bildschirmfoto 2024-09-27 um 10 47 08](https://github.com/user-attachments/assets/2d2c270a-09e3-4710-903d-d14e9f8f5fd1)


Please let me know if I can provide any more information.

**Comment by vslavik** [comment]
Thanks a lot!

I was able to reproduce — it seems to be limited to German (hence the lack of immediate sh**storm after release...).

So far I ruled out
1. bad translation (always a suspect with German due to the use of <kbd>Strg</kbd> instead of <kbd>Ctrl</kbd> and the mapping of Ctrl-vs-⌘ in wxWidgets), which you confirmed w.r.t. 3.4.4 and
2. macOS' keyboard mapping of shortcuts (not a thing with German, it seems, but e.g. for Czech, where "2" and "ě" share the same key and you type "2" by holding <kbd>Shift</kbd> when you press the key, the ⌘2 shortcut is shown as ⌘ě). 

Too bad these were my only suspects. Investigating further.

**Comment by vslavik** [comment]
While this isn't proper fix (that's upcoming shortly), I was able to patch-up OTA translations to fix this. Poedit checks for translation updates daily. Once it does, it will get an updated translation that fixes the shortcut, so you should be good in ≤24h.

**Comment by tsabsch** [comment]
Happy to confirm this! Thank you very much for resolving this so quickly!
