### ISSUE TITLE
Conversion specifier error

### ISSUE THREAD

**Issue by concatenateNL** [vslavik/poedit#95]
When translating the English '% comments' from a WordPress theme language file into the Dutch '% reacties', an error is shown:
Error:'msgstr'is not a valid PHP format string, unlike 'msgid'. Reason: In the directive number 1, the character 'r' is not a valid conversion specifier. 
I tried to translate as '% antwoorden', but the same error occurs, except mentioning the character 'a'.

When copying (ctrl-b) the original text, no error is given. 
I double checked to see if there was a whitespace after the % character.

**Comment by bhaible** [comment]
It should not be the business of a PO editor to remove flags like `php-format` that xgettext has added. If the flag should not be there, it is either the programmer who needs to make sure it is removed (via a comment `# xgettext: no-php-format`), or the format string recognition heuristic of xgettext needs to be improved.

I just did the latter: In future releases, strings like `"100% complete"` will no longer be marked as a format string by default, unless they are in a context where a format string is required.
https://gitweb.git.savannah.gnu.org/gitweb/?p=gettext.git;a=commitdiff;h=a9583d31f7f7489a3c9529d658f0171e7e95a6cf
https://gitweb.git.savannah.gnu.org/gitweb/?p=gettext.git;a=commitdiff;h=dacdbfec87a01589480fe120db9395b528f2c922

I hope this will convince you to revert the specific change above, at some point (maybe in a year or two).

**Comment by vslavik** [comment]
@bhaible I agree with you in principle, but the (even self-imposed) pressure on my to be pragmatic is higher I think than on you (see also our git-using discussion w.r.t. 0.24 that surfaced the same difference in views). I'll keep this in mind, but it's going to take non-trivial time for everybody to use the latest tools.

On the note of "being business of", maybe you'll view #708 and https://savannah.gnu.org/bugs/index.php?60947 more favorably in that light — that, i.e. removal of unrecognized flags, is something I think is *in principle* not the business of `msgcat`, but it's also a very practical problem because multiple projects/languages use custom flags like that..

**Comment by bhaible** [comment]
> On the note of "being business of", maybe you'll view https://github.com/vslavik/poedit/issues/708 and https://savannah.gnu.org/bugs/index.php?60947 more favorably in that light — that, i.e. removal of unrecognized flags, is something I think is in principle not the business of msgcat, but it's also a very practical problem because multiple projects/languages use custom flags like that..

Thanks for bringing this up. We have now started to extend the PO file format: https://lists.gnu.org/archive/html/bug-gettext/2025-06/msg00018.html
